### ISSUE TITLE
Enhance import/export 

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#3615] opened 2018-09-18 15:59 UTC

**Comment by heiko-braun** [comment] 2018-12-13 16:37
@dhirajsb Is this something you look into as part of #3701?

**Comment by dhirajsb** [comment] 2018-12-13 19:43
Yes, supporting user provided parameters for imports is part of the CI/CD API. I am marking this as a duplicate of 3701.

**Comment by dhirajsb** [comment] 2018-12-13 19:44
Closing as duplicate of #3701

**Closed by dhirajsb** 2018-12-13 19:44 UTC
Labels: Epic, closed/duplicate, source/qe
