### ISSUE TITLE
Improve error reporting in UI

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5981] opened 2019-06-28 10:12 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Several times now I've found myself unable to troubleshoot an issue in the UI here's what usually happens: I get the _**Something is wrong** An error occurred while talking with the server. Please check your internet connection._, there's no error that can be seen in the Network or in the Console tabs of the developer tools.

Obviously some error occurred, doubtfully it has anything to do with the the server, I'm left with nothing to troubleshoot this. I wonder what happens when we get users reaching error states and we can't offer any ways to help them provide us with enough information to troubleshoot issues.

To me this is a blocking issue.

**Comment by riccardo-forina** [comment] 2019-06-28 10:15
Was the error screen the one without the sidebar? That one has only one failure point, the app couldn't retrieve the config.json.

**Comment by zregvart** [comment] 2019-06-28 10:43
Yeah, only error was shown without the sidebar. Though I had this happen before with the UI fully loaded, for instance in #5831 and the only way to troubleshoot that was to enable break-on-exception breakpoint and look through the obfuscated code/stack trace.

**Comment by riccardo-forina** [comment] 2019-06-28 10:52
Oh I missed that issue. That error ui is another one tho, and it does support showing the stack trace; that’s it if the error is passed to it at least. We have not been consistent on that, I’ll amend in a new PR

**Comment by asmigala** [comment] 2019-07-03 14:25
I just ran into this on 1.7.8:

![image](https://user-images.githubusercontent.com/9480152/60599532-eac28e00-9dae-11e9-9fc9-db4cb7037388.png)

Is the error screen supposed to be completely gone, or is the resolution here that there is an error in the console?

**Comment by heiko-braun** [comment] 2019-07-03 14:27
@riccardo-forina I guess this a question for you.

**Comment by gashcrumb** [comment] 2019-07-03 14:31
"Show error details" there would be relevant in this case I think, it's some kind of unexpected exception.

**Comment by gashcrumb** [comment] 2019-07-03 14:32
BTW, I think @riccardo-forina's PR was more about ensuring that "Show error details" button is available vs. avoiding problems, so if that's some reproducible issue it should go into a new bug report.

**Comment by asmigala** [comment] 2019-07-24 14:26
Couldn't reproduce the issue I showed above and the error pages now have "Show error details" button which does show some details, closing

**Closed by asmigala** 2019-07-24 14:26 UTC
Labels: cat/bug, group/ui, prio/p0
