### ISSUE TITLE
Datamapper before/after Aggregate - both sides of the mapping are equal (can't map anything)

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#4905] opened 2019-03-15 10:08 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
**Example 1:**
DB -> Split -> Datamapper -> Aggregate -> Google sheets
**Datamapper offers mapping from DB to DB**
![Screenshot from 2019-03-15 11-00-08](https://user-images.githubusercontent.com/8707251/54424078-6ae6ba00-4712-11e9-93c5-545e2758b944.png)

**Example 2:**
DB -> Split -> Aggregate -> Datamapper-> Google sheets
**Datamapper offers mapping from Google sheets to Google sheets**
![Screenshot from 2019-03-15 11-00-22](https://user-images.githubusercontent.com/8707251/54424051-5c000780-4712-11e9-80b0-a27db35f0723.png)

**Comment by christophd** [comment] 2019-03-15 13:02
I can not reproduce this behavior on branch 1.6.x (from yesterday evening)

![Bildschirmfoto 2019-03-15 um 13 57 21](https://user-images.githubusercontent.com/195264/54432863-a68d7e00-472a-11e9-852b-e76b7db5eb20.png)

![Bildschirmfoto 2019-03-15 um 13 57 52](https://user-images.githubusercontent.com/195264/54432867-ab523200-472a-11e9-803f-e88eb8ab6e8b.png)

Steps I did:

1) SQL start connection
2) Google Sheets finish connection
3) Split
4) Aggregate
5) Data Mapper

**Comment by heiko-braun** [comment] 2019-03-18 07:22
@mastepan Moving to done according to @christophd 's comments. Can you verify on recent 1.6.x?

**Comment by christophd** [comment] 2019-03-18 12:18
@mastepan this issue came in on master a few day ago and now is also on 1.6.x. So no need to retest against 1.6.x, thanks! PR fixing the issue is on its way https://github.com/syndesisio/syndesis/pull/4929

**Comment by mastepan** [comment] 2019-04-02 13:14
verified

**Closed** 2019-04-02 13:21 UTC
Labels: cat/bug, closed/verified, prio/p0, source/qe
