### ISSUE TITLE
Operator support for Fuse console and Apicurito on OpenShift

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#4154] opened 2018-11-23 13:06 UTC

**Comment by tplevko** [comment] 2019-01-15 08:01
I want to ask regarding the Apicurito operator. Recently I was updated, that it should be ready for testing. The  https://github.com/syndesisio/syndesis/issues/4152 is closed, but we couldn't find any operator image on dockerhub. The is most probably, that the [PR]( https://github.com/Apicurio/apicurito/pull/21) with operator still isn't merged and the image therefor is not built. Could this be pushed forward?

**Comment by EricWittmann** [comment] 2019-01-17 15:37
@tplevko I don't know enough about operators to properly assess that PR - but I'm more than happy to merge it if someone with relevant expertise gives me a +1 on it.  I was waiting for Heiko to approve it, but happy for anyone on the fuse team to do it.

**Comment by tplevko** [comment] 2019-01-22 07:51
@EricWittmann in syndesis the operator is something @rhuss works on, so maybe it's the right person to discuss the matter - @heiko-braun wdyt?

**Comment by astefanutti** [comment] 2019-01-24 14:20
The Fuse console operator is available at https://github.com/hawtio/hawtio-operator. The main use cases are implemented and can be tested and reviewed. It remains a bit of work related to configuration and documentation before it's completed.

**Comment by heiko-braun** [comment] 2019-01-28 13:55
@astefanutti Is this done?

**Comment by astefanutti** [comment] 2019-01-28 13:56
@heiko-braun not yet, still configuration and documentation to complete.

**Comment by rhuss** [comment] 2019-02-08 09:31
@tplevko @heiko-braun I'm happy to help to bootstrap such an operator, but don't have the cycles to work on it on my own.

**Comment by heiko-braun** [comment] 2019-02-08 12:49
Thanks @rhuss, but I think we both operators in place already

**Comment by astefanutti** [comment] 2019-02-08 14:41
The operator (upstream) is ready for review at https://github.com/hawtio/hawtio-operator.

Next action is to _adapt_ it for the Fuse product. I fear it has to be forked and all hard-coded elements like the CRD changed. I wonder if anybody has another idea on how to deal with it. What's plan for the Apicurito CRD? How Syndesis CRD and operator get productised?

**Comment by tplevko** [comment] 2019-02-11 10:03
@heiko-braun where can QE please find a build of apicurito operator image?

**Comment by EricWittmann** [comment] 2019-02-11 13:09
@tplevko The Apicurito operator is here:  https://github.com/Apicurio/apicurito/tree/master/operator

Do we need to build the docker image and upload it to docker hub?  If so, I can do that.

**Comment by janstey** [comment] 2019-02-11 20:27
This operator is needed for 7.3 I presume? We'll need to cherry pick it to https://github.com/jboss-fuse/apicurito/tree/1.x.redhat-7-x if so.

**Comment by mmajerni** [comment] 2019-03-07 15:02
Hi all, did somebody try this operator? https://github.com/Apicurio/apicurito/tree/master/operator

When I did all the steps it failed with this in the log:

`2019/03/07 14:53:51 uninstall: Failed deletion of "apicurito-43fu09089kx7d48xa3nuqzd3w": deploymentconfigs.apps.openshift.io "apicurito-ui" is forbidden: User "system:serviceaccount:tmp-operator:default" cannot delete deploymentconfigs.apps.openshift.io in the namespace "tmp-operator": no RBAC policy matched
2019/03/07 14:53:51 uninstall: Failed deletion of "apicurito-43fu09089kx7d48xa3nuqzd3w": imagestreams.image.openshift.io "apicurito-ui" is forbidden: User "system:serviceaccount:tmp-operator:default" cannot delete imagestreams.image.openshift.io in the namespace "tmp-operator": no RBAC policy matched
2019/03/07 14:53:51 uninstall: Failed deletion of "apicurito-43fu09089kx7d48xa3nuqzd3w": routes.route.openshift.io "apicurito" is forbidden: User "system:serviceaccount:tmp-operator:default" cannot delete routes.route.openshift.io in the namespace "tmp-operator": no RBAC policy matched
time="2019-03-07T14:53:51Z" level=error msg="failed to reconcile release for apiVersion=apicur.io/v1alpha1 kind=Apicurito name=tmp-operator/apicurito: install error: release apicurito-43fu09089kx7d48xa3nuqzd3w failed: deploymentconfigs.apps.openshift.io is forbidden: User \"system:serviceaccount:tmp-operator:default\" cannot create deploymentconfigs.apps.openshift.io in the namespace \"tmp-operator\": no RBAC policy matched"
`

Did I something wrong or it is broken?

**Comment by heiko-braun** [comment] 2019-03-13 12:57
@mmajerni Can you create a sparate issue (bug) for the problems you see?

**Comment by mmajerni** [comment] 2019-03-13 13:01
@heiko-braun sure I can but I cannot verify this because obviously, it is not working.

**Comment by heiko-braun** [comment] 2019-03-13 13:03
yes, but this an epic. we can link all related bugs from it.

**Comment by lgarciaaco** [comment] 2019-03-13 13:19
@mmajerni I think I could reproduce this issue, I come back to you later

**Comment by mmajerni** [comment] 2019-03-15 13:43
#4871 is closed so this can be closed as well.

**Closed** 2019-03-15 13:43 UTC
Labels: Epic
