### ISSUE TITLE
Can't create integration using twitter search as the first step - Please check your sorting arguments

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#4484] opened 2019-02-08 14:50 UTC
## This is a...

<pre><code>
[ ] Feature request
[ x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
It's not possible to create twitter integrations using the twitter search. Warning with "Please check your sorting arguments" is displayed.

## Steps to reproduce
1. crete tw connection
2. create new integration with twitter search as the base - it's not possible

![tw_based_integration](https://user-images.githubusercontent.com/4180208/52485453-2e76ea00-2bb9-11e9-8b8b-a36d0694ebb6.png)

**Comment by rhuss** [comment] 2019-02-11 09:19
@syndesisio/all This is a blocker for me. Can please anyone have a look into this ? 

Currently Syndesis is completely broken. See #4486 for a relevant stacktrace.

**Comment by heiko-braun** [comment] 2019-02-11 14:11
Closing as duplicate of #4486

**Closed by heiko-braun** 2019-02-11 14:11 UTC
Labels: cat/bug, notif/triage, prio/p0, source/qe
