### ISSUE TITLE
Import/Export API

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#967] opened 2018-01-09 10:41 UTC
Create an API for export / importing which can be used from the outside.

Beside separating this from the 'internal' API between UI and Rest, one non-functional requirement is probably also how to authenticate.

more to come.

**Comment by aileenc** [comment] 2018-03-02 15:02
Removing from TP4

**Comment by paoloantinori** [comment] 2018-03-12 15:42
pending discussion on oauth issues

**Comment by gaughan** [comment] 2018-09-15 14:12
@rhuss Definitely a candidate for 7.3, hopefully, it fits.

**Comment by heiko-braun** [comment] 2019-01-09 13:22
closed as duplicate of #3701

**Closed** 2019-01-09 13:22 UTC
Labels: Epic, closed/duplicate, group/server
