### ISSUE TITLE
Salesforce clientId and secret handling in exports

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#2036] opened 2018-03-15 20:20 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
The clientId and secret values for Salesforce OAuth are not encrypted in exported files.  Twitter OAuth information is encrypted, btw.

## Expected behavior
Salesforce OAuth values should be encrypted.

**Comment by zregvart** [comment] 2018-03-16 09:43
Duplicate of #2021

**Closed by zregvart** 2018-03-16 09:43 UTC
