### ISSUE TITLE
Changing Finish Connection does not update left-hand navigator

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#6148] opened 2019-07-12 11:36 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
1. Create integration with a start & finish connection
2. Save the connection & return to its overview
3. Click on the dustbin icon to remove the finish connection
4. Confirm the deletion using the confirm dialog

The wizard page for the finish connection is re-displayed allowing for the selection of a new finish connection. However, the old finish connection is still displayed in the left-hand navigator rather than the finish place-holder. Of course, clicking cancel should retain the original finish connection.

![Screenshot_20190712_123325](https://user-images.githubusercontent.com/1634180/61125335-7ae48f80-a4a1-11e9-9ff7-2880522360b5.png)

**Comment by riccardo-forina** [comment] 2019-07-12 11:46
Duplicate of #5883. Closing.

**Closed by riccardo-forina** 2019-07-12 11:46 UTC
Labels: notif/triage
