### ISSUE TITLE
Datamapper and template hidden when no datashape i available.

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#5408] opened 2019-05-17 14:43 UTC
## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Datamapper and template are not available when previous connections have no datashape. But both could be used to set a constant value in the body (and there’s no other way to do it).

**Comment by zregvart** [comment] 2019-05-19 16:38
Not sure setting constant value would be possible without a destination data shape. To what would you map the constant value?
We do have an example of a extension [to set the body](https://github.com/syndesisio/syndesis-extensions/tree/master/syndesis-extension-body).

**Comment by gaughan** [comment] 2019-05-19 17:25
Yes, setting the body would really help.

**Comment by christophd** [comment] 2019-05-19 18:32
We already discussed some things in #4207 which pretty much describes the same thing

**Comment by gashcrumb** [comment] 2019-05-29 20:33
We should close this as a duplicate of #4207, which I'm working on fixing.

**Closed by gashcrumb** 2019-05-29 20:33 UTC
Labels: notif/triage
