### ISSUE TITLE
Save as draft redirect not working

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#1947] opened 2018-03-12 10:26 UTC
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When I try to create an integration in draft state, the page is not redirected to integration listing. The integration is created, but there is no info for the user, it really happened.

## Screenshot

![save_as_draft](https://user-images.githubusercontent.com/4180208/37278392-dc23a374-25e7-11e8-9d52-45ae9f284715.gif)

## Tasks involved / Steps to Reproduce

1. Create some integration 
2. Click "save as draft"
3. Enter name of the integration
4. Click "save as draft"

**Comment by zregvart** [comment] 2018-03-12 11:25
I think this is a duplicate of #1828.

**Closed by zregvart** 2018-03-12 11:25 UTC
Labels: cat/bug, group/ui, target/tp4
