### ISSUE TITLE
Create Connection page displays a "Register Applications" subpage

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#1280] opened 2018-01-29 07:35 UTC
After numerous rounds of testing, an unfamiliar subpage titled "Register Application" appears. Previously tests sees the Twitter, Salesforces, AMQ, AWS S3 icons appear instead of this subpage.

![fi-register](https://user-images.githubusercontent.com/8625482/35498603-f8816b86-0509-11e8-8687-ef955dc24f09.png)

**Comment by gashcrumb** [comment] 2018-01-29 12:54
Do you have the javascript console log handy?  I think this one shows up if no connectors are returned by the backend.

**Comment by honghuac** [comment] 2018-01-30 15:35
@gashcrumb I have this trace from the Google Developer Tools console - https://gist.github.com/honghuac/6a8b87646100f2da3e377967d7d9fb1b

It does not seem to indicate anything useful, I think.

**Comment by gashcrumb** [comment] 2018-01-30 15:51
`502 bad gateway` indicates an unavailable backend which yes, the UI doesn't handle so well.

**Comment by zregvart** [comment] 2018-02-22 17:08
I think we can close this, the root cause was that the liveness probe was killing the rest pod, we have a workaround (removing the probe), but we need to find a proper fix for this.

See #1616

**Closed by zregvart** 2018-02-22 17:08 UTC
Labels: cat/bug, group/ui, target/tp4
