### ISSUE TITLE
No Data Type Specification was found error - when using Data Mapper

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#2063] opened 2018-03-19 06:40 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[X] Documentation issue or request
</code></pre>

## The problem

A "No Data Type Specification was found error" appears - when using Data Mapper - either as a step for a Salesforce Start Connection or a step for PostgresDB Start Connection.
Also, more documentation + console tips should be created to help the developer with the use of Data Mapper.

## Expected behavior

Data Mapper should be able to recognise the Salesforce or PostgresDB schema.

## Screenshot

![no-data-type](https://user-images.githubusercontent.com/8625482/37581417-797a22d8-2b83-11e8-8da7-da47418a8d18.png)

## Tasks involved / Steps to Reproduce

1. Set up a Salesforce connection as Start connection. Choose PostgresDB as a Finish connection.
2. Add a step between both connections. Note that the error appears.
3. Cancel the integration and start over.
4. Set up a PostgresDB connection as Start connection. Set up any connector as a Finish connection.
5. Add a step between both connections. Note that the error appears too.

**Comment by gashcrumb** [comment] 2018-03-19 12:38
What did you use as a query for the DB connection?

**Comment by igarashitm** [comment] 2018-03-19 18:56
I couldn't reproduce this. If I don't put any parameter for the SQL finish connection, then there's no way to add a datamapper step between them. If I add parameters into SQL finish connection, datamapper successfully opened.
Possibly you hit #1961 with a bit older revision and tried to add a datamapper step from a wrong indicator?

**Comment by honghuac** [comment] 2018-03-20 08:14
@gashcrumb insert into todo (TASK) values ('test');

**Comment by gashcrumb** [comment] 2018-03-20 12:41
Yeah, so with that SQL there would be no input data shape, so data mapping isn't possible.  If the data mapper steps shows up as available then that would be the bug here.  @igarashitm can you verify if the data mapper step can be chosen in this situation?

**Comment by igarashitm** [comment] 2018-03-20 12:54
With current upstream master it's not possible, so it's more likely he hit #1961.

**Comment by gashcrumb** [comment] 2018-03-20 13:24
Okay, awesome, so this is fixed on master, thanks!

**Closed by gashcrumb** 2018-03-20 13:24 UTC
Labels: cat/bug, ext/atlasmap, group/ui, prio/p2
