### ISSUE TITLE
[collection support]: Data mapper should select aggregate input shape as target

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#4618] opened 2019-02-18 13:19 UTC
When a data mapper is placed in front of an aggregate step the mapper does not select the shape of the aggregate as target document. Instead the next connector step input is selected as target shape.

![Bildschirmfoto 2019-02-18 um 14.07.02.png](https://images.zenhubusercontent.com/5be31e5e6d41381168d0a8e7/74190bdd-3057-4f8d-9190-2da58320a155)

Steps to reproduce:
- add finish connection
- add aggregate step before that connection
- add data mapper before aggregate step

Data mapper should pick aggregate input shape as target.

**Comment by gashcrumb** [comment] 2019-02-19 18:23
So I created this integration and this seems to behave as I'd expect:

![image](https://user-images.githubusercontent.com/351660/53037667-c8a42100-3448-11e9-88c8-24d1ba634638.png)

I verified in the data mapper host component via the debugger that in this case the aggregate step is picked up and supplied to the data mapper.  

Why don't I add some behavior though to the aggregate step to indicate where it got it's data shape from?

**Comment by gashcrumb** [comment] 2019-02-19 18:34
Found a way to reproduce it here, AMQ connections are handy since you can specify json instance and make up your own data type.  And, as it turns out the issue only shows up when the data mapper is first added.  When you go and revisit the step afterwards it looks correct.

**Comment by christophd** [comment] 2019-02-19 18:39
Yes it is a very special procedure to reproduce the problem. For me it was adding the mapper 1st then the aggregate. We have many ways to write the integrations right!?

**Comment by christophd** [comment] 2019-02-19 18:44
Another thing that comes to my mind. What about the last connection having that warning sign that a data mapping is required. Can we get rid of this? The aggregate right before the connection provides that required shape. And I tested that it works without an additional mapping between aggregate and the finish connection. Is a lower prio issue I guess though.

**Comment by mmuzikar** [comment] 2019-03-13 10:04
While verifying this issue I've run into a problem when aggregate step doesn't select the subsequent data shape as the output, if you change it (by removing step or adding another one). So you end up in a state like this. It is fixed by removing the aggregate step and then adding it again.
![image](https://user-images.githubusercontent.com/46345469/54270424-af8e1c00-457f-11e9-8465-534b2e4624b8.png)

**Comment by heiko-braun** [comment] 2019-03-13 11:07
@mmuzikar I think it might help to create a separate issue for the problem you see in https://github.com/syndesisio/syndesis/issues/4618#issuecomment-472357130

**Comment by mmuzikar** [comment] 2019-03-13 12:05
Opened #4866 regarding the issue with updating datashape in aggregate. So this issue is verified.

**Closed by mmuzikar** 2019-03-13 12:05 UTC
Labels: cat/bug, closed/verified, group/ui, prio/p0
