### ISSUE TITLE
Scheme and Host should not be required in Swagger file used in API Connector import

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#2316] opened 2018-04-10 14:00 UTC
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

    2018-04-09 21:23:44.837 ERROR [-,7f9e8bcd53977170,7f9e8bcd53977170,false] 1 --- [  XNIO-3 task-1] .s.e.v.h.e.SyndesisServerExceptionMapper : Internal Server Exception. Swagger specification does not provide a `schemes` definition and the Swagger specification was uploaded so the originating URL is lost to determine the scheme to use

    java.lang.NullPointerException: Swagger specification does not provide a `schemes` definition and the Swagger specification was uploaded so the originating URL is lost to determine the scheme to use
    	at java.util.Objects.requireNonNull(Objects.java:228) ~[na:1.8.0_151]
    	at io.syndesis.server.connector.generator.swagger.PropertyGenerators.determineHost(PropertyGenerators.java:166) ~[server-connector-generator-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
    	at io.syndesis.server.connector.generator.swagger.PropertyGenerators.lambda$withDefaultValue$3(PropertyGenerators.java:239) ~[server-connector-generator-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
    	at io.syndesis.server.connector.generator.swagger.PropertyGenerators.createProperty(PropertyGenerators.java:156) ~[server-connector-generator-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
    	at io.syndesis.server.connector.generator.swagger.BaseSwaggerConnectorGenerator.lambda$basicConnector$5(BaseSwaggerConnectorGenerator.java:150) ~[server-connector-generator-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
    	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[na:1.8.0_151]
    	at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1505) ~[na:1.8.0_151]
    	at io.syndesis.server.connector.generator.swagger.BaseSwaggerConnectorGenerator.basicConnector(BaseSwaggerConnectorGenerator.java:149) ~[server-connector-generator-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]

## Expected behavior

Connector should import.

## Request and Response Data

[kie-server-swagger.json.txt](https://github.com/syndesisio/syndesis/files/1894925/kie-server-swagger.json.txt)

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by zregvart** [comment] 2018-04-10 14:02
This is a duplicate of #2307

**Closed by zregvart** 2018-04-10 14:02 UTC
Labels: group/server, notif/triage
