### ISSUE TITLE
Connector: Google Mail

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2636] opened 2018-05-14 14:41 UTC

**Comment by oscerd** [comment] 2018-05-17 12:13
@kcbabo can you elaborate about user stories?

**Comment by oscerd** [comment] 2018-05-17 16:38
As first step I'll do an analysis of what the camel component offers actually :-)

**Comment by kcbabo** [comment] 2018-05-18 16:51
@oscerd Hey Andrea - I can definitely create a user story.  Before I go there, however, I would like to brainstorm with you on (a) what's possible and (b) what's a reasonably minimal first pass at an implementation based on what the GMail API offers.

Here are some initial rough thoughts ...
- Connection config : username, password, OAuth?
- Two actions : send email, receive email
- Send email action behavior
  - Action config : default subject (optional), default to (optional), default cc (optional), default bcc (optional)
  - Data shape should have : subject, to, cc, bcc, body as fields
  - Data shape values override action config values when specified
- Receive email action behavior
  - Action config : label name (optional)
  - Data shape is same as send

**Comment by kcbabo** [comment] 2018-05-18 16:53
BTW, totally agree with @rhuss that templating would be useful.  I don't think it's required, but I see it as super helpful.  An awesome approach would be to have a templating step (e.g. velocity) that produced a data shape based on the tokens defined in the template.  User could then map data to the template values using data mapper.

**Comment by oscerd** [comment] 2018-05-21 08:28
Thanks for your ideas @kcbabo I will come back with information on internals of the component

**Comment by oscerd** [comment] 2018-05-24 15:18
Actually the Camel-google-mail component doesn't work on Spring-Boot

`2018-05-24 14:12:39.665  WARN 1 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.NoSuchMethodError: javax.servlet.ServletContext.getClassLoader()Ljava/lang/ClassLoader;
2018-05-24 14:12:39.677  INFO 1 --- [           main] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-05-24 14:12:39.686 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.NoSuchMethodError: javax.servlet.ServletContext.getClassLoader()Ljava/lang/ClassLoader;
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:137) ~[spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at io.syndesis.example.Application.main(Application.java:13) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [project-0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [project-0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [project-0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:587) [project-0.1-SNAPSHOT.jar:na]
Caused by: java.lang.NoSuchMethodError: javax.servlet.ServletContext.getClassLoader()Ljava/lang/ClassLoader;
	at io.undertow.websockets.jsr.Bootstrap.handleDeployment(Bootstrap.java:92) ~[undertow-websockets-jsr-1.4.20.Final.jar!/:1.4.20.Final]
	at io.undertow.servlet.core.DeploymentManagerImpl.handleExtensions(DeploymentManagerImpl.java:263) ~[undertow-servlet-1.4.20.Final.jar!/:1.4.20.Final]
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:153) ~[undertow-servlet-1.4.20.Final.jar!/:1.4.20.Final]
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.createDeploymentManager(UndertowEmbeddedServletContainerFactory.java:412) ~[spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.getEmbeddedServletContainer(UndertowEmbeddedServletContainerFactory.java:234) ~[spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:164) ~[spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134) ~[spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	... 16 common frames omitted`

I have a skeleton of the connector and the validation seems to be fine, but when I run an integration I got this error. It's the same if we use the plain starter from Camel, so first we need to fix this in Camel and then wait for a release.

**Comment by kcbabo** [comment] 2018-05-24 15:20
Can we fix this upstream and backport the fix to our product branch for Fuse 7?

**Comment by zregvart** [comment] 2018-05-28 12:09
@oscerd I don't think so, all that is needed is to configure properties in the connector descriptor. Some while back I created [this example](https://github.com/zregvart/syndesis/commit/d198876e92eeeddb787cbb5438db9a179d924890#diff-4b3dee35d7bec4106f2d30ff80f60f7d).

From reading [docs](https://developers.google.com/identity/protocols/OpenIDConnect#server-flow), it seems to me that `authorizationUrl` needs to be `https://accounts.google.com/o/oauth2/v2/auth` and `tokenUrl` needs to be `https://www.googleapis.com/oauth2/v4/token`.

**Comment by oscerd** [comment] 2018-05-28 12:10
https://www.googleapis.com/oauth2/v4/token doesn't exist anymore

**Comment by oscerd** [comment] 2018-05-28 12:11
https://accounts.google.com/o/oauth2/token this is the one to use

**Comment by zregvart** [comment] 2018-05-28 12:12
It's still advertised in the OpenID discovery at:

https://accounts.google.com/.well-known/openid-configuration

**Comment by oscerd** [comment] 2018-05-28 12:14
At least yesterday posting something there returned a 404, but let me check again.

**Comment by oscerd** [comment] 2018-05-28 14:45
The API for the consumer side of this connector can use two different approach: the first is a get where you can specify the id of a message and obtain it, the other is list and in that way you're able to get user inbox content paginated. So probably it makes sense to use list?

**Comment by nicolaferraro** [comment] 2018-05-28 16:12
I think the expected behavior of the "receive mail" action should be of syndesis processing all new messages, filtered by a optional label, that are received by gmail after the integration is deployed. Did I interpret it correctly @kcbabo ?

In this case I don't see it as a "list operation", unless it's a repeated "list" that can be filtered to return e.g. "all messages received after the last message fetched" (together with something for initialization). I hope the Camel component or the API support something like that.

I think we should create a stream of messages from periodic API calls under the hood.

**Comment by kcbabo** [comment] 2018-05-28 17:51
That's right - just pull all mail, optionally filtered by label.  It would be a list in the background, but that should be transparent to the end user.

Also agree with the point around idempotency - users will expect that they don't process the same messages over and over.  Perhaps use the state of the message (read vs. unread) to push that responsibility into Gmail vs. tracking it in Syndesis?

**Comment by oscerd** [comment] 2018-05-30 06:20
Actually the API from Camel permits only to list the messages by userId. We are unable to filter by label directly with camel.

**Comment by oscerd** [comment] 2018-05-31 13:34
After 4 days of work on the consumer side, I can say it doesn't work from a Camel consumer perspective, at least since we use the api component, the parameters that we need to make query on our inbox aren't available in Syndesis. So I believe it will be better to work in the following way:

- Add the producer side, to be able to send email
- Write a different component to consume stuff as stream in camel and then backport in our branch (we can add a second component in the same camel-google-mail with a different schema)
- Use it directly in Syndesis

I try to work on workaround and different approach but I don't like the final result and I believe it won't be good for a citizen integrator. If we all agree on this approach I will open a PR for the producer side once it's ready and then I'll start working on second component on Camel upstream, to backport in our branch.

**Comment by nicolaferraro** [comment] 2018-05-31 15:14
Seems reasonable. The Camel component currently maps single API operations, like sending a email or searching. I think you've also evaluated Google pub/sub for the implementation, right?

In order to implement something to "stream" emails, we need to execute a workflow on top of the standard APIs. There are also multiple strategies we can use to "mark messages as received" to avoid duplicates.

So a "stream" endpoint that is able to receive a continuous flow of emails may be useful and I think we can implement it in both Syndesis and Camel, but keep it only in Camel by Fuse 8.

**Comment by oscerd** [comment] 2018-06-04 10:00
@kcbabo I believe it makes more sense to give priority to the action configuration than datashape to avoid confusion. If I set a to address in the action config, I'd expect the email to arrive to that address without being override from datashape. WDYT?

**Comment by kcbabo** [comment] 2018-06-05 10:30
BTW, even if the underlying components are different for send and receive, can we please have this as a single connector in the Syndesis UI?  Having a separate connector for GMail Send and GMail Receive is suboptimal from my POV.

**Comment by oscerd** [comment] 2018-06-05 10:33
It shouldn't be a problem, because we are able to specify component scheme also at action level.

**Comment by kcbabo** [comment] 2018-06-05 10:47
I'm cool with not doing the datashape stuff for now as long as we can add that later.

**Comment by oscerd** [comment] 2018-06-05 10:58
The datashape stuff is already done as described.

**Comment by kcbabo** [comment] 2018-06-05 13:20
Sorry, I misread your question above.  I thought you were saying you wanted to do action only and not data shape.  I will update the user story.

In terms of what takes precedence (action vs. data shape), I feel like people want per-message content as an override for static definitions of configuration.  That said, I recognize that could be my own crazy view of the world. :-)  We should socialize this with the larger team and go with majority opinion.  We could always had a configuration setting that says "prefer per-message data" or something like that and then a user has a choice of which has precedence.

**Comment by oscerd** [comment] 2018-06-06 15:01
I have a new component for this purpose: https://github.com/apache/camel/tree/master/components/camel-google-mail/src/main/java/org/apache/camel/component/google/mail

the scheme is google-mail-stream. Still some things to add but the base already works. Since in syndesis upstream we are using camel-2.21.0, I suppose we may need to backport this to Fuse Camel used in Fuse 7 and changed the dependency but I'm not sure. @paoloantinori @rhuss WDYT?

**Comment by paoloantinori** [comment] 2018-06-06 16:17
As far as I know we are not planning to touch Camel version during Fuse 7 cycle.

I will confirm that, but in the meanwhile, I'd start looking at a way to have an independent copy/reference of that new component.

**Comment by kcbabo** [comment] 2018-06-06 17:08
We need to backport these features to the Fuse 7.x branch as necessary.

**Comment by zregvart** [comment] 2018-06-06 20:59
Perhaps in the future we could develop the component in Syndesis codebase/namespace and donate it to Camel. A while back we had a Camel component in Syndesis codebase so this should not be an issue.

**Comment by rhuss** [comment] 2018-06-07 10:36
👍 for including it in Syndesis (maybe even as part of the connector ?) until Camel is released with this update. I think maintaining some small duplicate code is easier to handler then forking and patching a whole project. And also because I dare to rely on the JBoss Nexus for delivering dependencies to upstream.

@oscerd would it be hard to embedd the gmail component directly in the connector as some inner classes ?

**Comment by oscerd** [comment] 2018-06-07 10:39
I think it won't be easy, I need to embed the whole camel-google-mail component from upstream to have this and I don't think it is feasible in an easy way. By the way I already opened a PR againt 7.1.x 

https://github.com/jboss-fuse/camel/pull/408

Let me know if it must be merged or not.

**Comment by oscerd** [comment] 2018-06-08 13:34
I have a working consumer connector here:

https://github.com/oscerd/syndesis/tree/gmail-connector-2.21.0-SNAPSHOT

I built Camel from Fuse Camel 7.1.x branch and use it inside Syndesis and it works well. I assumed to list the email in our inbox by unread label, then we consume these emails in a batch model, like S3 consumer and once we finished, we marked the consumed emails as read in the onCompletion phase. Is it possible to specify the max Results we want for each poll, the delay and if we want to mark the mail as read once we consumed it. We just need a pinned build of camel from Fuse 7.1.x branch and we can update the version in Syndesis. Once we have that I can open a PR.

I still have to add the oauth flow here because of special fields.

**Comment by oscerd** [comment] 2018-06-08 14:17
@rhuss with @nicolaferraro and @lburgazzoli we found a way to use a SNAPSHOT version of Camel inside Syndesis, I believe this could be formalized in some way, to be able to use a snapshot version without all the troubles I faced this time.

**Comment by oscerd** [comment] 2018-06-13 06:28
Through #2803 we now have the stream consumer for Gmail. The only thing missing is the oauth flow.

**Comment by mcada** [comment] 2018-06-14 11:59
To be more user-friendly - are user Id and Access Token necessary when creating gmail connection?
Gmail api allows using "me" as special value of user Id which means currently authenticated user.
We can generate access token from refresh token by ourselves. I guess it already does generate it as access token is valid only for a short period of time.

**Comment by oscerd** [comment] 2018-06-14 12:01
That option are there for the oauth flow integration that I still need to add, because it requires additional fields. Once we have the flow added it will be transparent to the end user.

**Comment by oscerd** [comment] 2018-06-25 09:23
I believe this is done.

**Closed** 2018-06-27 12:13 UTC
Labels: Epic, cat/feature, group/connector, prio/p1
