### ISSUE TITLE
API ExternalURL should include /api if appropriate

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#3820] opened 2018-10-12 15:11 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

In the swagger for https://github.com/KurtStam/syndesis-quickstarts/tree/master/api-provider, no contextPath is specific. So as far as the user is concerned the URL at which the API runs is
{$externalURL}/todo

however it is 

{$externalURL}/api/todo

There is another issue opened on this why we are doing this, but if we keep doing it then we should include the /api part in the externalURL. It's complete guess work for the enduser right now.

**Comment by gaughan** [comment] 2018-10-18 16:10
This would have high visibility for any demo of the feature. @heiko-braun

**Comment by heiko-braun** [comment] 2018-10-18 16:20
@zregvart Is the a duplicate issue? I remember we talked about this before ...

**Comment by zregvart** [comment] 2018-10-18 17:30
@heiko-braun yeah this should be squashed with #3746

**Comment by heiko-braun** [comment] 2018-10-18 18:43
Closed as duplicate of  #3746

**Closed by heiko-braun** 2018-10-18 18:43 UTC
Labels: notif/triage
