### ISSUE TITLE
Connector can be deleted even when connection using it exists

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#2194] opened 2018-03-29 08:53 UTC
## This is a...

<pre><code>
[ ] Feature request
[x ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

The Console fails to load connections page, after a "successful" purge of an API Client Connector, while a connection that uses this Connector still exists.

This error was detected in the syndesis-rest pod log:
https://gist.github.com/honghuac/836f7de644fc23c72c29a01f99b6e7d8

## Expected behavior

Maybe an alert should be thrown to prevent API Client Connector from becoming deleted, if a connection that uses it exists?

**Comment by sjcox-rh** [comment] 2018-04-02 16:46
I feel like this has been addressed before, but perhaps the solution has yet to be implemented? 

It was suggested to show a modal informing the user that the connector is in use and could potentially cause issues with an integration. Something to that effect.

@gashcrumb, @dongwang, @aglass I can't find the issue but do you know what I'm talking about?

**Comment by amysueg** [comment] 2018-04-02 17:16
Is this the modal you are thinking of @sjcox-rh ?https://github.com/syndesisio/syndesis/blob/master/ux/designs/connector-step-extensions/img/extensions_list_delete_warning.png

It's from the Connector & Step Extensions #806 -https://github.com/syndesisio/syndesis/blob/master/ux/designs/connector-step-extensions/connector-step-ext.md

**Comment by gashcrumb** [comment] 2018-04-02 17:41
This is a duplicate of https://github.com/syndesisio/syndesis/issues/2124 really I think, which I think duplicates some other issues as well.

Personally I'm -1 on an informative modal and more +1 on disabling/removing the button if a connector or extension is referenced by a connection/integration.

**Comment by gashcrumb** [comment] 2018-04-02 17:42
Ah, here's the original issue -> https://github.com/syndesisio/syndesis/issues/1827

So this is a result of being able to delete a connector that's in use.

**Comment by dongniwang** [comment] 2018-04-02 18:01
I think wether we want to go with disabling/removing the button or provide an modal depends on how we are handling this type of interaction in the rest of the application. I'd rather keep it consistent at this point. 

@amysueg @sjcox-rh

**Comment by paoloantinori** [comment] 2018-04-10 11:06
closing this as a duplicate of #2124 . please continue the discussion on the original issue

**Closed by paoloantinori** 2018-04-10 11:06 UTC
Labels: notif/triage, notif/uxd
