### ISSUE TITLE
[UI] Don't require click on the tooltip to display it

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#5714] opened 2019-06-13 07:54 UTC
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Currently when there is a tooltip in the UI, user needs to click on the "?" icon to display the tooltip. It would be better to display the tooltip on hover action
![out](https://user-images.githubusercontent.com/7081216/59414035-127e9180-8dc1-11e9-96a4-5b91af93a5d4.gif)

**Comment by dongniwang** [comment] 2019-06-13 17:34
I don't think this is a regression. 

Patternfly supports two kinds of help element, one is tooltip, the other one is popover, find out more information about this [here](https://www.patternfly.org/pattern-library/forms-and-controls/help-on-forms/). 

We chose to use popover here because:
> The help text is displayed in a popover when the user clicks on the information icon. Popovers are triggered on click, are mobile-friendly, and are ideal when links need to be listed in the help. 
And popover is a more accessible approach. 

Tooltip usually appears on hover, and it is a more ideal solution when we only need to provide a small amount of information in addition to a field label.

**Comment by seanforyou23** [comment] 2019-06-24 14:59
I also tend to think that these should have always been popovers, with the accessibility consideration at the forefront of the reasoning. There isn't an elegant way to consume information that's only available on hover when using screen-readers/mobile devices. For supplementary information, it could be ok, but for critical information that may often contain rich content (like links), Popover is probably the best UI pattern to use.

**Comment by seanforyou23** [comment] 2019-06-27 13:47
I think we can close this one, feel free to reopen if I've overlooked anything!

**Closed by seanforyou23** 2019-06-27 13:47 UTC
Labels: cat/bug, group/ui, prio/p2, source/qe
