### ISSUE TITLE
Tech extension: can't retry a failed upload

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#755] opened 2017-12-14 12:16 UTC
In case of error while uploading an extension i.e. the extension do not have the required metadata, the UI gets stuck to the upload page but it is not possible to retry to upload the extension again as the upload button does not show the file chooser any more.

**Comment by deeleman** [comment] 2018-03-16 16:00
@lburgazzoli could you email me an invalid extension .jar file so I can replicate the issue? I tried with a regular random JAR file with no success, since the validation in place intercepts the request, as expected.

**Comment by gashcrumb** [comment] 2018-03-16 18:17
@deeleman if you don't mind building one they're in this repo -> https://github.com/syndesisio/syndesis-extensions

**Comment by gashcrumb** [comment] 2018-03-16 18:23
Actually testing it here I don't see the file chooser button going away or anything, just the error message and can still choose a file or drag/drop a file into the drop target area, so can't reproduce.

**Comment by deeleman** [comment] 2018-03-19 10:38
Both @lburgazzoli and me agreed on closing this issue since it seems we cannot replicate it and might be solved already. Reopen should you spot this issue happening again. :)

**Closed by deeleman** 2018-03-19 10:38 UTC
Labels: cat/bug, group/ui, prio/p1
