### ISSUE TITLE
Syndesis install using build.sh is not working on master branch

### ISSUE THREAD

**Issue by dhirajsb** [syndesisio/syndesis#6976] opened 2019-10-22 02:34 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Using build.sh in app directory, installation is failing on master branch using command:
```
./build.sh install --local -p syndesis -y
```
The operator installs all deployment configs except the DB for some reason. 
```
rh-wfh-dbokde:app dbokde$ oc get dc
NAME                  REVISION   DESIRED   CURRENT   TRIGGERED BY
syndesis-meta         1          1         1         config
syndesis-oauthproxy   1          1         1         config
syndesis-operator     1          1         1         config,image(syndesis-operator:latest)
syndesis-server       1          1         1         config
syndesis-ui           1          1         1         config
```
Operator log shows the following repeated error
```
{"level":"error","ts":1571686043.8849003,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"syndesis-controller","request":"syndesis/app","error":"roles.rbac.authorization.k8s.io \"syndesis-editor\" is forbidden: attempt to grant extra privileges: [{[get] [] [deploymentconfigs/finalizers] [] []} {[list] [] [deploymentconfigs/finalizers] [] []} {[create] [] [deploymentconfigs/finalizers] [] []} {[update] [] [deploymentconfigs/finalizers] [] []} {[delete] [] [deploymentconfigs/finalizers] [] []} {[deletecollection] [] [deploymentconfigs/finalizers] [] []} {[watch] [] [deploymentconfigs/finalizers] [] []} {[patch] [] [deploymentconfigs/finalizers] [] []} {[get] [apps.openshift.io] [deploymentconfigs/finalizers] [] []} {[list] [apps.openshift.io] [deploymentconfigs/finalizers] [] []} {[create] [apps.openshift.io] [deploymentconfigs/finalizers] [] []} {[update] [apps.openshift.io] [deploymentconfigs/finalizers] [] []} {[delete] [apps.openshift.io] [deploymentconfigs/finalizers] [] []} {[deletecollection] [apps.openshift.io] [deploymentconfigs/finalizers] [] []} {[watch] [apps.openshift.io] [deploymentconfigs/finalizers] [] []} {[patch] [apps.openshift.io] [deploymentconfigs/finalizers] [] []}] user=&{system:serviceaccount:syndesis:syndesis-operator 2eb58a03-f437-11e9-aa70-627724c69e9e [system:serviceaccounts system:serviceaccounts:syndesis system:authenticated] map[]} ownerrules=[{[get] [ user.openshift.io] [users] [~] []} {[list] [ project.openshift.io] [projectrequests] [] []} {[get list] [ authorization.openshift.io] [clusterroles] [] []} {[get list watch] [rbac.authorization.k8s.io] [clusterroles] [] []} {[get list] [storage.k8s.io] [storageclasses] [] []} {[list watch] [ project.openshift.io] [projects] [] []} {[create] [ authorization.openshift.io] [selfsubjectrulesreviews] [] []} {[create] [authorization.k8s.io] [selfsubjectaccessreviews] [] []} {[get] [] [] [] [/healthz /healthz/*]} {[get] [] [] [] [/version /version/* /api /api/* /apis /apis/* /oapi /oapi/* /openapi/v2 /swaggerapi /swaggerapi/* /swagger.json /swagger-2.0.0.pb-v1 /osapi /osapi/ /.well-known /.well-known/* /]} {[create] [ authorization.openshift.io] [selfsubjectrulesreviews] [] []} {[create] [authorization.k8s.io] [selfsubjectaccessreviews] [] []} {[create] [authorization.k8s.io] [selfsubjectaccessreviews selfsubjectrulesreviews] [] []} {[create] [ build.openshift.io] [builds/docker builds/optimizeddocker] [] []} {[create] [ build.openshift.io] [builds/jenkinspipeline] [] []} {[create] [ build.openshift.io] [builds/source] [] []} {[get] [] [] [] [/api /api/* /apis /apis/* /healthz /openapi /openapi/* /swagger-2.0.0.pb-v1 /swagger.json /swaggerapi /swaggerapi/* /version /version/]} {[delete] [ oauth.openshift.io] [oauthaccesstokens oauthauthorizetokens] [] []} {[get] [] [] [] [/version /version/* /api /api/* /apis /apis/* /oapi /oapi/* /openapi/v2 /swaggerapi /swaggerapi/* /swagger.json /swagger-2.0.0.pb-v1 /osapi /osapi/ /.well-known /.well-known/* /]} {[impersonate] [authentication.k8s.io] [userextras/scopes.authorization.openshift.io] [] []} {[create get] [ build.openshift.io] [buildconfigs/webhooks] [] []} {[impersonate] [] [serviceaccounts] [] []} {[get] [] [namespaces] [] []} {[get] [ project.openshift.io] [projects] [] []} {[impersonate] [] [serviceaccounts] [] []} {[get list create update delete deletecollection watch] [] [pods pods/exec services endpoints persistentvolumeclaims configmaps secrets serviceaccounts] [] []} {[get list create update delete deletecollection watch patch] [] [replicationcontrollers replicationcontrollers/scale] [] []} {[get list create update delete deletecollection watch patch] [apps] [daemonsets deployments deployments/scale replicasets replicasets/scale statefulsets statefulsets/scale] [] []} {[get list create update delete deletecollection watch patch] [extensions] [daemonsets deployments deployments/scale ingresses networkpolicies replicasets replicasets/scale replicationcontrollers/scale] [] []} {[get list watch] [] [bindings events limitranges namespaces/status pods/log pods/status replicationcontrollers/status resourcequotas resourcequotas/status] [] []} {[get list create update delete deletecollection watch patch] [ build.openshift.io] [buildconfigs buildconfigs/webhooks builds] [] []} {[create] [ build.openshift.io] [buildconfigs/instantiate buildconfigs/instantiatebinary builds/clone] [] []} {[update] [ build.openshift.io] [builds/details] [] []} {[get list watch] [ build.openshift.io] [builds/log] [] []} {[get list create update delete deletecollection watch patch] [ apps.openshift.io] [deploymentconfigs deploymentconfigs/scale] [] []} {[create] [ apps.openshift.io] [deploymentconfigrollbacks deploymentconfigs/instantiate deploymentconfigs/rollback] [] []} {[get list watch] [ apps.openshift.io] [deploymentconfigs/log deploymentconfigs/status] [] []} {[get list create update delete deletecollection watch patch] [ image.openshift.io] [imagestreams imagestreamimages imagestreammappings imagestreams/secrets imagestreamtags] [] []} {[create] [ image.openshift.io] [imagestreamimports] [] []} {[get list watch] [ image.openshift.io] [imagestreams/status] [] []} {[get list create update delete deletecollection watch patch] [route.openshift.io] [routes] [] []} {[get list create update delete deletecollection watch patch] [ template.openshift.io] [processedtemplates templateconfigs templateinstances templates] [] []} {[get list create update delete deletecollection watch patch] [ build.openshift.io] [buildlogs] [] []} {[get list create update delete deletecollection watch] [syndesis.io] [* */finalizers] [] []} {[get list create update delete deletecollection watch] [] [pods services endpoints persistentvolumeclaims configmaps secrets serviceaccounts] [] []} {[get] [] [pods/log] [] []} {[get list create update delete deletecollection watch] [] [replicationcontrollers replicationcontrollers/scale replicationcontrollers/status] [] []} {[get list create update delete deletecollection watch] [ build.openshift.io] [builds buildconfigs builds/details buildconfigs/webhooks buildconfigs/instantiatebinary builds/log] [] []} {[get list create update delete deletecollection watch patch] [ apps.openshift.io] [deploymentconfigs deploymentconfigs/scale] [] []} {[create] [ apps.openshift.io] [deploymentconfigrollbacks deploymentconfigs/instantiate deploymentconfigs/rollback] [] []} {[get list watch] [ apps.openshift.io] [deploymentconfigs/log deploymentconfigs/status] [] []} {[get list create update delete deletecollection watch patch] [ image.openshift.io] [imagestreams imagestreamimages imagestreammappings imagestreams/secrets imagestreamtags] [] []} {[get list watch] [ image.openshift.io] [imagestreams/status imagestreamimports] [] []} {[get list] [] [events] [] []} {[get list create update delete deletecollection watch] [rbac.authorization.k8s.io] [roles rolebindings] [] []} {[get list create update delete deletecollection watch patch] [ template.openshift.io] [processedtemplates templateconfigs templateinstances templates] [] []} {[get list create update delete deletecollection watch] [authorization.openshift.io] [rolebindings] [] []} {[get list create update delete deletecollection watch patch] [route.openshift.io] [routes routes/custom-host] [] []} {[get list create update delete deletecollection watch] [camel.apache.org] [*] [] []} {[get list create update delete deletecollection watch] [monitoring.coreos.com] [alertmanagers prometheuses servicemonitors prometheusrules] [] []} {[get list create update delete deletecollection watch] [integreatly.org] [grafanadashboards] [] []} {[get list watch] [serving.knative.dev] [services] [] []} {[get list watch] [eventing.knative.dev] [channels] [] []} {[get] [ image.openshift.io] [imagestreams/layers] [] []}] ruleResolutionErrors=[]","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/circleci/project/install/operator/vendor/github.com/go-logr/zapr/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/circleci/project/install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/circleci/project/install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/circleci/project/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/circleci/project/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/circleci/project/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

**Comment by dhirajsb** [comment] 2019-10-22 02:35
It failed with or without `--local`.

**Comment by phantomjinx** [comment] 2019-10-22 12:08
Error linked to this [change](https://github.com/syndesisio/syndesis/pull/6802).
Unsurprisingly, I didn't push before testing so intrigued why it's now failing.

**Comment by lgarciaaco** [comment] 2019-10-22 12:39
I dont get it ... https://github.com/syndesisio/syndesis/pull/6802 is addressing just that

**Comment by phantomjinx** [comment] 2019-10-22 12:56
I saw the error when I was developing and added the ```deploymentconfig/finalizers``` to some part of the resources but not others. So maybe I've missed out some this permission from some section of the resources?

**Comment by phantomjinx** [comment] 2019-10-23 10:21
I've tried repeating this over the course of the last couple of days.
Executing the given command, ie. ```./build.sh ....``` results in just the operator being build, ie. nothing configured for deployment:
```
....
--> Creating resources with label build=syndesis-operator ...
    imagestream "syndesis-operator" created
    buildconfig "syndesis-operator" created
--> Success
/tmp/syndesis-operator-docker6Rc.tar
build/
build/_output/
build/_output/bin/
build/_output/bin/syndesis-operator
build/_output/bin/openapi-gen
build/Dockerfile
build/conf/
build/conf/config.yaml
build/bin/
build/bin/entrypoint
build/bin/user_setup
Dockerfile
Uploading archive file "/tmp/syndesis-operator-docker6Rc.tar" as binary input for the build ...
build "syndesis-operator-1" started
⏚ θ92° [: … operator] master(+11/-1)+ ± pods
NAME                        READY     STATUS      RESTARTS   AGE
syndesis-operator-1-build   0/1       Completed   0          4m
⏚ [: … operator] master(+11/-1)+ ± oc get dc
No resources found.
```
Alternatively, replacing 'build.sh' with 'syndesis', I do get the full local install. However, db comes up without a hitch.

@dhirajsb
- are you able to repeat?
- can you verify the commit id of the HEAD of your master branch?
- thx.

**Comment by KurtStam** [comment] 2019-10-23 13:41
Same error using the default community install:

bash <(curl -sL https://syndes.is/start)

**Comment by KurtStam** [comment] 2019-10-23 21:24
@lgarciaaco Why are you removing the p0 label?

**Comment by lgarciaaco** [comment] 2019-10-24 13:02
ok, the issue is related with the fact that the operator binaries are not released any longer. The last release was 10 days ago, and that build doesn't include the fixes for what @dhirajsb is facing, not to mention that it is building only 1.8 branch and not master.

To bypass this until I commit a solution, you can build the operator binary yourself, and use the binary for your distribution directly. Take the binary and copy to it to the location of $OPERATOR_BINARY.

https://github.com/syndesisio/syndesis/blob/6fed5ed2c5f07f22bfecb1b93175d04b2cb33bd3/tools/bin/commands/util/operator_funcs#L4

**Comment by zregvart** [comment] 2019-11-14 09:55
This is still an issue, as reported on Gitter and reproduced locally. Relevant bits from the operator log:

```
{"level":"info","ts":1573724756.5976403,"logger":"action","msg":"Failed to create or replace resource","type":"install","kind":"Role","name":"syndesis-editor","namespace":"myproject"}
{"level":"error","ts":1573724756.5976658,"logger":"controller","msg":"Error reconciling","action":"*action.installAction","phase":"Installing","error":"roles.rbac.authorization.k8s.io \"syndesis-editor\" is forbidden: attempt to grant extra privileges: [{[get] [] [deploymentconfigs/finalizers] [] []} {[list] [] [deploymentconfigs/finalizers] [] []} {[create] [] [deploymentconfigs/finalizers] [] []} {[update] [] [deploymentconfigs/finalizers] [] []} {[delete] [] [deploymentconfigs/finalizers] [] []} {[deletecollection] [] [deploymentconfigs/finalizers] [] []} {[watch] [] [deploymentconfigs/finalizers] [] []} {[patch] [] [deploymentconfigs/finalizers] [] []} {[get] [apps.openshift.io] [deploymentconfigs/finalizers] [] []} {[list] [apps.openshift.io] [deploymentconfigs/finalizers] [] []} {[create] [apps.openshift.io] [deploymentconfigs/finalizers] [] []} {[update] [apps.openshift.io] [deploymentconfigs/finalizers] [] []} {[delete] [apps.openshift.io] [deploymentconfigs/finalizers] [] []} {[deletecollection] [apps.openshift.io] [deploymentconfigs/finalizers] [] []} {[watch] [apps.openshift.io] [deploymentconfigs/finalizers] [] []} {[patch] [apps.openshift.io] [deploymentconfigs/finalizers] [] []}] user=&{system:serviceaccount:myproject:syndesis-operator 7b0849b0-06c3-11ea-8335-525400685f38 [system:serviceaccounts system:serviceaccounts:myproject system:authenticated] map[]} ownerrules=[{[get] [ user.openshift.io] [users] [~] []} {[list] [ project.openshift.io] [projectrequests] [] []} {[get list] [ authorization.openshift.io] [clusterroles] [] []} {[get list watch] [rbac.authorization.k8s.io] [clusterroles] [] []} {[get list] [storage.k8s.io] [storageclasses] [] []} {[list watch] [ project.openshift.io] [projects] [] []} {[create] [ authorization.openshift.io] [selfsubjectrulesreviews] [] []} {[create] [authorization.k8s.io] [selfsubjectaccessreviews] [] []} {[get] [] [] [] [/healthz /healthz/*]} {[get] [] [] [] [/version /version/* /api /api/* /apis /apis/* /oapi /oapi/* /openapi/v2 /swaggerapi /swaggerapi/* /swagger.json /swagger-2.0.0.pb-v1 /osapi /osapi/ /.well-known /.well-known/* /]} {[create] [ authorization.openshift.io] [selfsubjectrulesreviews] [] []} {[create] [authorization.k8s.io] [selfsubjectaccessreviews] [] []} {[create] [authorization.k8s.io] [selfsubjectaccessreviews selfsubjectrulesreviews] [] []} {[create] [ build.openshift.io] [builds/docker builds/optimizeddocker] [] []} {[create] [ build.openshift.io] [builds/jenkinspipeline] [] []} {[create] [ build.openshift.io] [builds/source] [] []} {[get] [] [] [] [/api /api/* /apis /apis/* /healthz /openapi /openapi/* /swagger-2.0.0.pb-v1 /swagger.json /swaggerapi /swaggerapi/* /version /version/]} {[delete] [ oauth.openshift.io] [oauthaccesstokens oauthauthorizetokens] [] []} {[get] [] [] [] [/version /version/* /api /api/* /apis /apis/* /oapi /oapi/* /openapi/v2 /swaggerapi /swaggerapi/* /swagger.json /swagger-2.0.0.pb-v1 /osapi /osapi/ /.well-known /.well-known/* /]} {[impersonate] [authentication.k8s.io] [userextras/scopes.authorization.openshift.io] [] []} {[create get] [ build.openshift.io] [buildconfigs/webhooks] [] []} {[impersonate] [] [serviceaccounts] [] []} {[get] [] [namespaces] [] []} {[get] [ project.openshift.io] [projects] [] []} {[impersonate] [] [serviceaccounts] [] []} {[get list create update delete deletecollection watch] [] [pods pods/exec services endpoints persistentvolumeclaims configmaps secrets serviceaccounts] [] []} {[get list create update delete deletecollection watch patch] [] [replicationcontrollers replicationcontrollers/scale] [] []} {[get list create update delete deletecollection watch patch] [apps] [daemonsets deployments deployments/scale replicasets replicasets/scale statefulsets statefulsets/scale] [] []} {[get list create update delete deletecollection watch patch] [extensions] [daemonsets deployments deployments/scale ingresses networkpolicies replicasets replicasets/scale replicationcontrollers/scale] [] []} {[get list watch] [] [bindings events limitranges namespaces/status pods/log pods/status replicationcontrollers/status resourcequotas resourcequotas/status] [] []} {[get list create update delete deletecollection watch patch] [ build.openshift.io] [buildconfigs buildconfigs/webhooks builds] [] []} {[create] [ build.openshift.io] [buildconfigs/instantiate buildconfigs/instantiatebinary builds/clone] [] []} {[update] [ build.openshift.io] [builds/details] [] []} {[get list watch] [ build.openshift.io] [builds/log] [] []} {[get list create update delete deletecollection watch patch] [ apps.openshift.io] [deploymentconfigs deploymentconfigs/scale] [] []} {[create] [ apps.openshift.io] [deploymentconfigrollbacks deploymentconfigs/instantiate deploymentconfigs/rollback] [] []} {[get list watch] [ apps.openshift.io] [deploymentconfigs/log deploymentconfigs/status] [] []} {[get list create update delete deletecollection watch patch] [ image.openshift.io] [imagestreams imagestreamimages imagestreammappings imagestreams/secrets imagestreamtags] [] []} {[create] [ image.openshift.io] [imagestreamimports] [] []} {[get list watch] [ image.openshift.io] [imagestreams/status] [] []} {[get list create update delete deletecollection watch patch] [route.openshift.io] [routes] [] []} {[get list create update delete deletecollection watch patch] [ template.openshift.io] [processedtemplates templateconfigs templateinstances templates] [] []} {[get list create update delete deletecollection watch patch] [ build.openshift.io] [buildlogs] [] []} {[get list create update delete deletecollection watch] [syndesis.io] [* */finalizers] [] []} {[get list create update delete deletecollection watch] [] [pods services endpoints persistentvolumeclaims configmaps secrets serviceaccounts] [] []} {[get] [] [pods/log] [] []} {[get list create update delete deletecollection watch] [] [replicationcontrollers replicationcontrollers/scale replicationcontrollers/status] [] []} {[get list create update delete deletecollection watch] [ build.openshift.io] [builds buildconfigs builds/details buildconfigs/webhooks buildconfigs/instantiatebinary builds/log] [] []} {[get list create update delete deletecollection watch patch] [ apps.openshift.io] [deploymentconfigs deploymentconfigs/scale] [] []} {[create] [ apps.openshift.io] [deploymentconfigrollbacks deploymentconfigs/instantiate deploymentconfigs/rollback] [] []} {[get list watch] [ apps.openshift.io] [deploymentconfigs/log deploymentconfigs/status] [] []} {[get list create update delete deletecollection watch patch] [ image.openshift.io] [imagestreams imagestreamimages imagestreammappings imagestreams/secrets imagestreamtags] [] []} {[get list watch] [ image.openshift.io] [imagestreams/status imagestreamimports] [] []} {[get list] [] [events] [] []} {[get list create update delete deletecollection watch] [rbac.authorization.k8s.io] [roles rolebindings] [] []} {[get list create update delete deletecollection watch patch] [ template.openshift.io] [processedtemplates templateconfigs templateinstances templates] [] []} {[get list create update delete deletecollection watch] [authorization.openshift.io] [rolebindings] [] []} {[get list create update delete deletecollection watch patch] [route.openshift.io] [routes routes/custom-host] [] []} {[get list create update delete deletecollection watch] [camel.apache.org] [*] [] []} {[get list create update delete deletecollection watch] [monitoring.coreos.com] [alertmanagers prometheuses servicemonitors prometheusrules] [] []} {[get list create update delete deletecollection watch] [integreatly.org] [grafanadashboards] [] []} {[get list watch] [serving.knative.dev] [services] [] []} {[get list watch] [eventing.knative.dev] [channels] [] []} {[get] [ image.openshift.io] [imagestreams/layers] [] []}] ruleResolutionErrors=[]","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/circleci/project/install/operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/syndesisio/syndesis/install/operator/pkg/controller/syndesis.(*ReconcileSyndesis).Reconcile\n\t/home/circleci/project/install/operator/pkg/controller/syndesis/syndesis_controller.go:120\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/circleci/project/install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/circleci/project/install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/circleci/project/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/circleci/project/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/circleci/project/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

Seems that the `syndesis-editor` role was not created and having failed there the operator could not proceed.

**Comment by KurtStam** [comment] 2019-11-27 19:10
@lgarciaaco Can you take a look?

**Comment by heiko-braun** [comment] 2019-11-28 08:05
@phantomjinx Looks like `deploymentconfigs/finalizers` related

**Comment by lgarciaaco** [comment] 2019-12-03 16:27
@zregvart I think this should be gone by now. Can you add some steps to reproduce?

**Comment by zregvart** [comment] 2019-12-03 16:37
@lgarciaaco let me test on my end and I'll report my findings with any steps needed to reproduce the issue.

**Comment by KurtStam** [comment] 2019-12-09 09:30
After fixing https://github.com/syndesisio/syndesis/issues/7355 I was able to verify that this is fixed now

**Closed by KurtStam** 2019-12-09 09:30 UTC
Labels: prio/p0
