### ISSUE TITLE
API Connector - Response processing error

### ISSUE THREAD

**Issue by pszuster** [syndesisio/syndesis#3367] opened 2018-08-13 12:58 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When using an API Connector in the middle of an integration, its reponse can't be used in a DataMapper, as it returns an error:
`io.atlasmap.api.AtlasException: Errors: [Source document '-LJUy1ewwDtasbGPSvu0' doesn't exist: docId='-LJUy1ewwDtasbGPSvu0', path='/@type'], 
	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:213) ~[camel-atlasmap-1.34.4.fuse-000001-redhat-1.jar!/:na]
`

The workaround I found is: 
1. Add a script extension step with this code: 
`exchange.in.body = exchange.in.getBody(java.lang.String.class);
exchange.out = exchange.in;`
2. Add a DataShape extension connector (https://github.com/pszuster/Fuse7TD/tree/master/syndesis-extensions-master/syndesis-connector-datashape) which is basically a mock connector that allows me to set a data shape
3. Then I can add a DataMapper and it works as expected.

## Expected behavior

I would expect to be able to work with the API Connector's reponse in a DataMapper.

## Tasks involved / Steps to Reproduce

1. Create API Connector
2. Create API Connector connection
3. Create Integration
4. Use API Connector in the middle of the integration
5. Add DataMapper after the API Connector
6. Publish the integration

[prueba-export-v2.zip](https://github.com/syndesisio/syndesis/files/2282989/prueba-export-v2.zip)

**Comment by zregvart** [comment] 2018-08-14 10:13
In the exported integration the mapping step is configured with:

```json
{
  "AtlasMapping": {
    "jsonType": "io.atlasmap.v2.AtlasMapping",
    "dataSource": [
      {
        "jsonType": "io.atlasmap.json.v2.JsonDataSource",
        "id": "-LJUKl9oUMZ5698Wpqmd",
        "uri": "atlas:json:-LJUKl9oUMZ5698Wpqmd",
        "dataSourceType": "SOURCE"
      },
      {
        "jsonType": "io.atlasmap.json.v2.JsonDataSource",
        "id": "-LJUy1ewwDtasbGPSvu0",
        "uri": "atlas:json:-LJUy1ewwDtasbGPSvu0",
        "dataSourceType": "SOURCE"
      },
      {
        "jsonType": "io.atlasmap.json.v2.JsonDataSource",
        "id": "-LJVHYPLfsx5Yopqa6PB",
        "uri": "atlas:json:-LJVHYPLfsx5Yopqa6PB",
        "dataSourceType": "TARGET",
        "template": null
      }
    ],
    "mappings": {
      "mapping": [
        {
          "jsonType": "io.atlasmap.v2.Mapping",
          "mappingType": "MAP",
          "id": "mapping.524738",
          "inputField": [
            {
              "jsonType": "io.atlasmap.json.v2.JsonField",
              "name": "@type",
              "path": "/@type",
              "fieldType": "STRING",
              "docId": "-LJUy1ewwDtasbGPSvu0",
              "userCreated": false
            }
          ],
          "outputField": [
            {
              "jsonType": "io.atlasmap.json.v2.JsonField",
              "name": "tipo",
              "path": "/tipo",
              "fieldType": "STRING",
              "docId": "-LJVHYPLfsx5Yopqa6PB",
              "userCreated": false
            }
          ]
        }
      ]
    },
    "name": "UI.79227",
    "lookupTables": {
      "lookupTable": []
    },
    "constants": {
      "constant": []
    },
    "properties": {
      "property": []
    }
  }
}
```

Notice that there are two source documents `LJUKl9oUMZ5698Wpqmd` and `-LJUy1ewwDtasbGPSvu0`, the latter is reported as non existent.

I've tried to reproduce this with the public instance of OpenCRX at demo.opencrx.org, by:

 1. downloading OpenAPI specification from http://demo.opencrx.org/opencrx-rest-CRX/org.opencrx.kernel.contract1/provider/CRX/segment/Standard/:api
 2. converting the specification into YAML, and editing it to add:
```yaml
securityDefinitions:
  auth:
    type: basic
```
 3. creating a custom API connector with the edited OpenAPI specification
 4. creating a connection for the the created connector with host: demo.opencrx.org, username: guest, password: guest
 5. deployed AMQ broker and created connection for it
 6. creating a from: timer (`10min`), to:AMQ (JSON instance data shape: `{"type":"test"}`); with: OpenCRX API (operation `GET /lead`, id: `getLeadS`) and a mapper step between OpenCRX API and AMQ mapping `/@type` to `/type`

And this is the generated mapping:
```json
{
  "AtlasMapping": {
    "jsonType": "io.atlasmap.v2.AtlasMapping",
    "dataSource": [
      {
        "jsonType": "io.atlasmap.json.v2.JsonDataSource",
        "id": "-LJrktH3AvFiWcsOT0F4",
        "uri": "atlas:json:-LJrktH3AvFiWcsOT0F4",
        "dataSourceType": "SOURCE"
      },
      {
        "jsonType": "io.atlasmap.json.v2.JsonDataSource",
        "id": "-LJrkezfAvFiWcsOT0F4",
        "uri": "atlas:json:-LJrkezfAvFiWcsOT0F4",
        "dataSourceType": "TARGET",
        "template": null
      }
    ],
    "mappings": {
      "mapping": [
        {
          "jsonType": "io.atlasmap.v2.Mapping",
          "mappingType": "MAP",
          "id": "mapping.50560",
          "inputField": [
            {
              "jsonType": "io.atlasmap.json.v2.JsonField",
              "name": "@type",
              "path": "/@type",
              "fieldType": "STRING",
              "docId": "-LJrktH3AvFiWcsOT0F4",
              "userCreated": false
            }
          ],
          "outputField": [
            {
              "jsonType": "io.atlasmap.json.v2.JsonField",
              "name": "tipo",
              "path": "/tipo",
              "fieldType": "STRING",
              "docId": "-LJrkezfAvFiWcsOT0F4",
              "userCreated": false
            }
          ]
        }
      ]
    },
    "name": "UI.751242",
    "lookupTables": {
      "lookupTable": []
    },
    "constants": {
      "constant": []
    },
    "properties": {
      "property": []
    }
  }
}
```

Notice there is a single source document in this one.

@igarashitm do you think this second source document in the mapping from the exported integration could have happened in the Atlasmap editor?

@pszuster if you remove the mapping step and create it again, do you experience the same issue?

**Comment by igarashitm** [comment] 2018-08-14 13:29
Data Mapper step only collects outputDataShape of preceding steps here
https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts#L199-L216

So it means that there actually were two data shape aware steps ahead of Data Mapper at that time, at least in the UI model object. But anyway, if it doesn't reproduce there's not much we can do.

@pszuster is this `Steps to Reprudce` working for you even by starting from creating new integration, rather than modifying existing? There must be something missing required to reproduce.

**Comment by zregvart** [comment] 2018-08-14 14:16
In the exported model.json I can see that the data shape of the timer is set to:

```json
"outputDataShape": {
  "description": "A user specified data type",
  "kind": "json-instance",
  "metadata": {
    "userDefined": "true"
  },
  "name": "None",
  "specification": "{}"
}
```

I wonder if this is an issue with the older version when we had timer step's data shape as `any` (#3034).

**Comment by pszuster** [comment] 2018-08-14 14:58
I created another integration from scratch, avoiding the use of any extension. This one uses AMQ -> DataMapper -> API Connector -> DataMapper -> AMQ. In this one I'm getting  a different error (which used to appear some time ago when I started developing this)
[prueba1-export.zip](https://github.com/syndesisio/syndesis/files/2287445/prueba1-export.zip)



Message History
--
  | ---------------------------------------------------------------------------------------------------------------------------------------
  | RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
  | [-LJsqXv_3XtQC_wjG6] [-LJsqXv_3XtQC_wjG6] [sjms-sjms-1://queue:cola1                                                     ] [        27]
  | [-LJsqXv_3XtQC_wjG6] [setHeader1        ] [setHeader[Syndesis.STEP_ID]                                                   ] [         1]
  | [-LJsqXv_3XtQC_wjG6] [process1          ] [Processor@0x21d488e8                                                          ] [         0]
  | [-LJsqXv_3XtQC_wjG6] [step:i-LJst4j3EmGT] [pipeline                                                                      ] [         4]
  | [-LJsqXv_3XtQC_wjG6] [setHeader2        ] [setHeader[Syndesis.STEP_ID]                                                   ] [         0]
  | [-LJsqXv_3XtQC_wjG6] [to1               ] [atlas:mapping-step-2.json?sourceMapName=Syndesis.CAPTURED_OUT_MESSAGES_MAP    ] [         2]
  | [-LJsqXv_3XtQC_wjG6] [process2          ] [Processor@0x21d488e8                                                          ] [         1]
  | [-LJsqXv_3XtQC_wjG6] [step:-LJsqhpj3XtQC] [pipeline                                                                      ] [        17]
  | [-LJsqXv_3XtQC_wjG6] [setHeader3        ] [setHeader[Syndesis.STEP_ID]                                                   ] [         0]
  | [-LJsqXv_3XtQC_wjG6] [to2               ] [swagger-operation-3?operationId=manageContainer                               ] [        17]
  | [-LJsqXv_3XtQC_wjG6] [process3          ] [Processor@0x21d488e8                                                          ] [         0]
  | [-LJsqXv_3XtQC_wjG6] [step:i-LJst4jOEmGT] [pipeline                                                                      ] [         0]
  | [-LJsqXv_3XtQC_wjG6] [setHeader4        ] [setHeader[Syndesis.STEP_ID]                                                   ] [         0]
  | [-LJsqXv_3XtQC_wjG6] [to3               ] [atlas:mapping-step-4.json?sourceMapName=Syndesis.CAPTURED_OUT_MESSAGES_MAP    ] [         4]
  |  
  | Stacktrace
  | ---------------------------------------------------------------------------------------------------------------------------------------
  |  
  | java.lang.NullPointerException: null
  | at io.atlasmap.json.module.JsonModule.getCollectionSize(JsonModule.java:218) ~[atlas-json-module-1.34.4.fuse-000001-redhat-1.jar!/:1.34.4.fuse-000001-redhat-1]
  | at io.atlasmap.core.DefaultAtlasContext.extractCollectionMappings(DefaultAtlasContext.java:333) ~[atlas-core-1.34.4.fuse-000001-redhat-1.jar!/:1.34.4.fuse-000001-redhat-1]
  | at io.atlasmap.core.DefaultAtlasContext.process(DefaultAtlasContext.java:252) ~[atlas-core-1.34.4.fuse-000001-redhat-1.jar!/:1.34.4.fuse-000001-redhat-1]
  | at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:194) ~[camel-atlasmap-1.34.4.fuse-000001-redhat-1.jar!/:na]
  | at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71) ~[camel-core-2.21.0.fuse-000077-redhat-1.jar!/:2.21.0.fuse-000077-redhat-1]

**Comment by igarashitm** [comment] 2018-08-14 15:01
Hmm https://github.com/syndesisio/syndesis/issues/3367#issuecomment-412887372 smells like @pszuster defined an output DataShape for the timer step via Describe Data Type page. If so please don't do that.

**Comment by igarashitm** [comment] 2018-08-14 15:04
https://github.com/syndesisio/syndesis/issues/3367#issuecomment-412902090 is a completely different issue, please don't mix up.

**Comment by pszuster** [comment] 2018-08-14 15:14
> Hmm #3367 (comment) smells like @pszuster defined an output DataShape for the timer step via Describe Data Type page. If so please don't do that.

Why is that?

**Comment by igarashitm** [comment] 2018-08-14 15:18
See #3034, Timer doesn't provide any output data, so its outputDataShape should be `none` while it was `any` in old version. You no longer can do it in newer version.

**Comment by igarashitm** [comment] 2018-08-14 15:25
So was that the root cause? can we close this?

**Comment by pszuster** [comment] 2018-08-14 15:31
> See #3034, Timer doesn't provide any output data, so its outputDataShape should be none while it was any in old version. You no longer can do it in newer version.


It seems current version still uses `any` as outputDataShape:  https://github.com/syndesisio/syndesis-extensions/blob/master/syndesis-connector-timer/src/main/resources/META-INF/syndesis/syndesis-extension-definition.json#L16

**Comment by igarashitm** [comment] 2018-08-14 15:37
https://github.com/syndesisio/syndesis/pull/3154/files

I have no idea about that extension

**Comment by pszuster** [comment] 2018-08-14 16:08
> https://github.com/syndesisio/syndesis/pull/3154/files
> 
> I have no idea about that extension

That one doesn't exist in latest GA version (1.3.12.fuse-000001-redhat-2)

**Comment by igarashitm** [comment] 2018-08-14 16:19
Anyway if it's an extension you can do whatever you want as opposed to built-in connectors right?

**Comment by pszuster** [comment] 2018-08-14 16:38
Ok let's close this, and I'll open a new one with my current reproduceable error..

**Comment by igarashitm** [comment] 2018-08-14 22:16
@pszuster please clean up your bug report - at first you had nothing described about Timer connector in your report and the root cause was in the Timer connector where the bug was already fixed in upstream. And you reopened that Timer connector bug report with saying you don't use Timer. It's hard to even guess who can help.

**Comment by zregvart** [comment] 2018-08-15 08:02
@pszuster can I ask you to create a separate issues for the ones you mention in https://github.com/syndesisio/syndesis/issues/3367#issuecomment-412902090 and https://github.com/syndesisio/syndesis/issues/3367#issuecomment-412985799. I believe the issue you encountered when raising this issue is related to #3034 and it has been resolved in a newer release of Syndesis.

**Closed by zregvart** 2018-08-15 08:02 UTC
Labels: notif/triage
