### ISSUE TITLE
Validating Kafka components always kills the Meta pod

### ISSUE THREAD

**Issue by weimeilin79** [syndesisio/syndesis#4234] opened 2018-12-20 20:33 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Trying to configure kafka component to AMQ Streams in the same cluster, but always throws OutOfMemoryError. 

`2018-12-20 20:27:17.698  INFO 1 --- [  XNIO-3 task-1] o.a.k.clients.admin.AdminClientConfig    : AdminClientConfig values:
--
  | bootstrap.servers = [my-cluster-kafka-bootstrap.streams.svc:9091]
  | client.id =
  | connections.max.idle.ms = 10000
  | metadata.max.age.ms = 300000
  | metric.reporters = []
  | metrics.num.samples = 2
  | metrics.recording.level = INFO
  | metrics.sample.window.ms = 30000
  | receive.buffer.bytes = 65536
  | reconnect.backoff.max.ms = 1000
  | reconnect.backoff.ms = 50
  | request.timeout.ms = 5000
  | retries = 5
  | retry.backoff.ms = 100
  | sasl.client.callback.handler.class = null
  | sasl.jaas.config = null
  | sasl.kerberos.kinit.cmd = /usr/bin/kinit
  | sasl.kerberos.min.time.before.relogin = 60000
  | sasl.kerberos.service.name = null
  | sasl.kerberos.ticket.renew.jitter = 0.05
  | sasl.kerberos.ticket.renew.window.factor = 0.8
  | sasl.login.callback.handler.class = null
  | sasl.login.class = null
  | sasl.login.refresh.buffer.seconds = 300
  | sasl.login.refresh.min.period.seconds = 60
  | sasl.login.refresh.window.factor = 0.8
  | sasl.login.refresh.window.jitter = 0.05
  | sasl.mechanism = GSSAPI
  | security.protocol = PLAINTEXT
  | send.buffer.bytes = 131072
  | ssl.cipher.suites = null
  | ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
  | ssl.endpoint.identification.algorithm = https
  | ssl.key.password = null
  | ssl.keymanager.algorithm = SunX509
  | ssl.keystore.location = null
  | ssl.keystore.password = null
  | ssl.keystore.type = JKS
  | ssl.protocol = TLS
  | ssl.provider = null
  | ssl.secure.random.implementation = null
  | ssl.trustmanager.algorithm = PKIX
  | ssl.truststore.location = null
  | ssl.truststore.password = null
  | ssl.truststore.type = JKS
  |  
  | 2018-12-20 20:27:17.970  INFO 1 --- [  XNIO-3 task-1] o.a.kafka.common.utils.AppInfoParser     : Kafka version : 2.0.0
  | 2018-12-20 20:27:17.970  INFO 1 --- [  XNIO-3 task-1] o.a.kafka.common.utils.AppInfoParser     : Kafka commitId : 3402a8361b734732

2018-12-20 20:29:51.370  INFO 1 --- [  XNIO-3 task-1] o.a.kafka.common.utils.AppInfoParser     : Kafka version : 2.0.0
--
  | 2018-12-20 20:29:51.370  INFO 1 --- [  XNIO-3 task-1] o.a.kafka.common.utils.AppInfoParser     : Kafka commitId : 3402a8361b734732
  | Terminating due to java.lang.OutOfMemoryError: Java heap space`

**Comment by heiko-braun** [comment] 2018-12-21 14:17
@weimeilin79 Can you attach an example integration (exported from Syndesis)?

**Comment by weimeilin79** [comment] 2018-12-21 14:19
@heiko-braun  I can't even get that far, I was just trying to configure the Connection.. It META keeps dying when I hit validate

**Comment by dhirajsb** [comment] 2019-02-28 14:06
@weimeilin79 I'll take a shot at this.

**Comment by dhirajsb** [comment] 2019-02-28 14:32
@weimeilin79 this looks like a related issue https://issues.apache.org/jira/browse/KAFKA-4090
In general it seems Kafka is sensitive to an incorrect configuration that can cause OOM errors.

**Comment by KurtStam** [comment] 2019-06-04 19:06
@weimeilin79 I'm sorry it took this long for someone to work on this. I just tried it but I can't reproduce it. Here is what I did:

1. I followed step 1 through 5 of the Kafka documentation on https://kafka.apache.org/quickstart and Kafka is now running happily on my local machine.

1. Installed syndesis on minishift using `bash <(curl -sL https://syndes.is/start)` (see https://syndesis.io/quickstart/)

1. I then pointed the Kafka broken URI to point to it and hit 'validate' and I'm getting a nice green validation
<img width="987" alt="Screen Shot 2019-06-04 at 2 59 21 PM" src="https://user-images.githubusercontent.com/35576/58906477-f7819280-86d9-11e9-856c-57e287afb56a.png">

@weimeilin79 wdyt? Is this fixed now?

**Comment by KurtStam** [comment] 2019-06-06 12:43
Ah I was able to reproduce it by misconfiguring the connection info. This sure is a Kafka issue. I will try to see if there is a workaround to validate the connection info.

**Comment by KurtStam** [comment] 2019-06-14 16:25
1. As mentioned above KAFKA has a huge bug that blows the memory when an SSL connection is tested (typically port 9093). Even if we catch this exception our JVM is still in an inconsistent state. It's probably better as it is now where the meta pod blows up and restarts. This until [the issue](https://issues.apache.org/jira/browse/KAFKA-4090) in Kafka gets fixed.

2. To configure a client correctly to be able to handle SSL connection we need to enhance the UI so the user can provide certificates needed by client to set up the SSL connection. At the time the Kafka connector was created SSL was not considered (https://github.com/syndesisio/syndesis/issues/2765#issuecomment-397112859). 
So if we want to support SSL we should add a new story.

3. That said I'm working on a QuickStart that demonstrates how to use strimzi in a non SSL way. I will add link when this done.

**Comment by TovaCohen** [comment] 2019-06-14 16:51
The 7.3 user doc is here: 
https://access.redhat.com/documentation/en-us/red_hat_fuse/7.3/html/connecting_fuse_online_to_applications_and_services/connecting-to-kafka_connectors

Please take a look. We can note the restriction in the intro, or in section 11.1, which is about creating a Kafka connection. Which do you prefer? 
How's this for the note: 

You cannot create a connection to a Kafka broker that requires an SSL connection. This is caused by a Kafka limitation that is expected to be resolved in a future release.

**Comment by KurtStam** [comment] 2019-06-14 16:56
@TovaCohen thank you that note sounds great to me.

**Comment by TovaCohen** [comment] 2019-06-14 17:06
How's this:
You cannot create a connection to a Kafka broker that requires SSL. In this release, connections to Kafka do not support SSL.

**Comment by KurtStam** [comment] 2019-06-14 17:37
You should not create a connection to a Kafka broker that requires SSL. In this release, connections to Kafka do not support SSL.

**Comment by TovaCohen** [comment] 2019-06-14 19:23
It sounds like the reality is that I can create a connection to a Kafka broker that requires SSL but that connection won't work in my integration. If that's right, I'd like to write the note more in line with your original suggestion, Kurt. And also indicate that there is hope that this limitation will be removed, because users always ask about that.  Is this okay: 

In this release, connections to Kafka do not support SSL. It is expected that this will change in a future release.

**Comment by KurtStam** [comment] 2019-06-14 20:28
Yes that is right, you can specify the SSL url but you will miss setting a lot of additional config param and due to a bug in Kafka verifying it does not simply say 'sorry you missed something', but instead it blows up the entire pod in spectacular fashion :(. 

I like you suggested verbiage.

**Comment by TovaCohen** [comment] 2019-06-14 21:33
I'll use this Jira to add the note: https://issues.jboss.org/browse/FUSEDOC-3273

**Comment by KurtStam** [comment] 2019-06-18 14:52
Everyone on this thread should upvote  https://issues.apache.org/jira/browse/KAFKA-4090

**Closed** 2019-08-07 10:51 UTC
Labels: cat/bug, closed/verified, prio/p1
