### ISSUE TITLE
Metrics tab doesn't show correct data

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#5914] opened 2019-06-25 12:04 UTC
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Metrics tab doesn't show correct data.

- A number of Total Messages is still 0 however the activity log contains some items.
- Uptime still shows as "No Data Available".
- Last Processed date shows a date (with time) when I refresh the page, not when the last message was processed.

**Comment by paoloantinori** [comment] 2019-06-25 13:56
Can you provide more information, logs or reproducer?

We do not have any evidence of this problem:

![Screenshot from 2019-06-25 15-55-24](https://user-images.githubusercontent.com/1520602/60104475-d99bd080-9761-11e9-9e20-fcefe6a7fd51.png)

**Comment by mkralik3** [comment] 2019-06-25 15:40
In the Chrome browser on the tag 1.7.4 installed today. (commit id 93a93bd)

**Comment by paoloantinori** [comment] 2019-06-26 07:29
No logs?

**Comment by mkralik3** [comment] 2019-06-26 07:59
No errors are in the server-log, integration-log, ui-log and browser-log so I have not uploaded any logs.
On the metrics tab, the response from the endpoint
`.../metrics/integrations/i-LiHivnXWz8gI7Cl_3P1z` is `{"metricsProvider":"prometheus","messages":0,"errors":0}` which is not true.
I don't know from where the UI gets Last Processed and Uptime.

Step to reproduce:
- `syndesis minishift --install --project syndesis --tag 1.7.4 `
- Create integration timer-to-log (etc. with 1second timer) and publish it
- Go to the activity tab, there should be logs of activity
- Go to the metrics tab, the Total Messages is still zero, Last Processed are changing every time when the page is refreshed and Uptime is still `No Data Available`

**Comment by riccardo-forina** [comment] 2019-06-26 08:05
`/metrics/integrations/i-LiHivnXWz8gI7Cl_3P1z` is the right API to check, but on staging for a simple running integration it's returning proper values:

```json
{"metricsProvider":"prometheus","messages":29827,"errors":0,"start":1560446075377,"lastProcessed":1561536120233,"integrationDeploymentMetrics":[{"version":"2","messages":1,"errors":0,"start":1560343061665,"lastProcessed":1560343062966},{"version":"3","messages":2574,"errors":0,"start":1560343083873,"lastProcessed":1560446005539},{"version":"4","messages":27252,"errors":0,"start":1560446075377,"lastProcessed":1561536120233}]}
```

The last processed date shows the current timestamp as a fallback in case of no values available. Maybe this has not been the greatest choice ever, but that's the reason why you get an updated date at each refresh.

Ultimately, the problem is with the underlying prometheus instance.

**Comment by mkralik3** [comment] 2019-06-26 08:17
Maybe when the no values available for _Last processed_, it should show something like "No processed yet" or so one. In my POV, the users can be confused that they see some date in the Last processed value however they don't see any activity in the activity log.

**Comment by riccardo-forina** [comment] 2019-06-26 08:35
Actually scratch that, I read the code wrong. If there is no last processed date, it should be showing the 'No data available' string. Code [here](https://github.com/syndesisio/syndesis/blob/1.7.x/app/ui-react/syndesis/src/modules/integrations/pages/detail/MetricsPage.tsx#L100-L108). 

If you're seeing a date, it must be coming from the BE.

**Comment by heiko-braun** [comment] 2019-06-28 09:26
@KurtStam Can you help @riccardo-forina to investigate this?

**Comment by KurtStam** [comment] 2019-07-01 12:37
@heiko-braun yes taking a look

**Comment by claudio4j** [comment] 2019-07-01 14:39
I can confirm this happens with the latest 1.7.x branch. Currently investigating.

**Comment by zregvart** [comment] 2019-07-02 13:19
Could this be related to https://github.com/syndesisio/syndesis/issues/6028#issuecomment-507632034?

**Comment by heiko-braun** [comment] 2019-07-02 13:44
Good point. 

@mkralik3 can you verify the setup instructions are followed? (See https://github.com/syndesisio/syndesis/issues/6028#issuecomment-507632034)

**Comment by claudio4j** [comment] 2019-07-02 15:14
As https://github.com/syndesisio/syndesis/issues/6028#issuecomment-507632034 said, running 
`oc adm policy add-role-to-user edit -z syndesis-prometheus`  on syndesis master, the metrics tab correctly shows the metrics.

Also, without the above permission, the syndesis-prometheus pod continually shows
```
level=error ts=2019-07-02T15:05:01.036392552Z caller=main.go:221 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:296: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:syndesis:syndesis-prometheus\" cannot list pods in the namespace \"syndesis\": no RBAC policy matched"
```

I will test on 1.7.x branch

![metrics_works](https://user-images.githubusercontent.com/836543/60524189-7c080680-9cc2-11e9-92ec-b43889a6251a.png)

**Comment by claudio4j** [comment] 2019-07-02 15:15
> Could this be related to [#6028 (comment)](https://github.com/syndesisio/syndesis/issues/6028#issuecomment-507632034)?

Thanks for the tip @zregvart and @mmelko , it works on master, I will try on 1.7.x

**Comment by heiko-braun** [comment] 2019-07-02 15:25
@mkralik3 @tplevko It seems to be a setup issue as documented in https://github.com/syndesisio/syndesis/issues/5914#issuecomment-507721700. Can you please verify that you've used the correct instructions as per https://github.com/syndesisio/syndesis/issues/6028#issuecomment-507632034? If that's the case I think we can resolve this.

**Comment by mkralik3** [comment] 2019-07-03 08:46
Yes, it works. Is this a workaround or the process of how it should work?
Also, I have installed syndesis via minishift command `syndesis minishift --install --tag 1.7.8 --project syndesis`. Shouldn't be run the command `oc adm policy add-role-to-user edit -z syndesis-prometheus` during `syndesis minishift --install...`?

**Comment by heiko-braun** [comment] 2019-07-03 09:39
@mkralik3 I guess it means that we can close this one, and track https://github.com/syndesisio/syndesis/issues/6028 instead, which deals with the permissions

**Comment by heiko-braun** [comment] 2019-07-03 09:40
> Shouldn't be run the command oc adm policy add-role-to-user edit -z syndesis-prometheus during syndesis minishift --install...?

Somehting like that yes. @nicolaferraro is looking into it already

**Comment by heiko-braun** [comment] 2019-07-03 09:47
@mkralik3 If you don't I close this in favor of #6028

**Comment by heiko-braun** [comment] 2019-07-03 09:48
Or better, we leave it open unil #6028 is fixed and than verify again

**Comment by mkralik3** [comment] 2019-07-03 10:50
> @mkralik3 I guess it means that we can close this one, and track #6028 instead, which deals with the permissions

I was asking because when it would be needed to run that command during the process of installation, it should be documented. But when it is the only workaround for 6028 for now and it will be fixed, it doesn't matter to document it. (Because it is p0, otherwise the workaround should be in errata or somewhere)

> Or better, we leave it open unil #6028 is fixed and than verify again

When we know that this issue is caused by 6028 and it is closely similar, we can theoretically close this one. However, in my POV, I would leave this open, and I will verify it again after the 6028 will be fixed. Just for sure that the fix will influences this case too.

**Comment by heiko-braun** [comment] 2019-07-03 11:38
Based on your defintion in https://github.com/syndesisio/syndesis/issues/5914#issuecomment-508043490, manually seeting the permissions is only a temporary workaround.

**Comment by nicolaferraro** [comment] 2019-07-05 10:15
This is not related to #6028 . The `syndesis:viewers` role has been removed and now the prometheus service account has no permissions.

I'm working to fix it.

**Closed** 2019-07-07 07:35 UTC
Labels: cat/bug, prio/p0, source/qe

**Comment by mkralik3** [comment] 2019-07-10 12:02
The metrics tab works on 1.7.9, However, still, when no messages are processed, it shows the actual date.  In my POV, it can be confusing for the users(as I mentioned https://github.com/syndesisio/syndesis/issues/5914#issuecomment-505771807). I created a new issue for it https://github.com/syndesisio/syndesis/issues/6117
