### ISSUE TITLE
FTP download action, buttons order is wrong.

### ISSUE THREAD

**Issue by Stefan365** [syndesisio/syndesis#1724] opened 2018-02-28 13:51 UTC
Steps to reproduce:
1. Select Create Integration.
2. Select start connection FTP.
3. Select action "download"
    - fill 1. form ..."Done"
    - fill 2. form ... "Next"
...

In step 3. you will fill first form and via "Done" button you enter second form.
After filling out second form, you finish this step by clicking on "Next"
Order of these buttons should be opposite. i.e. Next -> Done

1. form:
![download1](https://user-images.githubusercontent.com/2714974/36790694-f6f421e8-1c95-11e8-9252-e8730a16a2d5.png)

2. form:
![download2](https://user-images.githubusercontent.com/2714974/36790885-81a10018-1c96-11e8-81e9-29c79ffff259.png)

**Comment by gashcrumb** [comment] 2018-02-28 18:37
Hmm, this should work as of this PR -> https://github.com/syndesisio/syndesis/pull/1702 and am trying to reproduce it today on master and it behaves like I would expect, for both the start and finish cases.  Any chance you were on an old build, or maybe clear your browser cache just to be on the safe side?

**Comment by dsimansk** [comment] 2018-03-05 19:57
@Stefan365 this issue seems to be fixed via #1702, closing now.

**Closed by dsimansk** 2018-03-05 19:57 UTC
Labels: cat/bug, group/ui, target/tp4
