### ISSUE TITLE
User isn't redirected after deleting integration from integration detail

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5578] opened 2019-06-04 10:23 UTC
See also **https://issues.jboss.org/browse/ENTESB-11421**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
After deleting an integration inside integration detail, the user is not redirected to the integration list and sees an error message.

![image](https://user-images.githubusercontent.com/46345469/58872080-89ca6c00-86c3-11e9-97af-2c1f7503db62.png)

**Comment by riccardo-forina** [comment] 2019-06-13 13:31
This should be fixed.

**Comment by elvisisking** [comment] 2019-06-17 14:55
User now **is** redirected but I notice a 404 in log like this:

`GET http://localhost:3000/api/v1/integrations/i-Lh_tJbjTz_0k3Nsteu1z 404 (Not Found)`

**Comment by claudio4j** [comment] 2019-07-25 15:30
This is fixed in master branch. The 404 is there only once, but there is no bug.
If there is no objection, this can be closed.

**Comment by KurtStam** [comment] 2019-07-25 15:38
@claudio4j maybe you can explain why the 404 is not a bug - stale data in the UI?

**Comment by claudio4j** [comment] 2019-07-25 16:03
The original report says the redirection to the integration list doesn't occur, this is fixed, from user POV, after deletion it correctly redirects to the integration list with no errors. The 404 response is only displayed once in the browser console network tab. I didn't investigate the UI code, but looks like the UI does this request to check if the integration is there with no harm to the user experience.

**Comment by zregvart** [comment] 2019-07-25 18:19
I think the fetch for the deleted integration from the UI might be triggered by the event sent from the server when we delete stuff. As the event only contains a `kind` and a `id` the UI can't discern the difference between the integration being deleted and integration being created/updated.

**Comment by riccardo-forina** [comment] 2019-07-25 19:36
What he said :)

**Comment by heiko-braun** [comment] 2019-09-07 11:18
Migrated to **https://issues.jboss.org/browse/ENTESB-11421**

**Closed by heiko-braun** 2019-09-07 11:18 UTC
Labels: cat/bug, closed/migrated, prio/p1, source/qe, zenhub/backlog
