### ISSUE TITLE
Expose Open API data for discovery through annotation

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis#3471] opened 2018-08-28 09:52 UTC
We should export the swagger/openapi specification in the integration metadata so that it can be added to the proper annotation as part of #3504. Other metadata (such as paths and protocols) should be already present.

**Comment by heiko-braun** [comment] 2018-09-10 11:54
Closing as duplicate of #3504. @nicolaferraro please reopen if you think it's a different issues

**Comment by nicolaferraro** [comment] 2018-09-10 12:39
Yes, stated as is it's a duplicate. I was leaving it because we currently don't publish the swagger doc in a way that can be read by 3scale. So I'm reopening it and changing the description.

**Comment by zregvart** [comment] 2018-10-02 12:43
Implemented via #3683

**Closed by zregvart** 2018-10-02 12:43 UTC
