### ISSUE TITLE
UI freeze when creating new integration with no connections created

### ISSUE THREAD

**Issue by jsafarik** [syndesisio/syndesis#4571] opened 2019-02-14 15:27 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

With fresh installation of Syndesis (not having any integrations and connections) when I click on Create Integration and the dialog appears, I am not able to get back to Home page or any other page (the UI freezes - when clicking on any link in menu or cancel button, it doesn't interact). The only way to open any link is to open it in new tab (I am using Chrome)

## Tasks involved / Steps to Reproduce

1. Have no Connections
2. Click on Create Integration
3. Try to cancel it or to click on anything in the menu

**Comment by heiko-braun** [comment] 2019-02-14 16:37
@syndesisio/all Can anyone confirm this behaviour?

**Comment by heiko-braun** [comment] 2019-02-14 16:38
@jsafarik What browser/os are you using?

**Comment by tplevko** [comment] 2019-02-14 16:41
@heiko-braun we discussed in QE and this behavior was caused by this issue: https://github.com/syndesisio/syndesis/issues/4523
Closing this as duplicate of https://github.com/syndesisio/syndesis/issues/4523

**Closed by tplevko** 2019-02-14 16:41 UTC
Labels: cat/bug, notif/triage
