### ISSUE TITLE
After importing integration - Unable to decrypt key error appears

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#2603] opened 2018-05-12 13:14 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Unable to decrypt key error appears attempting to publish an integration that was reimported.
All this even after changing the password in the FTP connection and passing validation test.

## Request and Response Data
Error in log file: https://gist.github.com/honghuac/d7bd4d01a0e7562ad4a0bfcfddd9f7b8

## Tasks involved / Steps to Reproduce

1. Export integration containing FTP connection
2. Import integration to different Fuse Ignite instance
3. Change FTP connection password
4. Publish integration

**Comment by paoloantinori** [comment] 2018-07-04 10:11
Still belongs to the group of errors related to encryption

**Comment by amysueg** [comment] 2018-07-09 13:48
This issue includes the group/uxd label -- is there UX work associated with this bug and if so, can someone describe the UI impact and what needs design? From @heiko-braun's comment in #2602 it sounds like we need to provide information in the form of a message in the UI. Is that correct?
 @TovaCohen fyi.

**Comment by paoloantinori** [comment] 2018-07-09 14:19
hi @amysueg I can see UX involvement here, because this story might end up that we cannot fix this issue entirely and we have to rely on finding the best way to communicate the user a human intervention is required.

But we are still looking into this.

**Comment by tplevko** [comment] 2018-07-12 18:00
@paoloantinori I think this issue is actually a duplicate issue with: https://github.com/syndesisio/syndesis/issues/2585
There is a workarround for this, as discussed in https://github.com/syndesisio/syndesis/issues/2585. It's also covered in documentation. It's however really not ideal and it could be investigated by UX, as you mentioned.

**Comment by heiko-braun** [comment] 2018-07-27 06:59
Closing as duplicate of #2585

**Closed by heiko-braun** 2018-07-27 06:59 UTC
Labels: cat/bug, ext/docs, group/ui, group/uxd, prio/p1, qe/raised
