### ISSUE TITLE
Remove all non Syndesis message headers at the API provider start processor

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3865] opened 2018-10-16 15:10 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
We need to remove all non-Syndesis Camel message headers on reception of a HTTP request in the API provider-based integrations. If we don't they will be used by subsequent connectors/Camel components and they will cause issues.

Typical example is the `Host` header which will make the API client fail the request due to virtual host mismatch at the API service.

**Comment by asmigala** [comment] 2018-11-06 14:52
After discussing with @zregvart we agreed the issue is not fixed.

**Comment by heiko-braun** [comment] 2018-11-07 16:43
@zregvart are you going to take a stab at this?

**Comment by zregvart** [comment] 2018-11-07 20:48
@heiko-braun working on it

**Comment by zregvart** [comment] 2018-11-08 15:45
This also relates to #3729

**Comment by heiko-braun** [comment] 2018-11-08 16:45
Thanks @zregvart !

//cc @tplevko Now it's on your team I guess.

**Comment by zregvart** [comment] 2018-11-08 19:39
Let me add some notes to this: with this the existing functionality of #3729 remains in place and the previous PR for #3865 -- we'll remove all non Syndesis (i.e. ones beginning with `Syndesis.`) message headers after the API provider (Camel REST).

The change here also adds `HeaderFilterStrategy` that removes all `Syndesis.` headers going in our heading out of all HTTP interactions in integrations.

These are:
 - HTTP request/response headers when invoking WebHook or API provider
 - HTTP headers when issuing a request or reading a response to/from 3rd party HTTP services (HTTP, HTTPS, custom API client connectors)

To test this thoroughly I think these combinations we need to test:
 - Timer to HTTP/HTTPS/API Connector
 - WebHook/API Provider to log
 - WebHook/API Provider to HTTP/HTTPS/API Connector

The way this is implemented is that the `HeaderFilterStrategy` is defined only when HTTP/HTTPS/API Provider/Client or WebHook connectors are used and some of the duplicate combinations would make sure that this addition is performed in all of those cases (i.e. not just API Provider to API client).

**Comment by asmigala** [comment] 2018-11-16 15:22
Verified in current 1.5 branch (the latest fix is not in CR1).

Please note only the scenarios mentioned above were tested - there are most likely other places where message headers are not handled correctly, but that is out of scope of this issue and will be reported separately.

**Closed by asmigala** 2018-11-16 15:22 UTC
Labels: cat/bug, group/connector, prio/p0, progress/done
