### ISSUE TITLE
System start time looks wrong

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#7143] opened 2019-11-14 21:18 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
On staging, the duration seems right, but the start time doesn't look right:

![image](https://user-images.githubusercontent.com/351660/68896723-1741cb80-06fa-11ea-8037-49554465457a.png)

The number that drives this (the `start` field) looks truncated to me in the data coming back:

![image](https://user-images.githubusercontent.com/351660/68896817-49ebc400-06fa-11ea-8c06-2f31747c89e2.png)

Maybe this is a red herring 'cause it's staging, it'd be cool if someone could confirm this on another environment.

**Comment by gashcrumb** [comment] 2019-11-14 21:20
Oh, the raw response in the "Response" tab kinda looks odd to me too for the `start` and `lastProcessed` fields if it's truly coming across the wire like that:

![image](https://user-images.githubusercontent.com/351660/68896983-9505d700-06fa-11ea-8d0e-4f27a51db1be.png)

Y so many `0`s?

**Comment by zregvart** [comment] 2019-11-15 08:57
Most likely caused by #6959

**Comment by claudio4j** [comment] 2019-11-19 19:35
https://github.com/syndesisio/syndesis/pull/7142 fix this problem.

**Comment by KurtStam** [comment] 2019-11-27 19:06
@claudio4j so it's fixed on master and we can close this?

**Comment by claudio4j** [comment] 2019-11-27 20:17
> @claudio4j so it's fixed on master and we can close this?

Yeah, I closed the jira issue but forgot to close here. Thanks.

**Closed by claudio4j** 2019-11-27 20:17 UTC
Labels: cat/bug, group/server
