### ISSUE TITLE
Connection verification error shown as successful verification

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#1358] opened 2018-02-01 17:20 UTC
Currently our SQL verifier is broken (#1357), that means that `POST /api/v1/connectors/sql/verifier` endpoint returns:

```json
[
  {
    "status":"UNSUPPORTED",
    "scope":"PARAMETERS",
    "errors":[
      {
        "code":"internal-error",
        "description":"No action sql used for the verification known",
        "parameters":[],
        "attributes":{}
      }
    ]
  }
]
```

Which in turn is presented as:

![screenshot-2018-2-1 syndesis](https://user-images.githubusercontent.com/1306050/35692801-8d4efdea-077c-11e8-8d9a-dc34394689e3.png)

**Comment by KurtStam** [comment] 2018-02-02 01:16
@gashcrumb do you think you can take a look at this?

**Comment by gashcrumb** [comment] 2018-02-12 16:46
Is this an error?  'cause the validation component only cares about `status` set to `ERROR`

https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/connections/common/configuration/validation.component.ts#L45

I don't think we need to or should cater for more granularity than that...

**Comment by KurtStam** [comment] 2018-02-12 17:03
@gashcrumb yes this is the exception that can be sent back our code is broken. So it's not like 'hey you put in the the wrong password'.

**Comment by gashcrumb** [comment] 2018-02-12 17:21
So then can you just send back `ERROR` instead of `UNSUPPORTED`?  The UI doesn't care about the latter, I don't exactly understand why it should.

**Comment by KurtStam** [comment] 2018-02-12 17:29
@gashcrumb ah that's what you mean. Will check why it's doing that. Thx.

**Comment by KurtStam** [comment] 2018-02-13 16:28
going to close this as I can't reproduce the error anymore.

**Closed by KurtStam** 2018-02-13 16:28 UTC
Labels: cat/bug, group/ui
