### ISSUE TITLE
TP3 Extension scenario

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#1324] opened 2018-01-31 14:29 UTC
From out Mail Thread:
-------------

Some way to send a JMS message to kick off the integration.
We discussed a couple options here:
1) Extending the TODO app to send a JMS message by pushing a button.
2) Creating a standalone JMS script to send the message.

Option #2 gets pretty technical for a user (need Java and Maven most likely at a minimum).

An AMQ template to host a broker in the user's Fuse Online account.
I believe this is done and tested, but I'm not sure where it's located.  We discussed pre-loading the template in a user's account so that they can just click "Add to Project" to provision AMQ.  I guess another option would be to pre-install AMQ but have the replica count = 0 so that all a user has to do is bump the count to 1.

Anything else?  For reference, I have included the original scenario description below.

Here are some high-level ideas that we should do regardless of the specific scenario IMO:
Let's make it a single step in the extension to keep it simple.

* The step should do something with data shapes, either in or out, so that we can show it's type aware.
* The step should do something significant enough that it warrants creating a tech extension.
* The extension source code should be pushed to a separate example repo in Syndesis so that people can view/clone as they like.
* The extension binary should be hosted somewhere (GitHub, MRRC, etc.), so that people can deploy it directly.

I'm kinda thinking something like JMS -> Step -> Filter -> Data Map -> DB.  The scenario will be that a batch of inventory receipts (we can invent the format) is received via JMS.  The split step splits the inventory receipt into individual items received and then looks up contact info for each shipper (could be in-memory map with a few sample entries) and adds that to the message.  The output shape for the custom step defines the correct data type for an individual inventory receipt. The filter step only allows "DAMAGED" inventory to pass, followed by a data mapping step to map into our TODO format.  Finally the DB connector inserts the TODO to call the shipper with details on the damaged inventory.

--------

**Comment by dsimansk** [comment] 2018-02-01 13:05
@rhuss @lburgazzoli I've tested a small PoC that uses STOMP client in PHP to send message to broker. [1] It works quiet well to my surprise. Imho we could hardcode username/password for broker and deploy it with replica count set to 0, as suggested by Keith. For the users we would document how to scale the deployment and also how to create an example AMQ connection with our credentials. Then Camel route can be triggered from Todo app `1-click send button` with predefined message to be processed. Wdyt?

[1] https://github.com/syndesisio/todo-example/compare/master...dsimansk:stomp-poc

**Comment by dsimansk** [comment] 2018-02-02 11:34
@kcbabo I've started to implement the extension [1]. There seems to be a problem with initialization of datamapper as it ignores my provided shape #1375. Any feedback welcomed.

[1] https://github.com/dsimansk/syndesis-extension-tp3

**Comment by kcbabo** [comment] 2018-02-02 11:41
@lburgazzoli @igarashitm - any ideas?

@dsimansk - are you using TP3 build or master?  Wondering if the generated descriptor is compatible with TP3.

**Comment by dsimansk** [comment] 2018-02-02 11:45
@kcbabo TP3 build. Master is way ahead with extension definitions. It seems more like an UI issue ignoring the step and looking at the nearest connector. E.g. when I do JMS->DB->ext->datamapper->DB I get source with database objects.

**Comment by igarashitm** [comment] 2018-02-02 12:03
Hmm, actually datamapper host component looking at the connection right before&after itself, but it's only for Java online inspection. That shouldn't be a problem if DataShape.specification is correctly embedded.
https://github.com/syndesisio/syndesis/blob/1.2.7/app/ui/src/app/integrations/edit-page/step-configure/data-mapper/data-mapper-host.component.ts#L154-L169

step configure component is looking at step&connection here
https://github.com/syndesisio/syndesis/blob/1.2.7/app/ui/src/app/integrations/edit-page/step-configure/step-configure.component.ts#L199-L204

BTW I talked with Stan that the boolean flag passed to `fetchDataShapeFor()` should be opposite, should look at the **output** DataShape for previous step and **input** DataShape for subsequent step, so this is a bug. I fixed that as a part of #1367 though, we might want to fix it also for TP3.

**Comment by kcbabo** [comment] 2018-02-02 12:34
Marking this as a blocker for visibility until we can chase down the root cause.

**Comment by dsimansk** [comment] 2018-02-02 12:42
@igarashitm so adding inputDataShape definition to the extension has resolved the issue for me. In fact from you previous comment, that what fully definied dataShape is. I can now work with extension datashape in datamapper UI. Imho there no need to backport the fix, @kcbabo wdyt?

**Comment by kcbabo** [comment] 2018-02-02 12:45
If there's a way to make it work without a fix, then I vote we go with that for TP3.

I'm still a bit confused about why setting the output shape doesn't work.  Is there an issue here that needs to be tracked and fixed for TP4?

**Comment by igarashitm** [comment] 2018-02-02 12:50
Yep, there is a confusion around input/output flag in the UI code, checking opposite side of DataShape when it checks if exists. Note that only for existing checks, actual DataShape is retrieved correctly (as it is reversed twice...) That workaround is to add a dummy DataShape at opposite side and let them take the right one.

**Comment by igarashitm** [comment] 2018-02-02 12:51
And it is going to be addressed as a part of #1110 Data Buckets.

**Comment by kcbabo** [comment] 2018-02-02 13:01
Cool.  So @dsimansk - I'll leave it to you to remove the blocker flag if there are no issues blocking your progress.

**Comment by dsimansk** [comment] 2018-02-02 14:10
@kcbabo I've updated my project to the point that I'm able to map from extension to stored procedure of sql invoke. For the actual scenario I would either use DB insert or API that is exposed for Todo app currently (there's `Create new task` action) and it would be quiet nice demo imho.

If you'd like to review the extension (a bit of polish is still needed though):
https://github.com/dsimansk/syndesis-extension-tp3

**Comment by kcbabo** [comment] 2018-02-05 13:36
Super cool!  One comment that's going to annoy you though. :-) 

Can we implement this logic as a route and not as a bean?  I'd like to demonstrate that existing Camel developers can contribute extensions using the same approach they use to develop Fuse apps today.

I agree that the API approach would be cool to integrate with the Todo app.  Is there a Swagger for that API today?  If not, we should consider hosting it somewhere.  It could even just be included in the GitHub repository for the extension.

**Comment by dsimansk** [comment] 2018-02-06 13:39
@kcbabo actually that's a valid point. I've updated the code to leverage Camel processor pattern. Also I've cleaned up a bit and added pseudo-database in a list form that should simulate looking-up contact's detail. Now the extension generates single String task that can be mapped into our API or DB step sql like `INSERT INTO TODO (task) VALUES (:#task)`. I'll create a short screen cast to demonstrate once I'm done with sending custom message from Todo app. 

> Is there a Swagger for that API today?
Yes. In [the repository](https://github.com/syndesisio/todo-example/blob/master/swagger.json) and also it's part of Todo app deployment `<todo-url>/swagger.json`

**Comment by kcbabo** [comment] 2018-02-06 14:12
Thanks, David.  So looking at the logic for the bean, it looks like it could be done with Java DSL like:
``
.unmarhsall()
.split()
.filter()
``
Can we implement this logic using Java or XML DSL?

**Comment by kcbabo** [comment] 2018-02-06 14:22
@lburgazzoli : can you comment on whether an XML DSL route can be used with tech extensions for TP3?  Ideally, we would have an XML DSL route that replaces this bean:
https://github.com/dsimansk/syndesis-extension-tp3/blob/master/src/main/java/io/syndesis/extension/TodoDamageReporter.java

I believe that means that we would need to have a static definition of the extension json instead of auto-generating from the bean.

Can you confirm/correct the above?

**Comment by lburgazzoli** [comment] 2018-02-06 15:09
@kcbabo want to comment this morning but got lost in other stuffs. Yes you can use a route defined as xml or java according to the needs. If the route is written using XML the generation of the extension definition is left to you.

There is an [example](https://github.com/lburgazzoli/syndesis-extension-example-xml) on my github account which may be a little outdated but should help.

**Comment by dsimansk** [comment] 2018-02-06 16:39
@kcbabo ok now I get it :) Let me try to impl the xml variant. 

@lburgazzoli thanks!

**Comment by dsimansk** [comment] 2018-02-21 09:01
If there're no objections I'd like to close this issue as done.

Extension jar has been published in [its repo](https://github.com/syndesisio/fuse-online-tp3-sample-extension/releases) and is ready to be used.

**Closed by dsimansk** 2018-02-21 09:01 UTC
Labels: target/tp3

**Comment by kcbabo** [comment] 2018-02-21 13:51
Awesome.  Great job!
