### ISSUE TITLE
Skip Action configuration if there is no configuration

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2568] opened 2018-05-08 23:39 UTC
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

Not sure whether it already has been reported, but it would be awesome if we could avoid this empty unnecessary screen which forces the user to push a button even when an action doesn't need to be configured.

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/99080/39788230-587a84ce-52de-11e8-848a-8a503763c7cb.png">

**Comment by rhuss** [comment] 2018-05-08 23:50
This is also inconsistent to the way how "Steps" without configuration are handled: Steps are taken over directly without this intermediate screen.

**Comment by michael-coker** [comment] 2018-05-09 22:17
For reference, we addressed this behavior in https://github.com/syndesisio/syndesis/issues/1587. We'll re-visit in our next UXD meeting.

**Comment by michael-coker** [comment] 2018-06-05 20:48
@gashcrumb removing the `notif/uxd` label and assigning this to you since you addressed this back in https://github.com/syndesisio/syndesis/issues/1587. Feel free to reassign as you see fit.

**Comment by gashcrumb** [comment] 2018-06-08 12:32
Yeah, the trouble here is we have no way up front of knowing that a given action has no configuration until we query the server.  And automatically moving the user along when there's no configuration led to #1587 which is totally confusing.

We could fetch the action config though when the user selects the action on the previous wizard step and then skip this page.  The last hurdle will be what to do after the connection is set up and the user goes and clicks on that connection, I guess we disable the link for that connection that currently takes you to the action configuration page?

**Comment by michael-coker** [comment] 2018-06-08 14:01
> We could fetch the action config though when the user selects the action on the previous wizard step and then skip this page.

Do you mean instead of #1587 and displaying the "no properties to configure" alert then taking to the next page as _after a timeout_..., on the action configure step (after choosing the action), you fetch the properties and either show a configuration form if configurable properties exist, or just move to the next step if no properties are returned? Seems like that would work well.

> The last hurdle will be what to do after the connection is set up and the user goes and clicks on that connection, I guess we disable the link for that connection that currently takes you to the action configuration page?

I dunno if that would be necessary. I could see leaving it as it is now and showing them the "no properties to configure" alert since they clicked on that connection themselves. I think the original aim of this issue is just to advance people along through the workflow as easy as possible. Not being able to click on the connection after the start/finish points are configured could be confusing. What do you think @amysueg @dongniwang @sjcox-rh @seanforyou23.

Also an aside, when you create an integration, choose the start connection, and are on the "choose a finish connection" step, the link to the start connection isn't active. Is that by design?

**Comment by amysueg** [comment] 2018-06-08 14:14
I agree with the approach you described above, I'll restate it to make sure I understand: after choosing an action to configure, the system asks for properties and displays them if they are available, or just moves along to the next step if there are no properties to configure. Later if the user selects the action when they are viewing or editing the integration we will explicitly show a "this action has no configurable properties" or some wording.

To your aside question @michael-coker I think it is by design that you can't edit the start connection when you are on the choose a finish connection step. However, I suspect that we should make it possible for a user to back out of any action or step in the process with a "Cancel" or "Back to ..." button. This is larger than just this particular issue though, do you agree?

**Comment by gashcrumb** [comment] 2018-06-08 14:19
> I dunno if that would be necessary. I could see leaving it as it is now and showing them the "no properties to configure" alert since they clicked on that connection themselves.

I guess.  The tough part here is figuring out if it's the first time through configuring the connection/action or if it's the case when the user is re-visiting the action.  We don't really store that kind of information at the moment, but maybe we should so we can apply the appropriate behavior.

> Also an aside, when you create an integration, choose the start connection, and are on the "choose a finish connection" step, the link to the start connection isn't active. Is that by design?

Yes, when you're in a connection or step, the links in the side panel are disabled, requiring you to either click 'cancel' or 'done'.  Mostly to avoid data consistency issues that had come up.

**Comment by dongniwang** [comment] 2018-06-08 14:30
> I guess. The tough part here is figuring out if it's the first time through configuring the connection/action or if it's the case when the user is re-visiting the action. We don't really store that kind of information at the moment, but maybe we should so we can apply the appropriate behavior.

Agreed. 

I think we're trying to let users get through things as easy and quick as possible, but at the same time, also trying to provide flexibility (e.g. letting them change the action once it's configured)

**Comment by michael-coker** [comment] 2018-06-27 21:28
@gashcrumb do you have any other questions about this one? If you think it's ready to be worked on at some point, mind grabbing it or assigning it out?

**Closed** 2018-06-28 11:19 UTC
Labels: cat/feature, group/ui
