### ISSUE TITLE
Logo icon to small in 1.3.5

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2581] opened 2018-05-09 19:43 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

<img width="346" alt="image" src="https://user-images.githubusercontent.com/99080/39835919-99dba012-5386-11e8-9da9-4552210302fc.png">

**Comment by gashcrumb** [comment] 2018-05-09 19:54
Duplicate of https://github.com/syndesisio/syndesis/issues/2563

**Closed by gashcrumb** 2018-05-09 19:54 UTC
Labels: group/ui, notif/triage
