### ISSUE TITLE
Datamapper - I must delete mapping twice to make it disappear

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#6176] opened 2019-07-16 14:57 UTC
See also **https://issues.jboss.org/browse/ENTESB-11399**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

**Steps to reproduce:**
1. create a datamapper mapping
2. show mapping table in datamapper
3. select the mapping and click trash bin icon
4 click **Remove** button on **Remove Mapping?** dialog
nothing happens with the mapping
5. repeat 3 and 4
mapping deleted

![datamapper_delete](https://user-images.githubusercontent.com/8707251/61305076-78a86b00-a7ea-11e9-8dd5-47b83e4a869d.png)

**Comment by claudio4j** [comment] 2019-07-24 15:35
Hi @mastepan I couldn't reproduce with 1.8 master branch, can you confirm the syndesis version this bug happens ? Thanks.

**Comment by igarashitm** [comment] 2019-07-25 18:03
I tried with AtlasMap 1.41.1 which is now used by Syndesis upstream master and it didn't reproduce for me. @mastepan do you see anything in Javascript console when it happens?

**Comment by igarashitm** [comment] 2019-07-26 15:23
It did reproduce with CR2, guess it's fixed on upstream.

**Comment by heiko-braun** [comment] 2019-09-07 10:43
Migrated to **https://issues.jboss.org/browse/ENTESB-11399**

**Closed by heiko-braun** 2019-09-07 10:43 UTC
Labels: cat/bug, closed/migrated, ext/atlasmap, prio/p1, source/qe, target/7.5, zenhub/done
