### ISSUE TITLE
[ui] Connections are not updated after credentials are changed in Settings pane. 

### ISSUE THREAD

**Issue by dhirajsb** [syndesisio/syndesis#5763] opened 2019-06-15 18:49 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

User may update OAuth settings like Twitter API Key and Secret Key for various reasons, e.g. keys were regenerated in Twitter, a connection was imported from another Syndesis instance, so the keys in connection don't match what's in instance's OAuth configuration. 

When user changes the secrets in Settings page, UI doesn't show a bulletin for updating the now stale connection. Importing a connection from another instance does show a warning in Connections page. 

User edits connection and clicks on `Reconnect`, which goes through the OAuth flow, and validates new secrets from Settings. But, this never results in a Connection update on the backend, which still has the stale secrets. This can be verified by clicking on `Validate`, which fails due to an authentication error. 

I am not entirely sure whether this is simply a UI issue where a call to update Connection is missing, or the OAuth flow is supposed to update the Connection on its own in the backend. 

## Expected Behavior

1. After user edits OAuth secrets in Settings page, affected Connections must show a warning that they need to reconnect. 
2. After user reconnects in Connection Edit page, it should update the Connection in the backend with the updated secrets and updated OAuth tokens obtained from clicking `Reconnect`. 
3. Clicking `Validate` should use updated Connection properties. 

## Steps to recreate issue

1. Create a Twitter app
2. Set secrets in Settings page
3. Create Twitter Connection
4. Re-generate new secrets in Twitter app
5. Update secrets in Settings page
6. Edit Twitter connection. `Reconnect` works, but `Validate` fails.

**Comment by heiko-braun** [comment] 2019-06-20 10:42
@zregvart , @dhirajsb Did you have chance to talk through this?

**Comment by zregvart** [comment] 2019-06-20 10:49
I need to look into this, I haven't had the chance thus far.

**Comment by mkralik3** [comment] 2019-07-03 13:52
@zregvart Still present,
I have tested it on 1.7.8 tag.
![image](https://user-images.githubusercontent.com/16251792/60596019-6a009380-9da8-11e9-8fb6-0975d0572a57.png)

Step to reproduce:
- Go to the Settings -> Twitter and fill in Consumer API Key and Consumer API Secret Key.
- Go to the Connections -> Create Connection -> Twitter -> Click on Connect Twitter and fill in user name and password
- When the connection is created, the Validate button shows 
![image](https://user-images.githubusercontent.com/16251792/60596041-784eaf80-9da8-11e9-9712-81f0db83b408.png)
- Go to the https://developer.twitter.com/en/apps/ and regenerate _Consumer API keys_
- Go to the Settings -> Twitter and update values to the new generated keys and click on Save
- Go to the Connections -> Twitter and click on Reconnect
- Click on Validate button. The dialog "Could not authenticate you" is shown.

**Comment by mkralik3** [comment] 2019-07-03 13:54
@zregvart my bad, it works partially. When I go out from the connection details page and go back to the Connection, the validation button works, however when I click on Validate after Reconnect, it shows "Could not authenticate you".
I will create a new issue for that case because that is not p0 in my POV and we can close this issue.

**Comment by heiko-braun** [comment] 2019-07-03 13:58
> I will create a new issue for that case because that is not p0 in my POV and we can close this issue. WDYT?

yes, please

**Closed by heiko-braun** 2019-07-03 13:58 UTC
Labels: cat/bug, group/ui, prio/p0
