### ISSUE TITLE
AMQP Connection UI enhancement: Provide hint text for selected Schema type

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#1939] opened 2018-03-09 21:12 UTC
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
We could provide a little help on the page to users regarding the syntax of the selected Schema Type

## Expected behavior
When the user selects "Select Schema Type" dropdown and chooses a type, the "Schema" field could display hint text in the field for the selected type. The hint text would change if the user selected a different Schema type in the drop-down.

See #887 for dynamically changing view based on field selections and #1911 for providing hint text in fields. 

## Screenshot
This is not the most current but is the only screenshot I could find at the moment:
https://user-images.githubusercontent.com/24943812/36692596-89589d98-1b06-11e8-9841-54d2be73b443.png

## Tasks involved / Steps to Reproduce

1. 
2.
3.
4.

@dhirajsb @seanforyou23 @michael-coker @sjcox-rh @dongniwang

**Comment by gashcrumb** [comment] 2018-03-15 14:12
This is actually a duplicate of #1822

**Closed by gashcrumb** 2018-03-15 14:12 UTC
Labels: cat/enhancement, group/connector, group/ui
