### ISSUE TITLE
Investigate flaky test - io.syndesis.server.runtime.ExtensionsITCase

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#5534] opened 2019-05-31 10:07 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

```
testListExtensionDetails - io.syndesis.server.runtime.ExtensionsITCase

org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in io.syndesis.server.runtime.ExtensionsITCase expected:<[1]> but was:<[0]> within 60 seconds.
```

**Comment by zregvart** [comment] 2019-05-31 10:19
Duplicate of #4827

**Closed by zregvart** 2019-05-31 10:19 UTC
Labels: cat/bug, cat/build, group/server, prio/p2
