### ISSUE TITLE
UI: When defining an enum with a default value, the UI shows always the default value as selected ignoring the correct selection

### ISSUE THREAD

**Issue by oscerd** [syndesisio/syndesis#2749] opened 2018-06-05 09:07 UTC
## This is a...
<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
When you have an enum as action or connection configuration field, if a default value is specified in the JSON model, during the edit of connection or action, the actual value you choose will be always overidden (at UI level) by this default Value, while under the hood the value is defined correctly in the connection object. If you remove the default Value this behavior will disappear

## Expected behavior
Show the right value during editing of a connection or an action

## Tasks involved / Steps to Reproduce
A way to reproduce is explained here: https://github.com/syndesisio/syndesis/issues/2420

**Comment by oscerd** [comment] 2018-06-05 09:22
@paoloantinori what priority for this?

**Comment by gashcrumb** [comment] 2018-06-05 10:53
I might have sorted this already in this PR -> https://github.com/syndesisio/syndesis/pull/2722

unless you've tested against master recently in which case I totally didn't apparently :-)

**Comment by oscerd** [comment] 2018-06-05 10:59
I tested from master :-)

**Comment by gashcrumb** [comment] 2018-06-05 11:54
Awesome, see I'm just giving myself stuff to do, you know?  Will look today :-)

**Comment by oscerd** [comment] 2018-06-05 11:57
Take your time, I don't think is high priority :-)

**Comment by gashcrumb** [comment] 2018-06-05 12:27
Did you rebuild the UI and/or clear your browser cache?  'cause this is what I'm seeing after creating a connection with a different region for example:

![capture](https://user-images.githubusercontent.com/351660/40975797-1ba0a0ca-689a-11e8-88a6-e5c7f3b2fed4.PNG)

before that PR the form was definitely not properly picking up the configured properties object properly.

**Comment by oscerd** [comment] 2018-06-05 12:34
Let me try in an incognito tab

**Comment by oscerd** [comment] 2018-06-05 12:36
In an incognito window I see the correct behavior. The problem was reported here:  #2420 

but probably is the same stuff, @tplevko can you double check please?

**Comment by gashcrumb** [comment] 2018-06-05 13:35
Yep, this is a dupe of #2720, let's close this one and we'll hopefully close #2420 after a re-test.

**Closed by gashcrumb** 2018-06-05 13:35 UTC
Labels: group/ui, notif/triage
