### ISSUE TITLE
Unable to upload .json spec for API Provider connection in Chrome

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis#3823] opened 2018-10-12 19:01 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

I have Syndesis 1.5.4-2018-1012 installed on my Linux CSB laptop (running RHEL 7). I cloned the quickstart: 

git clone https://github.com/syndesisio/syndesis-quickstarts.git

So I have a local copy of task-api.json. 

In Firefox, I can drag it in or upload it. In Chrome, I get:

'task-api.json' is not a valid file. Only files that end in '.json' can be uploaded.

To reproduce:

Open Syndesis in Chrome.
Click Create Integration. 
Click API Provider.
Click Choose File. 
Navigate to and select syndesis-quickstarts/api-provider/task-api.json.
Click Open. 
Syndesis displays: 'task-api.json' is not a valid file. Only files that end in '.json' can be uploaded.

Click Cancel and Yes.
Click Create Integration. 
Click API Provider. 
Drag syndesis-quickstarts/api-provider/task-api.json into the drop area. 
Syndesis displays: 'task-api.json' is not a valid file. Only files that end in '.json' can be uploaded.

In Firefox, doing this with the same file is successful.

**Comment by riccardo-forina** [comment] 2018-10-15 12:12
I can't reproduce it locally. Perhaps it's something Chrome-on-Linux specific? Anyone else who can try to reproduce this?

**Comment by asmigala** [comment] 2018-10-15 12:40
I can confirm I am able to upload a json file in Chrome on Linux, both by selecting using the file picker and by drag-and-dropping.

Fedora 28, Chrome 68

**Comment by TovaCohen** [comment] 2018-10-15 15:13
Thanks for looking into this. Just want to let you know that I re-installed Syndesis and tried again. Still does not work for me. I also tried to upload other example .json files that defined APIs and while specifying the URL always works, I cannot select a file and successfully upload it, and I cannot drag and drop a file. But maybe it is something in my Chrome set up.

**Comment by heiko-braun** [comment] 2018-10-22 12:10
@TovaCohen What browser are you using / operating system?

**Comment by heiko-braun** [comment] 2018-10-22 12:51
@TovaCohen Have you been able to resolve it in the meantime?

**Comment by TovaCohen** [comment] 2018-10-22 12:57
Linux CSB (corporate standard build) and I think it runs RHEL 7 something. It's managed by Red Hat and software updates are pretty much automatic. I just click "Update" whenever I get a notification that updates are available. 
Chrome Version 59.0.3071.115 (Official Build) (64-bit)
I can try this again later, in about 90 minutes. sorry I can't try it now.

**Comment by TovaCohen** [comment] 2018-10-22 15:41
I just tried this again on the staging site, using Chrome incognito, and it works. 
I no longer have access to my own Fuse Online evaluation so I can't try it in that. I applied for a new evaluation and I'll try it again as soon as I get it.

**Comment by heiko-braun** [comment] 2018-10-22 15:55
Do you have access to syndesis staging?

**Comment by TovaCohen** [comment] 2018-10-22 15:57
@heiko-braun Yes - see my previous comment. It works for me on the staging site. :-)

**Comment by heiko-braun** [comment] 2018-10-22 16:19
Apologies, i should read more carefully. Based on your comments I am closing this now.

**Closed by heiko-braun** 2018-10-22 16:19 UTC
Labels: cat/bug
