### ISSUE TITLE
When creating the oAuth Connection for the twitter connector, UI should match the words in the Twitter UI.

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#2421] opened 2018-04-17 21:40 UTC
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
We use different terminology from twitter for the client id / secret from what twitter calls the fields on their admin screens.  Would be nice if they matched up so that user can more easily configure our UIs.

## Expected behavior
We should label our fields 'Consumer Key (API Key)' and 'Consumer Secret (API Secret)'

## Screenshot
What Twitter shows a user:
![syndesis_test_1___twitter_application_management](https://user-images.githubusercontent.com/103255/38899481-00a4871e-4266-11e8-8668-be4c55a3b8a9.jpg)

What Syndesis asks for in it's Oauth settings screen:
![syndesis](https://user-images.githubusercontent.com/103255/38899515-1553382c-4266-11e8-98f9-29b55876cc1a.jpg)

**Comment by zregvart** [comment] 2018-04-18 07:58
Duplicate of #240

**Closed by zregvart** 2018-04-18 07:58 UTC
Labels: group/connector
