### ISSUE TITLE
Illegal access of connector property on a connection without it

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5396] opened 2019-05-17 10:50 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

The Knative connection doesn't embed `connector` within it so accessing `connection.connector.someprop` will result in an error in the UI.

Not exactly sure how to fix it other than to skip over the knative connector.

On a clean database this looks like:

![Peek 2019-05-17 12-50](https://user-images.githubusercontent.com/1306050/57923359-5f467980-78a2-11e9-9516-058e57629b65.gif)

cc @gashcrumb @nicolaferraro

**Comment by gashcrumb** [comment] 2019-05-17 10:57
Yeah, we can't cope with a connection that doesn't have the connector embedded.  Specifically for the step select screen we need to check the actions on the connector to see if that connection can be shown to the user.

**Comment by riccardo-forina** [comment] 2019-06-13 16:26
Wonder, can we still have connections without a connector? We don't have any check like this one in the React UI.

**Comment by asmigala** [comment] 2019-07-03 14:10
The knative connection has a `connector` as of 1.7.8 and the issue is not reproducible anymore, closing

**Closed by asmigala** 2019-07-03 14:10 UTC
Labels: cat/bug, group/connector, group/server, group/ui, prio/p0
