### ISSUE TITLE
Class inspection for twitter4j.Status not found 

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#635] opened 2017-12-06 15:16 UTC
@rhuss @zregvart is it possible that inspection wasn't generated for latest image?

```
{
  "ClassInspectionRequest": {
    "jsonType": "io.atlasmap.java.v2.ClassInspectionRequest",
    "classpath": "",
    "className": "twitter4j.Status",
    "disablePrivateOnlyFields": false,
    "disableProtectedOnlyFields": false,
    "disablePublicOnlyFields": false,
    "disablePublicGetterSetterFields": false
  }
}
```

```
{
  "ClassInspectionResponse" : {
    "jsonType" : "io.atlasmap.java.v2.ClassInspectionResponse",
    "javaClass" : {
      "jsonType" : "io.atlasmap.java.v2.JavaClass",
      "status" : "NOT_FOUND",
      "className" : "twitter4j.Status",
      "javaEnumFields" : {
        "javaEnumField" : [ ]
      },
      "javaFields" : {
        "javaField" : [ ]
      }
    },
    "executionTime" : 0
  }
}
```

**Comment by dsimansk** [comment] 2017-12-07 08:12
@zregvart I can't really find the right conditions to reproduce the behaviour, but I'm seeing it intermittently on `Twitter::Mention` to `Salesforce::Create or Update` or `Salesforce::New record`.  The inspection response plainly returns `NOT_FOUND` status.

**Comment by zregvart** [comment] 2017-12-07 08:22
@dsimansk let's reopen and see if you can capture a failing request, AFAIK class inspection should be stateless and that would make it deterministic so for same given parameters we should observe same results.

**Comment by dsimansk** [comment] 2017-12-07 10:12
So in a failing case, there's one more request to class inspection endpoint `/v2/atlas/java/class`, that returns not found response. The working flow doesn't have such request and goes straight to `/v2/atlas/json/inspect` with `JsonInspectionRequest` object.

For JSON payload request
` curl -vk --cookie $COOKIE -H "Content-Type: application/json" -XPOST -d @inspection_fail.json "https://syndesis-e2e-tests.b6ff.rh-idev.openshiftapps.com/v2/atlas/java/class"`
```
{
  "ClassInspectionRequest": {
    "jsonType": "io.atlasmap.java.v2.ClassInspectionRequest",
    "classpath": "",
    "className": "twitter4j.Status",
    "disablePrivateOnlyFields": false,
    "disableProtectedOnlyFields": false,
    "disablePublicOnlyFields": false,
    "disablePublicGetterSetterFields": false
  }
}
```

```
{
  "ClassInspectionResponse" : {
    "jsonType" : "io.atlasmap.java.v2.ClassInspectionResponse",
    "javaClass" : {
      "jsonType" : "io.atlasmap.java.v2.JavaClass",
      "status" : "NOT_FOUND",
      "className" : "twitter4j.Status",
      "javaEnumFields" : {
        "javaEnumField" : [ ]
      },
      "javaFields" : {
        "javaField" : [ ]
      }
    },
    "executionTime" : 0
  }
```

**Comment by zregvart** [comment] 2017-12-07 10:17
This makes perfect sense with atlasmap/atlasmap-runtime#194 and the change in https://github.com/atlasmap/atlasmap/commit/fc3ab80f3bbc3a7221390744bdbf5d4064082649#diff-db440dcf358f0ea7c7b2095b333676ceL219

I'm a bit fuzzy on when we use Atlasmap for inspection vs inspector builtin into Syndesis, @iocanel @chirino can you chime in?

**Comment by dsimansk** [comment] 2017-12-07 12:46
Well, I can seen that first there's a request to fetch pre-computed inspection from `v1/java-inspections/twitter/twitter4j.Status.json`, that gets expected json. However, in ~50% of cases it's followed by class inspection request to Atlasmap API, that shouldn't happen. Maybe a promise chain issue in datamapper init service?

**Comment by zregvart** [comment] 2017-12-07 12:54
@syndesisio/ui-api can one of you UI folk take a look at this?

**Comment by igarashitm** [comment] 2017-12-07 13:02
Syndesis now only consumes pre-computed inspection result, which is gathered at startup time via atlasmap maven plugin. I think syndesis-rest is running it during startup, @chirino correct?

And I'm looking for the endpoint URL which returns pre-computed inspection cache... it must be somewhere in the syndesis-rest...

**Comment by dsimansk** [comment] 2017-12-07 13:03
@igarashitm sorry I haven't copied the whole endpoint `/mapper/v1/java-inspections/`.

**Comment by igarashitm** [comment] 2017-12-07 13:05
@dsimansk ah yeah, that should be it, and if it's returning 404 for the twitter4j.Status, I think that inspection cache via maven plugin is failing somehow.

**Comment by dsimansk** [comment] 2017-12-07 13:09
@igarashitm that is working as expected, but in some cases there is another request to Atlasmap inspection regardless of pre-computed inspection results and in that case Atlasmap class inspection fails, see my [previous comment](https://github.com/syndesisio/syndesis/issues/635#issuecomment-349922864).

**Comment by igarashitm** [comment] 2017-12-07 13:13
@dsimansk ah OK understood, so the online inspection is failing. And as @zregvart already pointed out the exact change, it's expected, atlasmap/ui shouldn't request online inspection at all within syndesis. hmm how could it be invoked...

**Comment by igarashitm** [comment] 2017-12-14 19:37
This is highly likely to be caused by atlasmap/atlasmap#176 atlasmap-maven-plugin was returning NOT_FOUND for twitter4j.* types of fields. I guess then UI was retrying inspection for sub-fields, which throw a request to online inspection.
This has been fixed in 1.32.1 just released. If it still happens, we need to figure out why online inspection is still invoked.

**Comment by igarashitm** [comment] 2017-12-14 20:47
Hmm nope, UI looks like just ignoring `NOT_FOUND` fields... not retrying. So online inspection is invoked from somewhere else.

I'll try looking into it but it's UI and would take longer to figure out. Safest way is to restore all the connector dependencies into atlasmap design runtime classpath.

**Comment by igarashitm** [comment] 2017-12-14 21:55
I believe only this line possibly invokes Java inspection
https://github.com/atlasmap/atlasmap/blob/62c6f54c123918f4ab35f23e2a7a9c9d49726e5f/ui/src/app/lib/atlasmap-data-mapper/services/document.management.service.ts#L95

which means `docDef.initCfg.inspectionResultContents` is `null` somehow. This is populated here, from pre-computed inspection result
https://github.com/syndesisio/syndesis/blob/9b7f5b0f571a15c114d4a6181f84b73028ff3aa7/app/ui/src/app/integrations/edit-page/step-configure/data-mapper/data-mapper-host.component.ts#L122

I have no idea how it happens. @syndesisio/ui-api any idea?

**Comment by jimmidyson** [comment] 2017-12-20 14:52
@syndesisio/ui-api Any ideas about this? Can we look this week, or is it safe to defer to TP4?

**Comment by jimmidyson** [comment] 2017-12-21 11:39
@kahboom @deeleman Really would appreciate one of you working with @igarashitm to figure out what's going on here.

@igarashitm What's the impact on the user of this error?

**Comment by igarashitm** [comment] 2017-12-21 12:28
@jimmidyson although I haven't succeeded to reproduce, possibly datamapper UI doesn't open at all if it happens. This looks very nasty, from me as a beginner of angular development, it looks like a race condition in angular that the inspection result vanishes in the middle or like that. I might be overlooking something easy though.

**Comment by chirino** [comment] 2018-01-03 15:05
If I recall correctly, this class has recursion in it.  Perhaps the online look up occurs when you try to navigate to deeper recursive levels.

**Comment by chirino** [comment] 2018-01-03 16:03
I just started debugging the .js, seems like the atlas component is intialized before the Status shape is loaded.

**Comment by chirino** [comment] 2018-01-04 13:56
Fixed.

**Closed by chirino** 2018-01-04 13:56 UTC
Labels: cat/bug, module/ui, target/tp3
