### ISSUE TITLE
Cannot create log connection step

### ISSUE THREAD

**Issue by jsafarik** [syndesisio/syndesis#4943] opened 2019-03-18 14:56 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When trying to add Log connection (Log -> Simple Logger action) as finish step, the connection just keeps loading and nothing happens. the chrome console displays 
`ERROR TypeError: Cannot read property 'find' of undefined
    at /12.93e47d2f00a932911647.js:1
    at Array.forEach (<anonymous>)
    at n.reconcileAllDataShapes (/12.93e47d2f00a932911647.js:1)
    at o (/12.93e47d2f00a932911647.js:1)
    at n.handleEvent (/12.93e47d2f00a932911647.js:1)
    at /12.93e47d2f00a932911647.js:1
    at e.t.object.o [as _next] (main.f99b4e125a82f5836537.js:1)
    at e.__tryOrUnsub (polyfills.cd1c6ed959cbc1c630d4.js:1)
    at e.next (polyfills.cd1c6ed959cbc1c630d4.js:1)
    at e._next (polyfills.cd1c6ed959cbc1c630d4.js:1)`

## Screenshot

![simple_logger](https://user-images.githubusercontent.com/46523434/54539224-0340a100-4996-11e9-9c44-dcc2aed301c1.png)

## Tasks involved / Steps to Reproduce

1. select periodic sql invocation as start step
2. select Log connection as finish step with simple logger action

**Comment by gashcrumb** [comment] 2019-03-18 15:00
This is a duplicate of https://github.com/syndesisio/syndesis/issues/4933

**Comment by christophd** [comment] 2019-03-18 15:01
PR to fix it is already on its way https://github.com/syndesisio/syndesis/pull/4940

**Closed by gashcrumb** 2019-03-18 15:00 UTC
Labels: cat/bug, notif/triage, prio/p0, source/qe
