### ISSUE TITLE
Error creating new API connector: Please check your sorting arguments

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#5002] opened 2019-03-20 14:52 UTC
## This is a...

<pre><code>
[X] Bug report  
</code></pre>

## Expected behavior
That the api imports.

## Screenshot
![Syndesis](https://user-images.githubusercontent.com/103255/54694229-49187900-4afe-11e9-9757-266489ee6833.jpg)

## Request and Response Data
Tried to import this API:

[Machine History.json.txt](https://github.com/syndesisio/syndesis/files/2988758/Machine.History.json.txt)

**Comment by zregvart** [comment] 2019-03-20 14:57
@chirino can you check if your version includes the fix for #4486

**Comment by heiko-braun** [comment] 2019-03-21 15:22
Closing as duplicate of  #4486

**Closed by heiko-braun** 2019-03-21 15:22 UTC
Labels: notif/triage
