### ISSUE TITLE
OData read entity returns null when mapped

### ISSUE THREAD

**Issue by jsafarik** [syndesisio/syndesis#5386] opened 2019-05-16 12:59 UTC
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I tried to create simple integration OData (read) -> Data Mapper -> OData(update). When published, it fails every time with error mentioned below.
```
io.atlasmap.api.AtlasException: Errors: [Unexpected exception is thrown while reading source field: null: docId='-Lf-gxkgsYfw_FUEYeOu', path='/ID'], [Unexpected exception is thrown while reading source field: null: docId='-Lf-gxkgsYfw_FUEYeOu', path='/ID'], [Unexpected exception is thrown while reading source field: null: docId='-Lf-gxkgsYfw_FUEYeOu', path='/ID'], [Unexpected exception is thrown while reading source field: null: docId='-Lf-gxkgsYfw_FUEYeOu', path='/ID'], [Unexpected exception is thrown while reading source field: null: docId='-Lf-gxkgsYfw_FUEYeOu', path='/ID'], [Unexpected exception is thrown while reading source field: null: docId='-Lf-gxkgsYfw_FUEYeOu', path='/Name'], [Unexpected exception is thrown while reading source field: null: docId='-Lf-gxkgsYfw_FUEYeOu', path='/ID'], [Unexpected exception is thrown while reading source field: null: docId='-Lf-gxkgsYfw_FUEYeOu', path='/ID'], [Unexpected exception is thrown while reading source field: null: docId='-Lf-gxkgsYfw_FUEYeOu', path='/Name'], [Unexpected exception is thrown while reading source field: null: docId='-Lf-gxkgsYfw_FUEYeOu', path='/Name'], 
	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:266)
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.process(ActivityTrackingInterceptStrategy.java:79)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:80)
	at org.apache.camel.util.component.ApiConsumerHelper.processResult(ApiConsumerHelper.java:140)
	at org.apache.camel.util.component.ApiConsumerHelper.getResultsProcessed(ApiConsumerHelper.java:127)
	at org.apache.camel.component.olingo4.Olingo4Consumer.poll(Olingo4Consumer.java:106)
	at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:174)
	at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by phantomjinx** [comment] 2019-05-24 12:21
@jsafarik 
Would you mind providing a little more detail about the particular services you were testing & the nature of the mapping you performed. Have just performed this with a test odata server (oddly reading then updating itself with the same values) & it has worked fine. So ...
1. Is the odata server the same for both the 'read' & the 'update'?
2. What are the credentials for the odata server, if relevant?
3. How did the mapping between the odata-read & odata-update go?

Thx.

**Comment by jsafarik** [comment] 2019-05-28 13:31
@phantomjinx 
I've tried it with this [service](https://services.odata.org/TripPinRESTierService/) with generated . the server is the same for both the read and update operations. There are no credentials for the service (just need to open the link and copy the url from browser - there is a unique key so noone can modify the instance a person is using). The read operation is working as supposed, but when at the data mapper step it has error. See attached screenshot below

![Screenshot from 2019-05-28 15-30-12](https://user-images.githubusercontent.com/46523434/58481861-8b44e300-815d-11e9-88df-724013aa9263.png)

I can try this integration with the service we use in our tests (the service is based on olingo tutorial project).

**Comment by jsafarik** [comment] 2019-05-28 13:34
+ it would be useful if the output of odata error had the URL it's trying to read from, just to see if it is accessing the right URL (with the correct path)

**Comment by jsafarik** [comment] 2019-05-28 13:51
So I've just tried it with the [service](https://github.com/syndesisio/syndesis-qe-olingo-sample-service) we use in out tests, and the result is the same. there is an error when outputed from the data mapper step. According to logs of the service, the GET request is performed, but (obviously) the PATCH request is never performed.

**Comment by phantomjinx** [comment] 2019-05-29 17:21
The Airlines resource has concurrency control implemented on it. See the OptimisticConcurrency annotation in the [metadata](https://services.odata.org/TripPinRESTierService/$metadata).

So first off, I avoided using the same connection for both read and update.
- Read: https://services.odata.org/TripPinRESTierService
- Update: https://services.odata.org/TripPinRESTierService/(S(4gus0w41xmxedlzbywj2srqo))
This meant, at least, I was not updating the same resource as I had just read from.

Executing this in an unit test resulted in the real problem -> no If-None-Match header in the PATCH request (@jsafarik: you've flagged the need for this before!). To fully implement this, the underlying camel-olingo4 component actually has to perform a GET request prior to the PATCH request in order to extract the contents of the server's ETag header. This value is then provided in the PATCH request in the If-None-Match header. Only with this header correctly added, will an update work.

This is an operation that must be performed in the underlying camel component so I have created a [feature request](https://issues.apache.org/jira/browse/CAMEL-13598) - the priority of which is TBD.

At the moment, I can try and bypass the error by including the [wildcard](https://www.odata.org/documentation/odata-version-2-0/operations/) '*' as the value of the If-None-Match header & will see if that helps. This is only a workaround as this simply overwrites the entity essentially disabling the concurrency control.

**Comment by jsafarik** [comment] 2019-05-30 09:02
Well, I tried the integration with the service we use in our tests (which doesn't support OptimisticConcurrency yet) and got the same exception. The service we use still needs refactoring I am working on, but according to the logs of this service, the integration does only the initial GET request, no other request happens after that.

![odata_error](https://user-images.githubusercontent.com/46523434/58621599-16db8280-82ca-11e9-91b4-f0957bc73645.png)

I tried it with the Airports resource collection as well (which according to $metadata page doesn't support OptimisticConcurrency) and the result is again the same.

![trippin_airport_error](https://user-images.githubusercontent.com/46523434/58621633-26f36200-82ca-11e9-91f4-0f3272968fc5.png)

for the Airlines collection:

![trippin_airline_error](https://user-images.githubusercontent.com/46523434/58621677-3d012280-82ca-11e9-98dc-2334234b51a8.png)

I am aware of the issue with the need of use of the ETag in If-Match or If-None-Match headers, but with the results I stated above, I am thinking if there is not another issue.

**Comment by phantomjinx** [comment] 2019-05-30 12:28
OK. So now I'm seeing differences to you.
Switching to Airports as you did, I have no errors at all:

1. I first ran the integration with different connections as I mentioned [above](https://github.com/syndesisio/syndesis/issues/5386#issuecomment-497030535). It worked.
![read-update-version-3](https://user-images.githubusercontent.com/1634180/58632696-43999500-82de-11e9-94d9-5061dd66d54e.png)

2. I then thought to confirm that using the same connection for both read and update was the problem. However, that too worked.
![read-update-version-4](https://user-images.githubusercontent.com/1634180/58632721-5b711900-82de-11e9-8738-6334b94886a2.png)
![read-update-int-version-4](https://user-images.githubusercontent.com/1634180/58632727-5e6c0980-82de-11e9-81f6-549a3777e93a.png)

So, maybe its a difference in the mappings that we are creating?
![read-update-mapping](https://user-images.githubusercontent.com/1634180/58632800-a0954b00-82de-11e9-9a96-bd11507c80b8.png)
- Note. I don't map the icaoCode since this is the key predicate so consider that something needs to remain the same in order for the mapping to be found.

**Comment by jsafarik** [comment] 2019-05-31 08:35
Just tried exactly the same integration (including the same mapping) as you, and it resulted again in an error.

![read_op](https://user-images.githubusercontent.com/46523434/58692369-c5e19200-838e-11e9-83db-9626e56d62a2.png)

![map_op](https://user-images.githubusercontent.com/46523434/58692344-bbbf9380-838e-11e9-8d6a-3587c2aa2f19.png)

![activity_log](https://user-images.githubusercontent.com/46523434/58692394-cd08a000-838e-11e9-83ec-bd671cd1d9f9.png)

Not sure what can be causing this then. I am on 1.7-SNAPSHOT with commit id 33448d721a671c230329712d1c775211b93c560e. Will try with different connections as start and finish steps as you mentioned to see what happens.

**Comment by phantomjinx** [comment] 2019-05-31 14:48
Further work by @jsafarik and I lead to the following errors that require fixing:
1. OData Read Connection -> Split Results: FALSE   Filter Old Results: FALSE  Key Predicate: "KSFO"
- Reproduces the mapping error as reported.
- Reason: The presence of the key predicate causes the [MetaRetrieval class](https://github.com/syndesisio/syndesis/blob/master/app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrieval.java#L199) to generate an output datashape of Entity Schema & not Array Schema. However, the key predicate is not observed by the [ODataReadCustomizer](https://github.com/syndesisio/syndesis/blob/master/app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/ODataReadCustomizer.java#L31), responsible for converting the odata results into json prior to it being passed on to the Data Mapping Step. Therefore, the real data is passed to the Data Mapper as an array whilst it was expecting an entity schema.

2. OData Read Connection -> Split Results: TRUE   Filter Old Results: FALSE  Key Predicate: NONE
- Successfully running integration

3. OData Read Connection -> Split Results: FALSE   Filter Old Results: FALSE  Key Predicate: NONE
- Causes a "Resource Not Found" error from the update connection. The actual URI executed is
`https://services.odata.org/TripPinRESTierService/(S(4gus0w41xmxedlzbywj2srqo))/Airports('null')`
- Reason: The check for a key predicate in the [MetaRetrieval class](https://github.com/syndesisio/syndesis/blob/master/app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrieval.java#L199) is not correct since a _containsKey_ is used. Unfortunately, the key is always there but set to null. Therefore, the output datashape is set to Entity Schema when it should be Entity Array Schema.

**Comment by phantomjinx** [comment] 2019-05-31 15:05
Should point out that following scenario is failing:
- Filter Old Results: TRUE
- Key Predicate: 'KSFO'

This is generating NP Exceptions from the filtering mechanism in the Olingo4Consumer. This is a separate issue, logged as #5533.

**Comment by paoloantinori** [comment] 2019-06-12 12:54
@phantomjinx has this been fixed? can we close it?

**Comment by phantomjinx** [comment] 2019-06-12 14:56
@paoloantinori
Yes via #5599.

**Closed** 2019-07-08 10:47 UTC
Labels: cat/bug, closed/verified, group/connector, prio/p0, source/qe
