### ISSUE TITLE
Verify Syndesis on OCP 4

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#4614] opened 2019-02-18 09:55 UTC

**Comment by lgarciaaco** [comment] 2019-05-16 11:21
I gave it a try using [crc](https://github.com/code-ready/crc) and [latest fuse release](https://github.com/syndesisio/fuse-online-install/tree/1.6.20). The installation scripts works, resoruces are created, but following pods aren't coming up:

- syndesis-db
- syndesis-meta
- syndesis-prometheus

All with the error:
```
pod has unbound immediate PersistentVolumeClaims
```

It is a known issue for CRC team that it is not possible to create PV, this is their issue: https://github.com/code-ready/snc/issues/16. Next CRC release should happen next week, and it should include a fix for the PV creation.

**Comment by lgarciaaco** [comment] 2019-05-16 11:22
Blocked by https://github.com/code-ready/snc/issues/16

**Comment by lgarciaaco** [comment] 2019-05-16 11:23
@heiko-braun ^^

**Comment by heiko-braun** [comment] 2019-05-16 12:41
Thanks for verifying it @lgarciaaco.  Let's for the next CRC release.

**Comment by lgarciaaco** [comment] 2019-05-28 15:30
I gave this another try using fuse-online-install 1.6.20 an https://github.com/code-ready/crc/releases/tag/0.86.0

I was able to install syndesis without problems, however, oauthproxy throws 500 errors after
authenticating, I am not able to pass beyond this point. The errors in oauthproxy are:

```
2019/05/28 15:28:03 provider.go:572: 404 GET https://oauth-openshift.apps.ocpdev-41.3sca.net/apis/user.openshift.io/v1/users/~ {
  "paths": [
    "/apis",
    "/healthz",
    "/healthz/log",
    "/healthz/ping",
    "/healthz/poststarthook/clientCA-reload",
    "/healthz/poststarthook/oauth.openshift.io-startoauthclientsbootstrapping",
    "/healthz/poststarthook/requestheader-reload",
    "/metrics",
    "/readyz",
    "/readyz/log",
    "/readyz/ping",
    "/readyz/poststarthook/clientCA-reload",
    "/readyz/poststarthook/oauth.openshift.io-startoauthclientsbootstrapping",
    "/readyz/poststarthook/requestheader-reload",
    "/readyz/terminating"
  ]
}
2019/05/28 15:28:03 oauthproxy.go:635: error redeeming code (client:10.128.2.3:38250): unable to retrieve email address for user from token: got 404 {
  "paths": [
    "/apis",
    "/healthz",
    "/healthz/log",
    "/healthz/ping",
    "/healthz/poststarthook/clientCA-reload",
    "/healthz/poststarthook/oauth.openshift.io-startoauthclientsbootstrapping",
    "/healthz/poststarthook/requestheader-reload",
    "/metrics",
    "/readyz",
    "/readyz/log",
    "/readyz/ping",
    "/readyz/poststarthook/clientCA-reload",
    "/readyz/poststarthook/oauth.openshift.io-startoauthclientsbootstrapping",
    "/readyz/poststarthook/requestheader-reload",
    "/readyz/terminating"
  ]
}
2019/05/28 15:28:03 oauthproxy.go:434: ErrorPage 500 Internal Error Internal Error
```


Using `syndesis install setup` and `syndesis install` it also works and without the problem with
oauthproxy. Here I am able to create an integration afterwards, I only did very little testing but it seems functional.

I also tried installing it is the shared 3scale odk 4 cluster, and results are the same as with crc, which discards a problem with crc.

**Comment by nicolaferraro** [comment] 2019-05-28 15:34
Maybe because of this https://github.com/syndesisio/syndesis/issues/5010

Syndesis works on OCP4, prod version still not.

**Comment by lgarciaaco** [comment] 2019-05-28 15:36
it might be that ... thx

**Comment by heiko-braun** [comment] 2019-05-28 15:46
1.6.20 is still using 3.x oauth-proxy which doesn't work on OCP 4. We need to update to a 4.0.x version of that: https://github.com/syndesisio/syndesis/issues/5010

Syndesis master is using, if you want to try that one.

**Comment by lgarciaaco** [comment] 2019-05-28 16:02
Yes, with quay.io/openshift/origin-oauth-proxy:v4.0.0 it works :man_dancing:

**Comment by dhirajsb** [comment] 2019-06-03 20:47
Closing issue as it was caused by a version mismatch.

**Closed by dhirajsb** 2019-06-03 20:47 UTC
Labels: Epic
