### ISSUE TITLE
Unable to map multiple fields to one target field in the datamapper

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#2292] opened 2018-04-09 17:00 UTC
## This is a...

<pre><code>
[*] Feature request
[] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
I'd like to map multiple source fields to one target field om the datamapper.

## Screenshot
<img width="1052" alt="screen shot 2018-04-09 at 12 57 43 pm" src="https://user-images.githubusercontent.com/35576/38511321-d04289d4-3bf5-11e8-97c2-052ca4a334da.png">

## Tasks involved / Steps to Reproduce
Create a DB2DB scenario. Try to map more then one source field to one single target field.

**Comment by paoloantinori** [comment] 2018-04-10 11:27
hi @igarashitm , @pleacu , I'm currently marking this as a blocker, since it sounds quite important. Please have a look at this!

**Comment by igarashitm** [comment] 2018-04-10 11:52
This is by design, `Map` mapping is meant to be one-to-one mapping. You need to use `Combine` mapping to do many-to-one mapping.

We think this is not the best from UX perspective, and have a plan to improve with #27, but it's a bigger enhancement and won't come before GA.

**Comment by KurtStam** [comment] 2018-04-10 13:30
@paoloantinori I used to be able to connect multi source fields to one target field. I think we even demoed this as a feature at Summit last year @kcbabo?

**Comment by igarashitm** [comment] 2018-04-10 13:32
@KurtStam do you see `Action` pull-down menu which is set to `Map` by default in the `Mapping Details` at right side? You just need to change it to `Combine`

**Comment by KurtStam** [comment] 2018-04-10 13:35
@igarashitm Thx - I tried that and didn't work for me. BTW even if it works shouldn't it switch automatically when trying to map multiple fields?

**Comment by igarashitm** [comment] 2018-04-10 13:45
> I tried that and didn't work for me

Do you mean you can't add more source fields by clicking in `Combine`? @pleacu implemented an UI improvement to enable Ctrl-click to add more source fieds by atlasmap/atlasmap#95, but it's not yet in syndesis. You need to add those from `Mapping Details` panel in the meantime.

> BTW even if it works shouldn't it switch automatically when trying to map multiple fields?

You need to wait for #27 and #244 to be implemented after GA

**Comment by pleacu** [comment] 2018-04-10 13:55
Here is a screen shot of combine/ separate:

![am1](https://user-images.githubusercontent.com/2981421/38560881-ab1190ce-3ca4-11e8-992c-f5d2573a8b6b.png)

As Tomo said - 'Map" is a one-to-one operation.  For 'Combine" select a source element, change the 'Mapping Details' action to 'Combine' and the ctrl-m1 the other elements you wish to combine into a single target element.  'Separate' is the same in reverse (select a target and ctrl-m1 other targets and connect to a singke source).  This was just checked in yesterday - all feedbacj welcome.

**Comment by pleacu** [comment] 2018-04-10 14:00
Form completeness - generated XML from diagram above:

![dm2](https://user-images.githubusercontent.com/2981421/38561387-e732f8d0-3ca5-11e8-9050-c37d02f5c3f5.png)

**Comment by igarashitm** [comment] 2018-06-20 10:37
Ctrl-click and auto-transition to Separate/Combine by selecting multiple fields has been implemented.

**Closed by igarashitm** 2018-06-20 10:37 UTC
Labels: cat/feature, ext/atlasmap, prio/p2
