### ISSUE TITLE
Importing integration overrides "parent" integration

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5247] opened 2019-04-17 14:30 UTC
See also **https://issues.jboss.org/browse/ENTESB-11478**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
This would be more or less fine except for when a user wants to duplicate an integration, which IMHO is a valid use case. This way you have to "click" in the integration again. @syndesisio/uxd please let me know if this is intended, because I think the user should be able to duplicate an integration and try out to change it but have the original "safe". Is this use case covered by using different versions? Or could this be somehow more streamlined (adding a button to duplicate the integration so users don't have to go through exporting and importing)

## Steps to reproduce
Create an integration
Export the integration
Feel free to rename the original integration (but it won't change anything though)
And import the integration again
The original integration is now overwritten :(

**Comment by gashcrumb** [comment] 2019-04-17 14:42
We used to have a `duplicate` menu entry like a really long time ago, I can't recall why we removed it.

But yeah, the problem is the matching is only done by ID, so the name isn't taken into account at all.

**Comment by mastepan** [comment] 2019-05-07 13:23
> But yeah, the problem is the matching is only done by ID, so the name isn't taken into account at all.
What about to match by id and timestamp (time of the integration import)? 
Then we know the integrations have the same base but they are distinct ones.

- If I **import** the same integration **2nd time**, it's **name changes** to [original integration name]-imported-1

- If I do it **3rd time**, the integration **name doesn't change** anymore

- If I **edit the imported** integration, **save** it **and import the original** one again, the last imported integration remains. **The edited one disappears**.

**It can lead to a loss of saved integration configuration!**

This is P0 priority issue for me

**Comment by zregvart** [comment] 2019-06-11 15:21
There might be a use case for the user to import the older integration export as a poor man's means of undoing changes.

@mastepan would a warning suffice before the import, we can compare `updatedAt` timestamps? Something like: the integration being imported would overwrite a newer version of the same integration, are you sure you want this?

**Comment by mastepan** [comment] 2019-06-12 14:14
Why not to change the imported integration name to 
"**original name-imported-1**"
"**original name-imported-2**" and so on if "**original name-imported-1**" already exists?

I'd say it reflects the original intention and is smoother for a user.
The only decision factors are the integrations names and timestamps.

That would also fix the current strange behavior I've described.

The best would be also adding an information like:

_The imported integration name has been changed to "new integration name" because an integration with the name "original name" already exists._


Wdyt @zregvart ?

**Comment by zregvart** [comment] 2019-06-12 14:21
I think the reason why import overwrites existing integrations is that you can deploy from one enviroment to another (e.g. staging to production). Import can be done via APIs so if we do something differently we need to make a change in the API by adding a property that will indicate what to do if the integration with the same ID already exists.
We can certainly do what is suggested in https://github.com/syndesisio/syndesis/issues/5247#issuecomment-501293075 though we have to make sure that there is a way to do imports that will overwrite as well for the use case above.
To me this feels like a @gaughan question, what would you expect to happen here?

**Comment by dongniwang** [comment] 2019-06-12 16:38
Agreed with Zoran we have a use case for overwrites existing integrations https://github.com/syndesisio/syndesis/issues/5247#issuecomment-501295890. Is this still P0 for 7.4? 

A couple of thoughts: 
- Should inform users that overwrite will happen via helper text and a confirmation modal if we can detect the same name is being used
- It makes sense for me to follow a naming convention like "name-1", "name-2", "name-3", is there a reason why we cannot do that? 
- this sounds like a bug to me...
  - > If I do it 3rd time, the integration name doesn't change anymore

**Comment by heiko-braun** [comment] 2019-06-12 18:41
Looking at the initial description I really don't think this is a p0 bug:

> Create an integration
Export the integration
Feel free to rename the original integration (but it won't change anything though)
And import the integration again
The original integration is now overwritten :(

**Comment by zregvart** [comment] 2019-06-12 20:49
It's not that we can't ensure that imported integrations don't overwrite or get a unique name as a result of import if they were to overwrite. It's that the original use case for the import/export, as far as I remember, was to enable transitioning integrations between environments (that staging to production case), and in that case, again, as far as I remember, we decided that we need to overwrite the integration with the one being imported.
I could be wrong on this...

**Comment by gaughan** [comment] 2019-06-13 00:40
@zregvart I think you're right

**Comment by heiko-braun** [comment] 2019-06-13 06:34
Removing the p0 based in the comments in https://github.com/syndesisio/syndesis/issues/5247#issuecomment-501449944

**Comment by mastepan** [comment] 2019-06-13 11:28
@heiko-braun This is P0 because of possible integration loss without knowing that it will happen.
Please add P0 tag if you agree.

We can discus other use cases , select the best and implement it. If that solves P0 reason, the issue is fixed. If we create another issue for another use cases or review it here, we still need to fix this at least the way @zregvart  suggested in https://github.com/syndesisio/syndesis/issues/5247#issuecomment-501295890

@dongniwang 
> this sounds like a bug to me...
If I do it 3rd time, the integration name doesn't change anymore

I agree

**Comment by gaughan** [comment] 2019-06-13 15:33
@mastepan This is not a regression, right? 
If so we address in 7.5 by detecting and informing the user, giving an option to rename.

**Comment by mastepan** [comment] 2019-06-13 16:53
@gaughan I've checked it and it isn't a regression. I still believe we shouldn't allow loss of any data with no warning.

**Comment by gaughan** [comment] 2019-06-13 17:50
Great thanks for checking and agreed we should add a warning. With sprint end tomorrow we can look to move to 7.5 tho

**Comment by tplevko** [comment] 2019-06-20 08:30
I understand what @zregvart meant by the CI pipeline from staging to prod environment. In the current implementation it is a desirable use case - ending in overriding the existing integration. 

However the possibility to rename existing integration - with the intent to keep it as a deployment, not overriding it with the same previously exported integration, or as a part of CI/CD is also valid and should be handled correctly. 

Again - the potential data loss in this case is of concern in QE, even if this may sound as an edge case.

If it is decided, it won't be supported for this release - at least a documentation notice/warning in UI of this behavior should be provided? And from my POV a more appropriate handling - e.g. with not overriding the renamed integrations should be provided for the next release. WDYT?

**Comment by heiko-braun** [comment] 2019-09-07 11:52
Migrated to **https://issues.jboss.org/browse/ENTESB-11478**

**Closed by heiko-braun** 2019-09-07 11:52 UTC
Labels: cat/discussion, cat/enhancement, closed/migrated, source/qe
