### ISSUE TITLE
Can't create an integration

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#4604] opened 2019-02-15 21:48 UTC
## This is a...

<pre><code>
[ ] Feature request
[*] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Click 'Add Integration' and arrive at:

<img width="1173" alt="screen shot 2019-02-15 at 4 46 39 pm" src="https://user-images.githubusercontent.com/35576/52886200-8aa1b700-3141-11e9-8289-90b8f65d5154.png">

Where I can't connectors..

**Comment by gashcrumb** [comment] 2019-02-16 00:23
Clear your cache maybe?

**Comment by tplevko** [comment] 2019-02-18 11:29
This seems like a issue we encountered in QE: https://github.com/syndesisio/syndesis/issues/4523
@KurtStam can you look into the server-pod log?

**Comment by mkralik3** [comment] 2019-02-18 12:02
Workaround: scale server pod to 0 and back to 1 in OpenShift console.

**Comment by heiko-braun** [comment] 2019-02-21 16:38
@tplevko #4505 is done, can you verify if this issue still exists?

**Comment by tplevko** [comment] 2019-02-25 13:23
@heiko-braun yes, it seems to work correctly ever since Zoran's fix got merged. This one was difficult to reproduce, so in case we'll hit it again, we can open a new issue for this. Closing.

**Closed by tplevko** 2019-02-25 13:23 UTC
Labels: cat/bug, prio/p0
