### ISSUE TITLE
Twitter Direct Message function

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3521] opened 2018-08-30 19:37 UTC
As a citizen integrator, I want the ability to receive or output data via the Twitter Direct message function.

## Acceptance Criteria
- I can receive direct messages and send them to a log.
- I can receive timer events and send them via twitter direct message.

## DoD
- The feature owner has confirmed one of the following:
--There is an initial draft of the user doc for this feature. 
--The writer acknowledges receiving enough information from engineering to write the initial draft of the user doc for this feature.

**Comment by claudio4j** [comment] 2019-03-11 19:08
@oscerd can I work on this connector ?

**Comment by oscerd** [comment] 2019-03-11 19:11
Wasn't you working already on SQS?

**Comment by oscerd** [comment] 2019-03-11 19:11
By the way, no problem from my side :-)

**Comment by claudio4j** [comment] 2019-03-11 19:12
> Wasn't you working already on SQS?

No, I was about to work on google-drive, but priorities changed to twitter direct message.

**Comment by heiko-braun** [comment] 2019-03-11 20:17
Sorry, my bad. I have created quite some confusion. Feel free to grab sqs Andrea.

**Comment by oscerd** [comment] 2019-03-11 20:20
Can you create the issue?

**Comment by claudio4j** [comment] 2019-03-18 13:55
From the description:

> --There is an initial draft of the user doc for this feature.

Can you post the draft here ?

**Comment by wyvie** [comment] 2019-07-01 14:23
@claudio4j 
While testing this feature, I get error on the data mapping step, here is part of the log of the deployed integration:
```
io.atlasmap.api.AtlasException: Errors: [Unexpected exception is thrown while reading source field: java.lang.reflect.InvocationTargetException: docId='-LihpxxpuOg_BQwrUERj', path='/senderScreenName'],
	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:262) ~[camel-atlasmap-1.40.0.jar!/:1.40.0]
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71) ~[camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$TrackDoneEventProcessor.process(ActivityTrackingInterceptStrategy.java:121) [integration-runtime-1.7.6.jar!/:1.7.6]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:80) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.component.twitter.consumer.DefaultTwitterConsumer.poll(DefaultTwitterConsumer.java:98) [camel-twitter-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:174) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:101) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
```

Also same happens to `sender.screenName`. Any ideas what could possibly be wrong here?

**Comment by claudio4j** [comment] 2019-07-03 21:47
Can we close this issue, as the issue is in Done state.

**Closed** 2019-08-08 09:51 UTC
Labels: cat/enhancement, cat/user-story, closed/verified
