### ISSUE TITLE
OData connector causing error when creating integration

### ISSUE THREAD

**Issue by jsafarik** [syndesisio/syndesis#4791] opened 2019-03-07 13:26 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When I create OData connector (with https://services.odata.org/TripPinRESTierService/ sample service) and try to create integration I get "javax.ws.rs.NotSupportedException: RESTEASY003200: Could not find message body reader for type: org.jboss.resteasy.util.Types$1@2b0b08a5 of content type: */*" in server pod log. When I continue and create integration (odata -> split -> log), wait for it to start and then try to edit it (the integration), I am not able to update or ~~remove~~ (with --full-reset install of syndesis, I am able to remove the step) the OData connector from the integration.

## Tasks involved / Steps to Reproduce

1. Create OData connector (https://services.odata.org/TripPinRESTierService/ sample service)
2. Create integration odata -> split -> log
3. Check server pod log
4. Try to edit integration and ~~delete~~/update odata connector

**Comment by heiko-braun** [comment] 2019-03-08 14:25
@phantomjinx I guess this one is for you as well

**Comment by jsafarik** [comment] 2019-03-11 10:40
I got new exception with OData's read operation:
`o.a.c.component.olingo4.Olingo4Consumer  : Consumer Consumer[olingo4-olingo4-0-0://read] failed polling endpoint: olingo4-olingo4-0-0://read. Will try again at next poll. Caused by: [org.apache.camel.RuntimeCamelException - org.apache.olingo.client.api.communication.ODataClientErrorException: Path segment not supported: City) [HTTP/1.1 501 Not Implemented]]
org.apache.camel.RuntimeCamelException: org.apache.olingo.client.api.communication.ODataClientErrorException: Path segment not supported: City) [HTTP/1.1 501 Not Implemented]`

Not sure if this is caused by the exception reported in this GH issue or not, either way the read operation is not working properly for me (I am able to get the whole collection and single entity, but not individual property of entity).

### Steps to reproduce:
 1. Create integration with OData connector as start step
 2. Choose read action
 3. Choose "Airports" as Resource collection
 4. Enter `('KLAX')/Location` in the Entity Key Predicate

It would be useful if the connector logged to pod what Request URL it's trying to send.

**Comment by heiko-braun** [comment] 2019-03-14 15:24
How does #4848 relate to this? Are we talking about two different issues?

**Comment by jsafarik** [comment] 2019-03-15 12:41
@heiko-braun I was not sure if they are related or not, that's why I posted the sencond issue just as comment and that led to creation of #4848. Anyway, tried to reproduce this issue (#4791) with todays install of syndesis and the exception is no longer there.

**Comment by heiko-braun** [comment] 2019-03-15 12:52
thanks for the clarification @jsafarik

**Comment by phantomjinx** [comment] 2019-03-19 13:09
@jsafarik
I've been testing out the odata connector for the last few days, both specifically trying to replicate this bug and fix #4889 and I haven't been able to reproduce the error reported.

I am a little confused why we expect to have created an integration then delete the connector? If there is an existing integration that includes the connector, there is specific code in the UI that disables the connector delete function. Therefore, I think that is working as it should unless I've misunderstood.

@heiko-braun

**Comment by zregvart** [comment] 2019-03-19 14:22
In a fit of premature optimization I've added there can be a window of 3 seconds in which the `usage` field of a connector or extension is not updated to the latest value. Within that small window one could theoretically delete a connector.

If this is the root cause of the issue I can remove that 3 sec window.

Not sure about this being a `p0` in that case, users can delete a lot of things and end up in unexpected states. We should try our best to prevent that, though a lot of cases are asynchronous in nature only eventually consistent, this is due to our architecture and it's difficult to change without changing it.

**Comment by jsafarik** [comment] 2019-03-19 14:29
@phantomjinx @zregvart 
I meant deleting a connection from integration steps, not to delete the connector entirely from syndesis. Sorry for the confusion. But with todays syndesis installed it seems that I cant reproduce this issue anymore. The server log is exception free and after the integration is running, when try to edit or delete the connection from the integration steps it does what it's supposed to.

**Comment by phantomjinx** [comment] 2019-03-19 14:31
@jsafarik 
Damn ... I hate it when that happens! :-)

**Comment by phantomjinx** [comment] 2019-03-20 11:23
Going to close this subject to re-opening if errors re-occur.

**Closed by phantomjinx** 2019-03-20 11:23 UTC
Labels: cat/bug, prio/p0, source/qe
