### ISSUE TITLE
DataMapper returns null from api client connector even though the value exists

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#4077] opened 2018-11-12 14:59 UTC
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Data mapper is not able to take value from api client connector response, instead null is returned. The integration is between database and todo-app with usage of api client connector.

Check log body before and after data mapper step:
![screenshot_20181112_150814](https://user-images.githubusercontent.com/14313995/48354448-119e4980-e692-11e8-8198-32cfcc62d99c.png)

Data mapper:
![screenshot_20181112_150841](https://user-images.githubusercontent.com/14313995/48354466-1b27b180-e692-11e8-8bb2-088015854a09.png)

Integration:
![screenshot_20181112_150826](https://user-images.githubusercontent.com/14313995/48354480-22e75600-e692-11e8-8f15-4df8fb6d5923.png)

Steps to reproduce:
Scenario @DB-custom-api-connector-DB in following feature file:
https://github.com/syndesisio/syndesis-qe/blob/master/ui-tests/src/test/resources/features/integrations/api-client-connector.feature#L1

Syndesis version: 1.5.6.fuse-720003-redhat-00001

**Comment by zregvart** [comment] 2018-11-12 15:09
I think this one might be fixed with #3914 @mcada would you mind trying to run your integration on current `master` or from `1.5.x` branch?

**Comment by mcada** [comment] 2018-11-12 16:08
@zregvart It works on master.

**Comment by zregvart** [comment] 2018-11-12 20:36
@mcada thanks, I'll close this as duplicate of #3914

**Closed by zregvart** 2018-11-12 20:36 UTC
Labels: cat/bug, notif/triage, prio/p0, source/qe
