### ISSUE TITLE
[Custom connectors] Define dedicated metadata format for extension definition

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#1037] opened 2018-01-12 09:41 UTC
As today extension definition is based on syndesis model but in order to support syndesis internals upgrades we should define a dedicated and versioned metadata definition that should be translated to the syndesis model.

**Comment by nicolaferraro** [comment] 2018-01-15 16:57
I started to do #1056 and was thinking to this issue. Conceptually it is a good thing to go in this direction and create a metadata definition for users and another one for our rest services and mapping between the two.

But if we use java beans for the user-facing model, it will result in a duplicate of the core/model project, since the objects used in an extension are really complex, and they'll be more complex now that we want to introduce custom connectors.

I was thinking to an alternative approach:
- Add a schema version information in the generated extension object
- Create a converter project that:
  - takes the generated json (as raw jackson maps) 
  - applies a transformation if necessary and convert the content to core model

We can also add tests to validate generated schema of some sample projects against a json schema (we have generated it) to ensure that we handle model version changing correctly.

This way, we should not need a duplicate structure.

Wdyt @lburgazzoli ?

**Comment by lburgazzoli** [comment] 2018-01-15 17:34
That is ok to me however it may complicate the maven plugin as we need to enrich / generate the extension/connector model so we would need to use raw json stuffs.

**Comment by nicolaferraro** [comment] 2018-01-17 15:05
So the approach used in the PR is to convert from the public schema to the internal schema, do changes in the maven-plugin and convert back to the public schema when saving. The rest analyzer part has been adapted to convert from the public schema to the internal schema before saving the extension in the jsondb.

We can add a `schemaVersion` field (integer) but it may be missing in metadata fragments written by users. The only place where it can be used is when loading the extension from file in the rest part.

The field can be also stored in jsondb in the internal model. We can track this way if the uploaded extension was targeting a old schema. Also, the `syndesisVersion` used to create the extension seems important in this context. We can add both, or just the `syndesisVersion` to the metadata in both schemas. Wdyt @lburgazzoli ?

**Comment by nicolaferraro** [comment] 2018-01-17 15:11
It is also true that adding a `syndesisVersion` field is not useful, as syndesis version can be inferred from dependencies (`extension-api` is a mandatory dependency, right?).

**Comment by nicolaferraro** [comment] 2018-01-17 15:28
Let's go for adding a mandatory `schemaVersion` that is added automatically by the plugin.

**Closed** 2018-01-22 09:08 UTC
Labels: cat/enhancement, cat/tooling, module/extension, module/rest, target/tp4
