### ISSUE TITLE
Local build failure

### ISSUE THREAD

**Issue by seanforyou23** [syndesisio/syndesis#6384] opened 2019-08-15 13:16 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Trying to build latest master branch with `syndesis build --clean --flash` brings me to the following error;

<img width="1514" alt="Screen Shot 2019-08-15 at 8 43 35 AM" src="https://user-images.githubusercontent.com/5942899/63096909-1b185300-bf3d-11e9-85f0-bd0829b20353.png">

Is there a better command to use when building? If there's anything else I can provide to help diagnose please let me know!

Running macOS: 10.14.6

**Comment by seanforyou23** [comment] 2019-08-15 14:38
FWIW I ran the same build on `Linux 4.20.0-arch1-1-ARCH x86_64` and the build succeeded. Seems to be a mac only issue. Might that `sed` script be dropping the ball in some way?

**Comment by squakez** [comment] 2019-08-20 12:58
It seems a regression introduced by the new local S2I. I'll have a look asap and ask @seanforyou23 help for testing on mac.

**Comment by squakez** [comment] 2019-08-20 13:56
@seanforyou23 can you please edit your local copy of this file https://github.com/syndesisio/syndesis/blob/277fd5f3470035084f331f53208db7fa25505819/app/s2i/copy_mvn_repo.sh#L2
adding a new line with `set -x` and execute `syndesis build -f -c -i -m s2i`? I'd like to see the entire `sed` statement executed.

**Comment by seanforyou23** [comment] 2019-08-20 15:38
With additional `-x` flag
https://gist.github.com/seanforyou23/a51244d0c9588c6ed23f8ed0dfdd1620

With additional `-e` flag
https://gist.github.com/seanforyou23/707392cb970ca6b2704e8bba8e3e331e

**Comment by squakez** [comment] 2019-08-21 07:19
Thanks for the feedback. It seems the issue is the different behavior of `sed` command between `linux` and `macos`. Before submitting the PR I need you to please use this script locally and confirm it works correctly also on mac now: https://github.com/squakez/syndesis/blob/fix/6384_sed_regression/app/s2i/copy_mvn_repo.sh

In order to speed up the test you can simply build the s2i module without image push: `syndesis build -f -c -m s2i`

**Comment by seanforyou23** [comment] 2019-08-21 21:31
@squakez that seems to work just fine. https://gist.github.com/seanforyou23/822e712e2811e7f413341c48c8604b7a

Anything else I can help test?

**Comment by squakez** [comment] 2019-08-22 08:36
Thanks! yeah, please just approve the PR #6421 so it can be merged and working for any Mac user too!

**Closed** 2019-08-22 09:38 UTC
Labels: cat/bug, cat/build, prio/p0
