### ISSUE TITLE
[ui] [react] Salesforce connection validation is broken for username password connections

### ISSUE THREAD

**Issue by dhirajsb** [syndesisio/syndesis#5762] opened 2019-06-15 04:31 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When creating a new Salesforce connection with a username and password, validation fails due to an empty `refreshToken` property being sent to the verifier endpoint. 
This is also an issue for imported connections, where the stale imported `refreshToken` is sent to the verifier and fails. 
Also, when saving the connection after updating secrets in an imported connection, only user provided properties should be saved, as any generated secrets like `refreshToken` need to be regenerated using user provided `password` and `clientSecret`. 

## Expected behavior

The backend generated property (not provided by user) should be removed when validating and saving a connection after other properties are updated by user. 
## Screenshot

<img width="1407" alt="Screen Shot 2019-06-14 at 9 20 52 PM" src="https://user-images.githubusercontent.com/181691/59546951-65ecfe80-8eeb-11e9-87ce-7aa31f2e432f.png">

## Tasks involved / Steps to Reproduce

1.Create new Salesforce connection
2.Provide username, password, clientId and clientSecret
3.Click validate
4.See unparsed error on the top of the connection properties, see error response details in network pane of inspect window.

**Comment by riccardo-forina** [comment] 2019-06-15 06:08
Duplicate of https://github.com/syndesisio/syndesis/issues/5582

**Closed by riccardo-forina** 2019-06-15 06:08 UTC
Labels: cat/bug, group/ui, notif/triage, prio/p0
