### ISSUE TITLE
DB-to-DB integration: No action available

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2071] opened 2018-03-19 17:38 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Creating a DB-to-DB integration on master, doesn't allow you to specify the action for the end connection.

## Screenshot

![image](https://user-images.githubusercontent.com/99080/37612043-4d7c7124-2ba4-11e8-8eaa-066d2f1976e1.png)

## Tasks involved / Steps to Reproduce

1. New integration
2. Select "DB Connection"
3. Select "Periodic SQL" --> "select * from contact"
4. "Done"
5. Select "DB ConnectioN"
6. No action offered

**Comment by rhuss** [comment] 2018-03-19 17:40
Response of the last query
```json
{
  "description": "Invoke SQL or a stored procedure",
  "icon": "fa-database",
  "connectorCustomizers": [
    "io.syndesis.connector.sql.customizer.DataSourceCustomizer"
  ],
  "uses": 0,
  "id": "sql",
  "actions": [
    {
      "id": "sql-connector",
      "name": "Invoke SQL",
      "description": "Invoke SQL to obtain, store, update, or delete data.",
      "descriptor": {
        "componentScheme": "sql",
        "connectorCustomizers": [
          "io.syndesis.connector.sql.customizer.SqlConnectorCustomizer"
        ],
        "inputDataShape": {
          "kind": "json-schema"
        },
        "outputDataShape": {
          "kind": "json-schema"
        },
        "propertyDefinitionSteps": [
          {
            "description": "Enter a SQL statement that starts with INSERT, SELECT, UPDATE or DELETE.",
            "name": "SQL statement",
            "properties": {
              "query": {
                "deprecated": false,
                "labelHint": "SQL statement to be executed. Can contain input parameters prefixed by ':#'.",
                "placeholder": "for example ':#MYPARAMNAME'",
                "displayName": "SQL statement",
                "group": "common",
                "javaType": "java.lang.String",
                "kind": "path",
                "required": true,
                "secret": false,
                "type": "string"
              }
            }
          }
        ]
      },
      "tags": [
        "dynamic"
      ],
      "actionType": "connector",
      "pattern": "To"
    },
    {
      "id": "sql-start-connector",
      "name": "Periodic SQL invocation",
      "description": "Periodically invoke SQL to obtain, store, update, or delete data.",
      "descriptor": {
        "componentScheme": "sql",
        "connectorCustomizers": [
          "io.syndesis.connector.sql.customizer.SqlStartConnectorCustomizer"
        ],
        "inputDataShape": {
          "kind": "none"
        },
        "outputDataShape": {
          "kind": "json-schema"
        },
        "propertyDefinitionSteps": [
          {
            "description": "Enter a SQL statement that starts with SELECT.",
            "name": "SQL statement",
            "properties": {
              "query": {
                "deprecated": false,
                "labelHint": "SQL SELECT statement to be executed.",
                "displayName": "SQL statement",
                "group": "common",
                "javaType": "java.lang.String",
                "kind": "path",
                "required": true,
                "secret": false,
                "type": "string"
              },
              "schedulerExpression": {
                "defaultValue": "1000",
                "deprecated": false,
                "labelHint": "Delay in milliseconds between scheduling (executing).",
                "displayName": "Period",
                "group": "consumer",
                "javaType": "long",
                "kind": "parameter",
                "required": false,
                "secret": false,
                "type": "duration"
              }
            }
          }
        ],
        "split": {}
      },
      "tags": [
        "dynamic"
      ],
      "actionType": "connector",
      "pattern": "From"
    },
    {
      "id": "sql-stored-connector",
      "name": "Invoke stored procedure",
      "description": "Periodically invoke a stored procedure.",
      "descriptor": {
        "componentScheme": "sql-stored",
        "connectorCustomizers": [
          "io.syndesis.connector.sql.customizer.SqlStoredConnectorCustomizer"
        ],
        "inputDataShape": {
          "kind": "json-schema"
        },
        "outputDataShape": {
          "kind": "json-schema"
        },
        "propertyDefinitionSteps": [
          {
            "description": "Select the stored procedure.",
            "name": "Procedure name",
            "properties": {
              "procedureName": {
                "componentProperty": true,
                "deprecated": false,
                "labelHint": "Name of the stored procedure.",
                "displayName": "Procedure name",
                "group": "common",
                "javaType": "java.lang.String",
                "kind": "property",
                "required": false,
                "secret": false,
                "type": "string"
              },
              "template": {
                "componentProperty": false,
                "deprecated": false,
                "labelHint": "Stored procedure template to perform.",
                "displayName": "Template",
                "group": "producer",
                "javaType": "java.lang.String",
                "kind": "path",
                "required": true,
                "secret": false,
                "type": "hidden"
              }
            }
          }
        ]
      },
      "tags": [
        "dynamic"
      ],
      "actionType": "connector",
      "pattern": "To"
    },
    {
      "id": "sql-stored-start-connector",
      "name": "Periodic stored procedure invocation",
      "description": "Periodically invoke a stored procedure.",
      "descriptor": {
        "componentScheme": "sql-stored",
        "connectorCustomizers": [
          "io.syndesis.connector.sql.customizer.SqlStartStoredConnectorCustomizer"
        ],
        "inputDataShape": {
          "kind": "none"
        },
        "outputDataShape": {
          "kind": "json-schema"
        },
        "propertyDefinitionSteps": [
          {
            "description": "Select the stored procedure.",
            "name": "Procedure name",
            "properties": {
              "procedureName": {
                "componentProperty": true,
                "deprecated": false,
                "labelHint": "Name of the stored procedure.",
                "displayName": "Procedure name",
                "group": "producer",
                "javaType": "java.lang.String",
                "kind": "path",
                "required": true,
                "secret": false,
                "type": "string"
              },
              "template": {
                "componentProperty": false,
                "deprecated": false,
                "labelHint": "Stored Procedure template to perform.",
                "displayName": "Template",
                "group": "producer",
                "javaType": "java.lang.String",
                "kind": "path",
                "required": true,
                "secret": false,
                "type": "hidden"
              },
              "schedulerExpression": {
                "defaultValue": "1000",
                "deprecated": false,
                "labelHint": "Delay in milliseconds between scheduling (executing).",
                "displayName": "Period",
                "group": "consumer",
                "javaType": "long",
                "kind": "parameter",
                "required": false,
                "secret": false,
                "type": "duration"
              }
            }
          }
        ]
      },
      "tags": [
        "dynamic"
      ],
      "actionType": "connector",
      "pattern": "From"
    }
  ],
  "tags": [
    "verifier"
  ],
  "name": "Database",
  "properties": {
    "url": {
      "componentProperty": true,
      "deprecated": false,
      "labelHint": "JDBC URL of the database.",
      "displayName": "Connection URL",
      "group": "common",
      "javaType": "java.lang.String",
      "kind": "property",
      "required": true,
      "secret": false,
      "type": "string"
    },
    "user": {
      "componentProperty": true,
      "deprecated": false,
      "labelHint": "Username for the database connection.",
      "displayName": "Username",
      "group": "common",
      "javaType": "java.lang.String",
      "kind": "property",
      "required": true,
      "secret": false,
      "type": "string"
    },
    "password": {
      "componentProperty": true,
      "deprecated": false,
      "labelHint": "Password for the database connection.",
      "displayName": "Password",
      "group": "security",
      "javaType": "java.lang.String",
      "kind": "property",
      "label": "common,security",
      "required": false,
      "secret": true,
      "type": "string"
    },
    "schema": {
      "componentProperty": true,
      "deprecated": false,
      "labelHint": "Database schema.",
      "displayName": "Schema",
      "group": "common",
      "javaType": "java.lang.String",
      "kind": "property",
      "label": "common",
      "required": false,
      "secret": false,
      "type": "string"
    }
  },
  "dependencies": [
    {
      "type": "MAVEN",
      "id": "io.syndesis.connector:connector-sql:1.3-SNAPSHOT"
    },
    {
      "type": "EXTENSION_TAG",
      "id": "jdbc-driver"
    }
  ]
}
```

**Comment by gashcrumb** [comment] 2018-03-19 17:41
Duplicate of https://github.com/syndesisio/syndesis/issues/2062

**Closed by gashcrumb** 2018-03-19 17:41 UTC
Labels: cat/bug, notif/triage, prio/p0
