### ISSUE TITLE
Cannot open Syndesis Web UI

### ISSUE THREAD

**Issue by alexkieling** [syndesisio/syndesis#6329] opened 2019-08-07 13:20 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
After clicking on the route to the Syndesis Web UI and logging in, I see the following error page:

![syndesis 192 168 42 132 nip io_](https://user-images.githubusercontent.com/1910095/62625944-a28e1280-b8fc-11e9-8e96-5a7502bae50a.png)

Using latest code from master.

**Comment by zregvart** [comment] 2019-08-08 12:32
Duplicate of #6314?

**Comment by heiko-braun** [comment] 2019-08-08 15:43
@alexkieling Is it a duplicate?

**Comment by alexkieling** [comment] 2019-08-09 11:03
@heiko-braun @zregvart The bug seems to be the same one. After a fresh deployment of Syndesis (`syndesis minishift --install` in my case), the user sees the `Something is wrong` page when opening the UI.
Shall I close this issue?

**Closed** 2019-08-09 11:45 UTC
Labels: cat/bug, prio/p0
