### ISSUE TITLE
Amazon SQS Connector

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#4732] opened 2019-03-04 13:06 UTC
As a user I want ot be able to send and receive message from Amazon SQS queues.

## Related Resources

- https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/examples-sqs-messages.html

**Comment by oscerd** [comment] 2019-03-04 13:43
Is this for 7.4?

**Comment by oscerd** [comment] 2019-04-12 14:26
duplicate of #4843

**Closed** 2019-04-12 14:27 UTC
Labels: Epic, notif/triage
