### ISSUE TITLE
Advanced filter throws exception when message body is plaintext 

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#3149] opened 2018-07-23 09:48 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I have integration consists of http4 connection (which produces plaintext), AMQ connection:
![screen shot 2018-07-23 at 11 27 08](https://user-images.githubusercontent.com/6814482/43069501-8ae6cbe6-8e6d-11e8-9b83-8a340e47e4a6.png)

 and advanced filter with `${body} contains 'number'` expression. I'm getting following exeption in integrations pod:
```

  | {"exchange":"i-LI5UBV62B2_hQp5ECQ6z","step":"-LHs62QN3UerPfOI7WY5","id":"i-LI5UBVH2B2_hQp5ECQ9z","duration":5050540952}
  | {"exchange":"i-LI5UBV62B2_hQp5ECQ6z","status":"done","failed":false}
  | {"exchange":"i-LI5UCjx2B2_hQp5ECQDz","status":"begin"}
  | {"exchange":"i-LI5UCjx2B2_hQp5ECQDz","step":"-LHs6Abi3UerPfOI7WY5","id":"i-LI5UCk32B2_hQp5ECQEz","duration":8870706}
  | {"exchange":"i-LI5UCjx2B2_hQp5ECQDz","step":"-LHs5Slz3UerPfOI7WY4","id":"i-LI5UDyM2B2_hQp5ECQHz","duration":8723435}
  | {"exchange":"i-LI5UCjx2B2_hQp5ECQDz","step":"-LHs7t9A3UerPfOI7WY7","id":"i-LI5UDyV2B2_hQp5ECQIz","message":"Body: [number:9436] Log zo syndesisu"}
  | 2018-07-23 09:33:53.952  INFO 1 --- [ Session Task-2] -LHs5Eft3UerPfOI7WY4                     : Body: [number:9436] Log zo syndesisu
  | {"exchange":"i-LI5UCjx2B2_hQp5ECQDz","step":"-LHs7t9A3UerPfOI7WY7","id":"i-LI5UDyV2B2_hQp5ECQIz","duration":350469}
  | 2018-07-23 09:33:53.953  WARN 1 --- [ Session Task-2] i.s.i.runtime.util.JsonSimplePredicate   : Unable to apply simple filter to the given payload
  | 2018-07-23 09:33:53.959 DEBUG 1 --- [ Session Task-2] i.s.i.runtime.util.JsonSimplePredicate   : Unable to parse incoming message body as JSON needed for simple filtering
  | com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'number': was expecting 'null', 'true', 'false' or NaN
  | at [Source: org.apache.camel.converter.stream.InputStreamCache@2779bdba; line: 1, column: 8]
  | at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3528) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3502) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._matchToken(UTF8StreamJsonParser.java:2824) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:858) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:772) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3850) ~[jackson-databind-2.8.11.1.jar!/:2.8.11.1]
  | at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3799) ~[jackson-databind-2.8.11.1.jar!/:2.8.11.1]
  | at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2938) ~[jackson-databind-2.8.11.1.jar!/:2.8.11.1]
  | at io.syndesis.integration.runtime.util.JsonSimplePredicate.matches(JsonSimplePredicate.java:91) ~[integration-runtime-1.4-SNAPSHOT.jar!/:1.4-SNAPSHOT]
  | at org.apache.camel.processor.FilterProcessor.matches(FilterProcessor.java:65) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.FilterProcessor.process(FilterProcessor.java:51) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.process(ActivityTrackingInterceptStrategy.java:79) [integration-runtime-1.4-SNAPSHOT.jar!/:1.4-SNAPSHOT]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.DelayProcessorSupport.processDelay(DelayProcessorSupport.java:100) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.DelayProcessorSupport.process(DelayProcessorSupport.java:168) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.process(ActivityTrackingInterceptStrategy.java:79) [integration-runtime-1.4-SNAPSHOT.jar!/:1.4-SNAPSHOT]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:80) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.component.sjms.consumer.InOnlyMessageHandler.handleMessage(InOnlyMessageHandler.java:65) [camel-sjms-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.component.sjms.consumer.AbstractMessageHandler.onMessage(AbstractMessageHandler.java:86) [camel-sjms-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.activemq.ActiveMQMessageConsumer.dispatch(ActiveMQMessageConsumer.java:1401) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.ActiveMQSessionExecutor.dispatch(ActiveMQSessionExecutor.java:131) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.ActiveMQSessionExecutor.iterate(ActiveMQSessionExecutor.java:202) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48) [activemq-client-5.14.5.jar!/:5.14.5]
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
  | at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
  | {"exchange":"i-LI5UCjx2B2_hQp5ECQDz","step":"-LHs62QN3UerPfOI7WY5","id":"i-LI5UDyW2B2_hQp5ECQJz","duration":24378220}
  | {"exchange":"i-LI5UCjx2B2_hQp5ECQDz","step":"-LHs62QN3UerPfOI7WY5","id":"i-LI5UCkC2B2_hQp5ECQGz","duration":5035848330}
  | {"exchange":"i-LI5UCjx2B2_hQp5ECQDz","status":"done","failed":false}
  | {"exchange":"i-LI5UDyw2B2_hQp5ECQKz","status":"begin"}
  | {"exchange":"i-LI5UDyw2B2_hQp5ECQKz","step":"-LHs6Abi3UerPfOI7WY5","id":"i-LI5UDyx2B2_hQp5ECQLz","duration":10538289}
  | {"exchange":"i-LI5UDyw2B2_hQp5ECQKz","step":"-LHs5Slz3UerPfOI7WY4","id":"i-LI5UFCF2B2_hQp5ECQOz","duration":4500632}
  | {"exchange":"i-LI5UDyw2B2_hQp5ECQKz","step":"-LHs7t9A3UerPfOI7WY7","id":"i-LI5UFCK2B2_hQp5ECQPz","message":"Body: [smaller] Log zo syndesisu"}
  | 2018-07-23 09:33:58.997  INFO 1 --- [ Session Task-2] -LHs5Eft3UerPfOI7WY4                     : Body: [smaller] Log zo syndesisu
  | {"exchange":"i-LI5UDyw2B2_hQp5ECQKz","step":"-LHs7t9A3UerPfOI7WY7","id":"i-LI5UFCK2B2_hQp5ECQPz","duration":334694}
  | 2018-07-23 09:33:58.997  WARN 1 --- [ Session Task-2] i.s.i.runtime.util.JsonSimplePredicate   : Unable to apply simple filter to the given payload
  | 2018-07-23 09:33:58.998 DEBUG 1 --- [ Session Task-2] i.s.i.runtime.util.JsonSimplePredicate   : Unable to parse incoming message body as JSON needed for simple filtering
  | com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'smaller': was expecting ('true', 'false' or 'null')
  | at [Source: org.apache.camel.converter.stream.InputStreamCache@23d2cc50; line: 1, column: 15]
  | at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3528) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2686) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:878) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:772) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3850) ~[jackson-databind-2.8.11.1.jar!/:2.8.11.1]
  | at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3799) ~[jackson-databind-2.8.11.1.jar!/:2.8.11.1]
  | at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2938) ~[jackson-databind-2.8.11.1.jar!/:2.8.11.1]
  | at io.syndesis.integration.runtime.util.JsonSimplePredicate.matches(JsonSimplePredicate.java:91) ~[integration-runtime-1.4-SNAPSHOT.jar!/:1.4-SNAPSHOT]
  | at org.apache.camel.processor.FilterProcessor.matches(FilterProcessor.java:65) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.FilterProcessor.process(FilterProcessor.java:51) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.process(ActivityTrackingInterceptStrategy.java:79) [integration-runtime-1.4-SNAPSHOT.jar!/:1.4-SNAPSHOT]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.DelayProcessorSupport.processDelay(DelayProcessorSupport.java:100) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.DelayProcessorSupport.process(DelayProcessorSupport.java:168) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.process(ActivityTrackingInterceptStrategy.java:79) [integration-runtime-1.4-SNAPSHOT.jar!/:1.4-SNAPSHOT]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:80) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.component.sjms.consumer.InOnlyMessageHandler.handleMessage(InOnlyMessageHandler.java:65) [camel-sjms-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.component.sjms.consumer.AbstractMessageHandler.onMessage(AbstractMessageHandler.java:86) [camel-sjms-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.activemq.ActiveMQMessageConsumer.dispatch(ActiveMQMessageConsumer.java:1401) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.ActiveMQSessionExecutor.dispatch(ActiveMQSessionExecutor.java:131) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.ActiveMQSessionExecutor.iterate(ActiveMQSessionExecutor.java:202) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48) [activemq-client-5.14.5.jar!/:5.14.5]
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
  | at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]



```

**Comment by lburgazzoli** [comment] 2018-07-23 14:39
@mmelko can you attach your integration ?

**Comment by lburgazzoli** [comment] 2018-07-23 21:30
Is p1 correct ? 

this is not a bug but an annoying warning that appears as the filter tries first to apply the expression using OGNL against a json but if the payload is not a json, jackson may throw this exception which is then logged and the filter goes ahead and applies the expression as it is against the payload.

**Comment by mmelko** [comment] 2018-07-24 08:47
hmm I tried to create simple integration just for reproduce this but with no luck. I will investigate a bit.

**Comment by mmelko** [comment] 2018-07-24 11:05
@lburgazzoli It looks like message won't pass the filter because it's object message. Output from http connector is object type message instead of text. I should probably rename name of issue.

**Comment by lburgazzoli** [comment] 2018-07-24 11:14
so maybe also the expression need to be adapted

**Comment by heiko-braun** [comment] 2018-07-24 12:52
@lburgazzoli Since you started looking into already, I've added it to this sprint

**Comment by mmelko** [comment] 2018-07-24 14:11
Okay so here are my observations: 
 1.  this occurs only when HTTP component is involved 
 2. after change expression from `${body}` to `${bodyAs(String)}` everything works as exptected. 
 3. I've added log step right before filter with message body and message context checked:  
`
Message Context: [{breadcrumbId=i-LIBOkStzF4hu6Yq7QBZz, CamelHttpResponseCode=200, CamelHttpResponseText=OK, Content-Length=12, Content-Type=text/plain, Date=Tue, 24 Jul 2018 13:40:22 GMT, JMSDeliveryMode=2, JMSDestination=queue://guesses, JMSExpiration=0, JMSMessageID=ID:i-process-feedback-4-2whpg-38334-1532437712205-1:2:1:1:907, JMSPriority=4, JMSRedelivered=false, JMSTimestamp=1532439620992, Set-Cookie=c730435f1cc4db3e78e54344462b5b0d=b19af8dbd4d22040ef18df699b1ccbda; path=/; HttpOnly, Syndesis.STEP_ID=-LIBCjghq_amW8I94g4e, Syndesis.STEP_TRACKER_ID=i-LIBWEof-UP2Z1a04RdCz, X-Application-Context=application}] Body: [number:46542] 
`
4. Also added following expressions into next log-step : ` ${body} | as String: ${bodyAs(String)}`. Result was: `number:23987 | as String: number:23987` as you can see log step can convert object body to String properly 

5. Exception in log actually differs when filter is success:  (message should get trough filter):
`com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'number': was expecting 'null', 'true', 'false' or NaN
--
  | at [Source: org.apache.camel.converter.stream.InputStreamCache@766fd83b; line: 1, column: 8]`
VS message shoudln't get through filter: `com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'smaller': was expecting ('true', 'false' or 'null')
--
  | at [Source: org.apache.camel.converter.stream.InputStreamCache@6c4912c5; line: 1, column: 15]
  `

It seems that ${body} is converted differently in Log step that in advanced filter step and which might be a reason why messages never get through filter.

**Comment by lburgazzoli** [comment] 2018-07-24 15:35
So the http connector generates an exchange with body of type InputStream then the filter does two things:

1. it tries to convert to a Map<String, Object> and apply some OGNL filtering and this may fail if the InpuStream does not represent a valid json object
2. it then tries to apply the expression to the body as it is but as it is an InpuStream, a simple expression may fail too

In this case an explicit conversion (either using a step or inside the expression) is required so I guess we can close this issue and the related one.

I have [this](https://github.com/syndesisio/syndesis/pull/3160) PR ready to remove the warning and the exception as it is misleading: @mmelko @heiko-braun should we merge it ? 

@gashcrumb unrelated thing: maybe in the future the activity logging could have a "contextual status" so for filter it would display filtered/non filtered in addition to success/failure ?

**Comment by gashcrumb** [comment] 2018-07-24 15:42
> @gashcrumb unrelated thing: maybe in the future the activity logging could have a "contextual status" so for filter it would display filtered/non filtered in addition to success/failure ?

Can you raise an issue for this?  Am not 100% following but worth fleshing out as a requirement.

**Closed** 2018-07-25 08:48 UTC
Labels: cat/bug, prio/p1, qe/raised
