### ISSUE TITLE
DataMapper : inconsistent field mapping visiualization 

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#3833] opened 2018-10-15 10:09 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I define the mapping between two large objects:
- a SalesForce Case object
- a ServiceNow Incident object 

When defining the map, everything work as expected but when I'm getting back to my integration to change the mapping, the lines connecting the fields to map are inconsistent.

## Screenshot

![syndesis](https://user-images.githubusercontent.com/1868933/46944627-d3057700-d072-11e8-97c4-b9d75e89b4d9.gif)

## Tasks involved / Steps to Reproduce

1. Create an integration between SalesForce and ServiceNow
2. Map Case to Incident
3. Publish the integration
4. Edit the integration

**Comment by igarashitm** [comment] 2018-10-15 13:20
If runtime works correctly, it would be a line drawing issue in UI and might be related to atlasmap/atlasmap#565.
How can I create ServiceNow connection in the Syndesis to reproduce this? How can I get the credentials?

**Comment by lburgazzoli** [comment] 2018-10-15 13:47
I can create a new account on our test instance but you may have a faster dev experience if you create a data shape with a large number of fields.

**Comment by igarashitm** [comment] 2018-10-15 15:21
So far it doesn't reproduce with standalone AtlasMap. I would have to look in Syndesis anyway. It'll take a bit of time to understand how to create the extension...

**Comment by igarashitm** [comment] 2018-10-15 15:42
@pleacu any guess? in Syndesis mapping definition is passed as a property and directly processed via `MappingSerializer.deserializeMappingServiceJSON()` here:
https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts#L301-L315

**Comment by gashcrumb** [comment] 2018-10-15 15:45
It could also be kinda related to the issue I'm fixing for https://github.com/syndesisio/syndesis/issues/3789

**Comment by igarashitm** [comment] 2018-10-15 17:04
Also curious if there's some room to add safe guard from AtlasMap side instead of just showing broken lines.

**Comment by gashcrumb** [comment] 2018-10-15 17:13
Yep, probably still worth investigating.  That PR was merged so the changes are available on master.

Wonder, if it's a rendering problem, have we even just verified if it shows up or not with just twitter to salesforce perhaps?  I know I haven't personally put that integration together in quite awhile...

**Comment by igarashitm** [comment] 2018-10-15 17:19
This line drawing is the most dirty place in AtlasMap UI, it's not surprising if we break it again :-D

**Comment by igarashitm** [comment] 2018-10-15 22:39
I managed to restore twitter/salesforce credentials... yeah that reproduced with twitter>salesforce integration. It seems lines are not redrawn unless some mapping is selected. Once you select one of fields that is involved in mapping, then all lines are redrawn. I don't think this is p0 btw.

**Comment by igarashitm** [comment] 2018-10-16 01:17
It seems this only happens within Syndesis. Those inactive lines are drawn correctly from beginning even after reload or import in standalone. No idea why... could it be caused by the dependency difference, like Angular 6.0 vs. 6.1, etc?

**Comment by gashcrumb** [comment] 2018-10-16 01:52
I'll give it a test tomorrow and have a look, agreed it's probably not p0.

**Comment by lburgazzoli** [comment] 2018-10-16 07:40
I would say that it is not a p0 for technical reason but - imho - it is definitively a p0 for UX as the mapping step would be perceived as buggy even it is just a UI glitch.

**Comment by gashcrumb** [comment] 2018-10-16 12:36
@igarashitm wonder if it's anything to do with how the initialization logic is done in the host controller, there's a call to re-initialize the data mapper angular services in 2 spots, one in the constructor of the host component and another that gets kicked off via ngOnInit(), I kinda think we can get rid of the one in the constructor.

Also I notice that if I just switch to the table of mappings and then back the lines behave okay.

Lemme just re-understand what's going on in the host component and see if we can tidy that up a bit :-)

**Comment by gashcrumb** [comment] 2018-10-16 12:36
> Also I notice that if I just switch to the table of mappings and then back the lines behave okay.

Nope, I lied there, they don't behave correctly :-)

**Comment by gashcrumb** [comment] 2018-10-16 13:43
@igarashitm so adding this to the host component makes it behave better:

![image](https://user-images.githubusercontent.com/351660/47020208-de19df00-d126-11e8-9b65-2af627509460.png)

by manually triggering the event that the line machine component seems to act on for redraws.  The `setTimeout` causes the code to execute outside of the current change detection cycle and then another change detection cycle runs.  I'm not sure it's exactly the best fix though, what would normally cause that event to fire from the normal initialization path?  

Worst case we could keep it for now but I do like to try and find alternatives :-)  I wonder if this maybe came from reworking how the syndesis loading component there works perhaps, that kinda sped up a fair few pages and removed a lot of random code executing when it shouldn't have been.

**Comment by igarashitm** [comment] 2018-10-16 21:44
@gashcrumb yeah it indeed solves the issue. I actually tried calling `this.cfg.mappingService.notifyMappingUpdated()` in the `setTimeout()` and it works. But it doesn't work without `setTimeout()`.

In standalone, `notifyMappingUpdated() is invoked via this `handleMappingSaveSuccess()`
https://github.com/atlasmap/atlasmap/blob/master/ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-example-host.component.ts#L139

**Comment by gashcrumb** [comment] 2018-10-16 22:30
Maybe we should keep it then?  I'd definitely add a comment to explain why
the setTimeout is needed.

**Comment by igarashitm** [comment] 2018-10-16 22:38
+1, at least until we find better solution

**Comment by gashcrumb** [comment] 2018-10-16 23:00
Sounds good, I'll submit a PR with that change in syndesis tomorrow morning-ish

**Comment by igarashitm** [comment] 2018-10-16 23:06
For long term we'll need to clean up these messy state management in AtlasMap UI, maybe when we migrate to React.

**Comment by tplevko** [comment] 2018-10-18 13:51
@mmelko please verify the fix

**Closed** 2018-10-25 09:20 UTC
Labels: cat/bug, ext/atlasmap, group/ui, notif/triage, prio/p0
