### ISSUE TITLE
API Provider not saving return code

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3798] opened 2018-10-10 20:30 UTC
## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When I provide my API definition and set a return code in a flow, the return code is not updated on returning to the operations list.

## Expected behavior

Return code is updated.

## Screenshot

![kapture 2018-10-10 at 16 27 06](https://user-images.githubusercontent.com/674767/46764130-a71c7700-cca9-11e8-994e-1c26836c59f8.gif)

**Comment by amysueg** [comment] 2018-10-10 20:57
Well, that's true.
But what is really worse from a pure usability perspective is the control for selecting the return code in the first place. It scrolls out of the browser frame, and I imagine is very difficult to find the return code you are looking for. @michael-coker @jameslau @seanforyou23 -- can we substitute a different component for that "drop-down" (drop-up & down). Could that be handled here in this issue, or would it need to be a separate issue?

**Comment by jameslau** [comment] 2018-10-10 21:53
Hey @amysueg @gaughan, that is definitely an issue when dealing with so many options in a dropdown menu. The best solution I can think of is adding a scrollbar inside of the dropdown menu. I found a site that demos this solution (scrollable menu): https://www.bootply.com/86116. I'll need to see if PF has this option.

**Comment by michael-coker** [comment] 2018-10-10 22:20
Patternfly3 supports [bootstrap-select](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/bootstrap-select.html), which allows you to modify the size of the dropdown. Here are some [more examples](https://developer.snapappointments.com/bootstrap-select/examples/#menu-size). I'm not sure how difficult it would be to implement something like that since this is part of the form controls. Maybe @seanforyou23 can speak to that.

**Comment by amysueg** [comment] 2018-10-10 23:40
Thanks, @jameslau and @michael-coker. Hoping we and/or UI dev (@gashcrumb ) can resolve this. Plus @gaughan 's original request of course. :-)

**Comment by riccardo-forina** [comment] 2018-10-11 07:03
About the combobox, I have it in progress here https://github.com/riccardo-forina/patternfly-ng/tree/combobox
The original issue was #2673 which is very similar in scope.

The combobox is almost ready, I submitted [a first PR](https://github.com/patternfly/patternfly-ng/pull/448) where the lack of accessibility was pointed out and I completely rewrote it. I just have to finalize the component with the proper aria-roles, and write some tests. I'll do it in the next few days.

I guess once submitted and merged, we can simply upgrade the select to use the combobox.

About the original topic though, the problem is that from the app perspective editing an operation flow is really like editing any "standard" integration. So unless you hit the "Save as draft" button, any change done is lost. I guess this is again something about the Autosave feature #3048.

**Comment by zregvart** [comment] 2018-10-11 07:53
We had issues with data binding using Bootstrap select and dropped it, I'd be wary to introduce it again.

Also this issue is somewhat similar to #3776

**Comment by riccardo-forina** [comment] 2018-10-11 07:55
Right, that's the reason why I have been working on a bootstrap-combox-like but written from scratch in Angular, and with PF design principles in mind...

**Comment by gashcrumb** [comment] 2018-10-15 17:31
So the control thing as an aside, basically you *have* to click 'save as draft' before clicking on the "go to operation list" button, as I think when the operation list page loads it fetches the integration from the server and wipes out any local changes.

I propose for the first pass we make the "go to operation list" button there just do a save.

The more complicated option would be to add tracking to detect if the intergration's been changed or not via the editor and pop up a dialog asking the user if they want to save or discard the changes, but I dunno, I kinda dislike those naggy modals.

**Comment by gaughan** [comment] 2018-10-15 18:00
Agree on the modal point, I'm not a modal fan at all, but as code freeze approaches I accept we can only do so much.

**Comment by zregvart** [comment] 2018-10-15 18:11
So this is a duplicate of #3776?

**Comment by gaughan** [comment] 2018-10-15 18:16
Yes, I believe so.

**Closed** 2018-10-15 18:20 UTC
Labels: group/ui, notif/uxd, prio/p1
