### ISSUE TITLE
Integration S3>S3: FailedToCreateRouteException

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#933] opened 2018-01-05 15:19 UTC
I hit an exception when trying to create a S3>S3 integration. There seems to be an issue with the secret key in the integration, it's set to: "secretKey=xxxxxx"

The exception:
``
org.apache.camel.RuntimeCamelException: org.apache.camel.FailedToCreateRouteException: Failed to create route flow1: Route(flow1)[[From[aws-s3-polling-bucket-connector?accessKey... because of The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: 5E388EB207AE6FA8; S3 Extended Request ID: KB/LYi+eV6nAwWGl1IZY9tAGzEDyAxkqu6/8DWXe4QWAg0GUXOAIrhz6P64g4yBhPV250p7/LdU=)
``

The full integration pod log is attached.
[asdf-2-zx291.log](https://github.com/syndesisio/syndesis/files/1606956/asdf-2-zx291.log)

**Comment by oscerd** [comment] 2018-01-05 15:21
Usually this is because you didn't specified the right region. Where is your bucket located? What is the complete consumer path? How did you specified the region option?

**Comment by oscerd** [comment] 2018-01-05 15:27
Really weird. This seems something inserted by hand

**Comment by oscerd** [comment] 2018-01-05 15:36
This is because this is defined as secret in the schema

https://github.com/syndesisio/syndesis/blob/a49b35f89ec958d5e58abb23a50b7d1d2e2f70a8/app/rest/dao/src/main/resources/io/syndesis/dao/deployment.json#L1804

While accessKey is not secret. So it's the normal behavior.

**Comment by oscerd** [comment] 2018-01-05 15:38
So probably the client configuration, region and bucket are wrong in some way.

**Comment by tplevko** [comment] 2018-01-05 15:51
I tried this several times, because I also suspected that there is a problem in my configuration. But after several unsuccessful attempts I still can't get it up and running as I was able in the past. 
The buckets are located in US_WEST_1 (N. California) and I tried also to recreate the secrets for my account, but I always get the same issue.

**Comment by oscerd** [comment] 2018-01-05 15:58
I'll try to reproduce on Monday. Do you remember the last time it was working, maybe when we changed from "to" pattern to "from" pattern? This is really weird. Component didn't change, connector too.. Only the deployment.json and some text message.

**Comment by tplevko** [comment] 2018-01-08 07:41
Well, after all it seems like my configuration issue, it seems to be related to my new AWS account with restricted access rights, I'll investigate it further, but it seems like with the admin account it works. Sorry, my bad, I'll close this issue.

**Comment by tplevko** [comment] 2018-01-08 08:42
Ok, I think I figured it out. I tried this several more times and I think I found the source of the issue. 
My second account seems to work just fine. I tried several times to recreat the AWS access key and secret and I noticed something odd. 
Every time, the generated AWS secret did not contain any special characters (just alphanumeric), it worked fine and every time there was a "+" it did not. I am 95% sure, this is the source of the issue, could you please look into it?

**Comment by oscerd** [comment] 2018-01-08 08:43
I don't think I can do anything for this, this is something coming from the AWS SDK java.

**Comment by oscerd** [comment] 2018-01-08 08:44
https://forums.aws.amazon.com/thread.jspa?threadID=134011

**Comment by oscerd** [comment] 2018-01-08 08:44
and it seems it still happens
https://github.com/aws/aws-sdk-java/issues/1425

**Comment by oscerd** [comment] 2018-01-08 08:48
So, it's a problem from AWS SDK stuff.

**Comment by dsimansk** [comment] 2018-01-08 09:07
@kcbabo FYI we depend on a bug in AWS SDK to be fixed. Should S3 still go to TP3, wdyt?

**Comment by oscerd** [comment] 2018-01-08 09:15
We will always be dependent on bugs or status of AWS, so bringing it out of TP3 is not a solution.

**Comment by tplevko** [comment] 2018-01-08 15:50
@oscerd I investigated this further and found possible solution. It doesn't seem like the issue is in the AWS SDK, it's most probably camel-related. 
When creating camel routes, I noticed that when there is "+" sign in some of the route parameters, camel omits this sign and there is empty space instead. There is however "RAW()" keyword, which is used in such cases, the working camel route can be found here: https://gist.github.com/tplevko/048822eabe998ec53fb580433283f21a
Without the "RAW()" keyword, the route in my sample throws the same exception as the syndesis integration.
I don't know exactly, how the camel routes are generated on syndesis side, but I suppose this "RAW(....)" keyword could be used also on other places when generating camel routes, to prevent issues like this one.

**Comment by oscerd** [comment] 2018-01-08 15:54
We can try to find a way for this particular case, but in the SDK there are documented cases of problem with special characters in secretKey. I'm not sure if we can try to specify something in the connector schema. @lburgazzoli any idea for RAW ?

**Comment by oscerd** [comment] 2018-01-09 08:52
I can confirm we need to use RAW, probably this requires something on the Syndesis connectors and thus this will go in TP4. We were discussing this with @lburgazzoli

**Comment by oscerd** [comment] 2018-01-09 13:18
The possible workaround will change the connector too much. Since between TP3 and TP4 connectors will change, I change the target to TP4.

**Comment by lburgazzoli** [comment] 2018-01-09 13:23
@oscerd yeah, the workaround would require some deep changes to the current connector so I think it would be better to move this to TP4 and micrate the AWS connector to the "new style connectors" . 

I will open an issue to support RAW options.

**Comment by rhuss** [comment] 2018-01-09 15:52
@lburgazzoli @oscerd Is this a blocker for adding AWS connector to TP3 or is this only that we are going to fix this bug in TP4 ?

**Comment by oscerd** [comment] 2018-01-09 16:03
If you have a secret key with special character camel will encode URL the Uri. If you use a straight key like the one I have I didn't have problem. For sure it is a known bug. @lburgazzoli what do you think?

**Comment by lburgazzoli** [comment] 2018-01-09 16:29
I think it is more a PM decision to include it with a know issue or delay it to next TP

**Comment by kcbabo** [comment] 2018-01-09 16:53
My understanding from @dsimansk is that special characters in keys is a sometimes, not always, event with AWS.  If so, my vote would be to ship and document the limitation along with a workaround of regenerating the key until you get one without special characters.  Not ideal, but would still put us in a position to get feedback on the connector.

**Comment by oscerd** [comment] 2018-01-09 16:55
By the way with @lburgazzoli se should be able o add the RAW support  and migrate the connector as we did for the twitter stuff. This should be a problem only for TP3..

**Comment by rhuss** [comment] 2018-01-10 11:01
Ok, so we keep this bug issue open, and fix it with a rewrite of AWS connector with the new connector architecture in TP4.

**Comment by oscerd** [comment] 2018-01-29 08:18
This has been fixed with the RAW support from @lburgazzoli  :-)

**Closed by oscerd** 2018-01-29 08:18 UTC
Labels: cat/bug, module/connectors, target/tp4
