### ISSUE TITLE
[Datamapper] Transformation's delimiter not saved

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#4874] opened 2019-03-13 13:26 UTC
See also **https://issues.jboss.org/browse/ENTESB-11435**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Integration sql -> datamapper -> amq

```
1. open datamapper
2. map from one field to another
3. add source transformation
4. select concatenate
5. insert delimiter ,
6. click done
7. reopen datamapper to check the delimiter
8. comma isn't there
9. (bonus) there are now 2 concatenate transformations with empty delimiters, writing into one mirrors the input in the second
```

## Workaround
Press `<Tab>` key after step 5, so that the focus gets out from input field. Then delimiter is properly saved.

**Comment by igarashitm** [comment] 2019-03-13 15:00
Yes highly possibly, moving to atlasmap repo

**Comment by igarashitm** [comment] 2019-03-13 15:00
This issue was moved to atlasmap/atlasmap#827

**Comment by pleacu** [comment] 2019-03-20 19:25
It's back! :)

The issue is that if you're still in the delimiter input text field at the time you click 'Done' it isn't saved before AtlasMap is closed. The fix is to call the AtlasMap mapping service to save the current mapping within the SaveMappingHandler:

`--- a/app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
+++ b/app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts

 .subscribe((saveHandler: Function) => {
 .subscribe(async(saveHandler: Function) => {
   await this.cfg.mappingService.saveCurrentMapping();
   const json = this.cfg.mappingService.serializeMappingsToJSON();
   this.mappings.emit(JSON.stringify(json));
   this.cfg.mappingService.handleMappingSaveSuccess(saveHandler);
`
I consistently see the delimiter with this fix (the delim is duplicated because of #834)

**Comment by avano** [comment] 2019-03-22 09:18
looks ok now

**Comment by igarashitm** [comment] 2019-05-15 15:30
Reopening - we had to disable this fix due to #5365

**Comment by igarashitm** [comment] 2019-06-27 13:14
@gashcrumb @riccardo-forina now that AtlasMap UI is loaded into iframe, is it possible at all to caputure `Done` button event and deliver it into AtlasMap UI?

**Comment by riccardo-forina** [comment] 2019-06-27 13:33
Let me answer proposing a different take: can we get an event from Atlasmap when it start "processing" things so to disable the `Done` button 'til we get an updated mapping?

**Comment by igarashitm** [comment] 2019-06-27 14:15
That's possible, but that doesn't solve this specific issue. The problem is that unless user focuses out from input box, no event happen in AtlasMap UI. It means that we can lost the last input if user push `Done` button right after they input something like delimiter and push `Done` button.

**Comment by igarashitm** [comment] 2019-06-27 14:17
Ah, you mean we should disable the `Done` button until user focus out from input?

**Comment by igarashitm** [comment] 2019-06-27 14:18
It sounds like it's time to reconsider introducing `Save` button within AtlasMap. Maybe only for Syndesis usage.

**Comment by riccardo-forina** [comment] 2019-06-27 14:19
Yeah, something like that. As soon as they start changing something - simplifying, on a keydown event - Atlasmap tells Syndesis that something is changing. As soon as something actually did change - simplifying again, on blur out - we get the updated mapping and then we re-enable the button.

**Comment by igarashitm** [comment] 2019-06-27 14:24
I want to hear from @syndesisio/uxd - now we have 2 options to address this issue:
1. Disable `Done` button in Syndesis so that user can't push Syndesis `Done` button unless they focus out from AtlasMap UI input box
1. Introduce explicit `Save` button in AtlasMap UI
The former has `Save` action implicitly on focus out user action. We can still keep auto-saving even if we take latter, introduce `Save` button.

**Comment by dongniwang** [comment] 2019-06-27 18:28
Had a conversation with @igarashitm and @pleacu - I think we agree that for now will be using something similar to inline edit for text input box, so users would need to click a check mark for saving the text string they input.

**Comment by igarashitm** [comment] 2019-06-27 19:02
Filed AtlasMap issue - atlasmap/atlasmap#1055

**Comment by heiko-braun** [comment] 2019-09-07 11:28
Migrated to **https://issues.jboss.org/browse/ENTESB-11435**

**Closed by heiko-braun** 2019-09-07 11:28 UTC
Labels: cat/bug, closed/migrated, ext/atlasmap, group/ui, prio/p1, source/qe, zenhub/backlog
