### ISSUE TITLE
Support app identifier and key auth with 3scale (app_id/app_key)

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#5275] opened 2019-04-24 18:16 UTC
## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
As a citizen integrator I want to be able to authenticate with 3scale managed APIs via all available mechanisms. Currently 3scale supports: 
- API key (user_key)
- App identifier and keys (app_id/app_key)
- OpenID Connect (supported by Fuse online, OAuth2)

Fuse online should add support for: 
- App identifier and keys (app_id/app_key)
https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.4/html-single/api_authentication/index

Related:
- https://github.com/syndesisio/syndesis/issues/3629
- https://github.com/syndesisio/syndesis/issues/5112

**Comment by heiko-braun** [comment] 2019-09-05 10:21
@zregvart Is this still pending?

**Comment by zregvart** [comment] 2019-09-05 10:50
Duplicate of #3629

**Closed by zregvart** 2019-09-05 10:50 UTC
Labels: Epic, cat/enhancement
