### ISSUE TITLE
"No supported source type was found" when editing datamapper step

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#1895] opened 2018-03-08 11:18 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When edition an existing integration and clicking around, one eventually get an errror:

```
No supported source data type was found. Data type needs to be configured before Data Mapper step is added. 
```
## Expected behavior

No error should occur
## Screenshot

![image](https://user-images.githubusercontent.com/99080/37148302-44bb6898-22ca-11e8-9ba6-d252963c532a.png)

![image](https://user-images.githubusercontent.com/99080/37148374-8eb37878-22ca-11e8-9258-46ccb1805ee5.png)

## Tasks involved / Steps to Reproduce

1. Create integration as described in #1894 
2. Select integration from overview
3. "edit integration"
4. Select datamapper step
5. "Cancel"
6. Select initial connection
7. Select datamapper step again --> boom

**Comment by gashcrumb** [comment] 2018-03-08 14:17
I have a sneaking suspicion that the data shape gets overwritten on step 6 with a data shape that's missing a specification but will verify here first...

**Comment by zregvart** [comment] 2018-03-08 14:21
Yeah, that's the most likely culprit (#1886), now that has been merged perhaps we could try to provoke this on staging (when the [builds](https://circleci.com/gh/syndesisio/syndesis/tree/master) are done)?

**Comment by gashcrumb** [comment] 2018-03-08 14:31
So, I just pulled about an hour ago and rebuilt, response back is:

```
  "componentScheme": "sql",
  "connectorCustomizers": [
    "io.syndesis.connector.sql.customizer.SqlStartConnectorCustomizer"
  ],
  "inputDataShape": {
    "kind": "none"
  },
  "outputDataShape": {
    "kind": "json-schema"
  },
```

But it looks like the UI is posting an empty object at this point.  I think this is probably wrong, or we should be discarding the data shape here since we haven't provided any set configured properties.

**Comment by gashcrumb** [comment] 2018-03-08 14:53
Ah, so the empty object is actually by design so we get the first page of properties.  Am updating the editor so it won't update the data shape in the integration if there's no specification in this case, hopefully that should do the trick.

**Closed** 2018-03-08 15:44 UTC
Labels: cat/blocker, cat/bug, group/ui
