### ISSUE TITLE
Sf->DB integration "Invalid Operation syndesis_Lead_create"

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#668] opened 2017-12-08 12:00 UTC
The Sf->DB integration is not working. I followed the [SF->DB documentation](https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/7.0-tp/html-single/fuse_ignite_sample_integration_tutorial/) and created the integration. After I try to create new Lead in SF, the following error occured: 

```Caused by: org.apache.camel.FailedToCreateProducerException: Failed to create Producer for endpoint: salesforce-on-create-component://getSObject?rawPayload=true&sObjectName=Lead. Reason: java.lang.IllegalArgumentException: Invalid Operation syndesis_Lead_create```

Full integration log attached:
[integration.log](https://github.com/syndesisio/syndesis/files/1542537/integration.log)

**Comment by zregvart** [comment] 2017-12-08 18:09
Seems like the endpoint URI is no longer generated properly

**Comment by KurtStam** [comment] 2017-12-18 13:51
@zregvart can you elaborate?

**Comment by zregvart** [comment] 2017-12-18 16:02
The Salesforce Camel component looks for text after `:` to determine operation to perform, the exception claims that the text after `:` is `syndesis_Lead_create` (which should be the topic name). That leads me to believe that the endpoint URI created isn't properly formed.

From the log:

```
Caused by: java.lang.IllegalArgumentException: Invalid Operation syndesis_Lead_create
	at org.apache.camel.component.salesforce.SalesforceEndpoint.createProducer(SalesforceEndpoint.java:69) ~[camel-salesforce-2.20.1.jar!/:2.20.1]
```

**Comment by zregvart** [comment] 2017-12-19 13:40
I think this was fixed with #817

**Closed by zregvart** 2017-12-19 13:40 UTC
Labels: cat/bug, module/connectors, target/tp3

**Comment by dsimansk** [comment] 2017-12-19 13:41
@tplevko couuld you verify the fix pls?

**Comment by tplevko** [comment] 2017-12-22 16:23
It seems like there is still some issue prevailing, the integration can't successfully create new record in the DB. SF -> DB integration log attached. 
[sfDb.log](https://github.com/syndesisio/syndesis/files/1583006/sfDb.log)

**Comment by zregvart** [comment] 2017-12-23 20:43
@tplevko the exception in https://github.com/syndesisio/syndesis/issues/668#issuecomment-353630502 is caused by an connection that doesn't have OAuth client ID specified, can you make sure that the OAuth settings for Salesforce on the Connection are OK? If you set the OAuth settings for Salesforce and created a connection to Salesforce using the OAuth flow and still have the same exception then this is a bug and a new issue should be opened for it.

**Comment by tplevko** [comment] 2018-01-02 13:49
I tried this again manually on multiple setups and I am hitting always the issue mentioned in my comment above. I also think it is not really related to the original issue, it seems that salesforce connector has some issues, I'll create a new issue for this.
