### ISSUE TITLE
Export fails to exports the OpenAPI ResourceDefinition

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#3804] opened 2018-10-11 13:13 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
So upon importing let's say the TaskAPI-export.zip on

https://github.com/KurtStam/syndesis-quickstarts/tree/master/api-provider

It won't create any rest routes, leaving the end user frustrated. No errors are reported and all looks ok, but no endpoint is deployed.

**Comment by zregvart** [comment] 2018-10-11 13:17
From what I looked at, the issue is that the export doesn't contain OpenApi resource. We should export it along with the integration, i.e. go through referenced resources and include them in the export. We should also check if import will import resources.

**Comment by KurtStam** [comment] 2018-10-11 13:52
BTW this blocks me from sending @TovaCohen an export that works so that she can play with it and document things.

**Comment by KurtStam** [comment] 2018-10-11 14:33
@zregvart I tried the following:
https://github.com/KurtStam/syndesis/commit/d875f81a35c96e1f0a9862b74ecef012d17406fa

**Comment by KurtStam** [comment] 2018-10-11 18:16
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkcS-iBhDFfjWIGHYjlzlU2MtSIJEl80vopD7qneQxACxW2-O7

**Comment by heiko-braun** [comment] 2018-10-17 17:14
@KurtStam Please leave these items in the done column and open, when reopened after a PR was merged. This is to support the QE workflow.

**Comment by tplevko** [comment] 2018-10-29 13:15
@mkralik3 please verify the fix

**Closed** 2018-10-30 12:31 UTC
Labels: cat/bug, closed/verified, prio/p1
