### ISSUE TITLE
Unable to upgrade syndesis due to:   Required value: template.parameters[4]: parameter SAR_PROJECT is required and must be specified

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#3840] opened 2018-10-15 15:37 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I've tried upgrade of syndesis (from latest) but it's without any success due to: 

`error: unable to process template
  | Required value: template.parameters[4]: parameter SAR_PROJECT is required and must be specified`

full log: 
```
Now using project "syndesis" on server "https://172.30.0.1:443 ".
--
  | ### -----------------------------------------
  | ### PREFLIGHT CHECK
  | ### Upgrade from latest (latest) --> latest
  | ###
  | ### --> OK
  | ### -----------------------------------------
  | =============================================
  | === STARTING UPGRADE TO SYNDESIS latest
  | =============================================
  | === * Backup Resource objects (prep_10_backup_resources)
  | - ConfigMap
  | * syndesis-db-conf
  | * syndesis-meta-config
  | * syndesis-prometheus-config
  | * syndesis-sampledb-config
  | * syndesis-server-config
  | * syndesis-ui-config
  | - Secret
  | * syndesis-global-config
  | * syndesis-oauth-proxy-cookie-secret
  | * syndesis-server-secret
  | - DeploymentConfig
  | * syndesis-db
  | * syndesis-meta
  | * syndesis-oauthproxy
  | * syndesis-prometheus
  | * syndesis-server
  | * syndesis-ui
  | - Service
  | * syndesis-db
  | * syndesis-meta
  | * syndesis-oauthproxy
  | * syndesis-prometheus
  | * syndesis-server
  | * syndesis-ui
  | - Route
  | * syndesis
  | - RoleBinding
  | * syndesis:editors
  | * syndesis:viewers
  | - ServiceAccount
  | * syndesis-integration
  | * syndesis-prometheus
  | * syndesis-server
  | - Template
  | * syndesis-upgrade
  | - PersistentVolumeClaim
  | * syndesis-db
  | * syndesis-meta
  | * syndesis-prometheus
  | * syndesis-upgrade
  | - BuildConfig
  | === * Stopping syndesis-server (prep_15_stop)
  | deploymentconfig "syndesis-server" scaled
  | deploymentconfig "syndesis-meta" scaled
  | Waiting for syndesis-server to be scaled to 0
  | Sleeping 10s ...
  | NAME                          READY     STATUS        RESTARTS   AGE
  | syndesis-db-1-qngv8           1/1       Running       0          3m
  | syndesis-meta-1-qpzkp         1/1       Terminating   0          3m
  | syndesis-oauthproxy-1-nttks   1/1       Running       0          3m
  | syndesis-operator-1-d4nst     1/1       Running       0          3m
  | syndesis-prometheus-1-lldtd   1/1       Running       0          3m
  | syndesis-server-1-75wv2       0/1       Terminating   1          3m
  | syndesis-ui-1-qfkxq           1/1       Running       0          3m
  | syndesis-upgrade-latest       1/1       Running       0          40s
  | todo-1-build                  0/1       Completed     0          3m
  | todo-1-c8ztg                  1/1       Running       0          2m
  | syndesis-meta-1-qpzkp   0/1       Terminating   0         3m
  | syndesis-server-1-75wv2   0/1       Terminating   1         3m
  | syndesis-server-1-75wv2   0/1       Terminating   1         3m
  | syndesis-meta-1-qpzkp   0/1       Terminating   0         3m
  | syndesis-meta-1-qpzkp   0/1       Terminating   0         3m
  | Waiting for syndesis-meta to be scaled to 0
  | === * Backup database (prep_20_backup_db)
  | === * Process new template to extract update resources (prep_40_process_template)
  | - Current Syndesis version "latest"
  | error: unable to process template
  | Required value: template.parameters[4]: parameter SAR_PROJECT is required and must be specified
  | ====> Error ==> Rollback
  | ----- Rollback
  | --- * Rolling back 'Process new template to extract update resources'
  | --- * Rolling back 'Backup database'
  | --- * Rolling back 'Stopping syndesis-server'
  | deploymentconfig "syndesis-server" scaled
  | deploymentconfig "syndesis-meta" scaled
  | Waiting for syndesis-server to be scaled to 1
  | NAME                          READY     STATUS              RESTARTS   AGE
  | syndesis-db-1-qngv8           1/1       Running             0          3m
  | syndesis-meta-1-jhbql         0/1       ContainerCreating   0          2s
  | syndesis-oauthproxy-1-nttks   1/1       Running             0          3m
  | syndesis-operator-1-d4nst     1/1       Running             0          3m
  | syndesis-prometheus-1-lldtd   1/1       Running             0          3m
  | syndesis-server-1-vdflz       0/1       Running             0          4s
  | syndesis-ui-1-qfkxq           1/1       Running             0          3m
  | syndesis-upgrade-latest       1/1       Running             0          56s
  | todo-1-build                  0/1       Completed           0          3m
  | todo-1-c8ztg                  1/1       Running             0          2m
  | syndesis-meta-1-jhbql   0/1       Running   0         2s
  | Sleeping 10s ...
  | Sleeping 10s ...
  | syndesis-meta-1-jhbql   1/1       Running   0         26s
  | Sleeping 10s ...
  | syndesis-server-1-vdflz   1/1       Running   0         40s
  | Waiting for syndesis-meta to be scaled to 1
  | --- * Rolling back 'Backup Resource objects'
```

### Steps to reproduce
1. install syndesis on minishift (latest)
2. Try to upgrade syndesis (Catalog -> syndesis-upgrade)

**Comment by heiko-braun** [comment] 2018-10-16 07:54
@mmelko Duplicate of #3687?

**Comment by mmelko** [comment] 2018-10-16 08:11
@heiko-braun well root cause is the same, but this is happening during upgrade. In #3687 is about new installation I guess.  
@rhuss woudln't this affect also upgrade from 7.1.1 to 7.2 ? shoudln't be SAR_PROJECT parameter added also in 7.1.1 upgrade template?

**Comment by rhuss** [comment] 2018-10-16 09:08
@mmelko I'm on it, you can expect a PR with a fixed upgrade pod soonish.

**Comment by rhuss** [comment] 2018-10-16 09:09
@mmelko yes, the upgrade pod has to take care to use this new template parameter. This is not the case for the latest 1.4.10 upgrade pod, but will be fixed in a second.

**Comment by rhuss** [comment] 2018-10-18 09:28
Fixed with #3855

**Comment by tplevko** [comment] 2018-10-18 09:33
@mmelko please verify the fix

**Comment by mmelko** [comment] 2018-10-18 14:48
@rhuss now I'm getting

```
Waiting for syndesis-ui to be scaled to 0
--
  | === * Update resources (upgrade_40_update_resources)
  | - Executing any/01_ensure_sar_project_parameter.sh
  | Error from server (BadRequest): invalid character '\n' in string literal
  | ====> Error ==> Rollback
```

**Comment by rhuss** [comment] 2018-10-18 21:01
@mmelko could you please describe how you did the update (as I can't reproduce it) ? I mean, did you do it by installing the update pod manually or via the operator ?

**Comment by rhuss** [comment] 2018-10-18 21:07
I think I found it, the base64 command on centos breaks up the output into multiple lines by default (need to add a `-w 0` to prevent this). This is different than other base64 commands, so I will add tomorrow a feature detection for the proper call.

**Comment by rhuss** [comment] 2018-10-19 08:34
@mmelko should be fixed now. Could you please re-verify ?

**Comment by mmelko** [comment] 2018-10-19 15:12
@rhuss I can confirm that it's working now. Thanks!

**Closed** 2018-10-19 15:13 UTC
Labels: cat/bug, closed/verified, prio/p0, source/qe
