### ISSUE TITLE
Integrations - User is randomly redirected to the Datamapper upon creating a basic step

### ISSUE THREAD

**Issue by deeleman** [syndesisio/syndesis#2101] opened 2018-03-21 12:37 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
For some weird reason (mostly related to the fact that monster component of `IntegrationStepSelectComponent` redirects users depending on Integration select/update events), the user is randomly redirected to the datamapper (`/integrations/{id}/edit/step-configure/1`) while creating a basic step or even just by clicking on `Basic Step` upon choosing the step type upfront.

## Expected behavior

Once clicking on "Basic Step", users should stay at the edit basic step page/component all the time until they click elsewhere to leave that page.

## Screenshot

N/A

## Steps to Reproduce
1. Create an Integration and make sure there is a Datamapper intermediate step
2. Click "Edit Integration" and add a step BEFORE the Datamapper step. Choose "Basic Step".
3. At this stage, the problem might arise already. Otherwise got o [4]
4. Enter a filter step item and wait...

**Comment by gashcrumb** [comment] 2018-03-21 17:47
Damn, I can't seem to reproduce this.  From the code though I can see it's a definite possibility if the timing is wrong.

I think we can safely take this out [this block](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/step-select/step-select.component.ts#L95-L102), this is some leftovers from when the editor used to have some serious loading problems, as opposed to the occasional loading problems it has now, but hey, who clicks refresh these days?

If you get a second want to try commenting out that block and give it a test?  I could pull it out too but I'd rather have some way of verifying this sorts it.  Thanks!

**Comment by gashcrumb** [comment] 2018-04-17 17:48
I still can't reproduce this and I haven't seen anyone else hitting it, let's close this.

**Closed by gashcrumb** 2018-04-17 17:48 UTC
Labels: cat/bug, group/ui, prio/p1
