### ISSUE TITLE
Add support for sftp via public key

### ISSUE THREAD

**Issue by jsight** [syndesisio/syndesis#7174] opened 2019-11-20 17:11 UTC
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Currently the SFTP connector requires authentication via username and password. Many of our internal systems and partners require that authentication is done via public/private key pairs. It should be possible to pull the private key part of this from an openshift secret. In some cases, we may also wish to have separate pairs for each integration as well.

**Comment by zregvart** [comment] 2019-11-20 23:35
Duplicate of #2660

**Closed by zregvart** 2019-11-20 23:35 UTC
Labels: cat/enhancement, notif/triage
