### ISSUE TITLE
API provider returns data even if data type is not defined

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#6122] opened 2019-07-10 14:06 UTC
See also **https://issues.jboss.org/browse/ENTESB-11402**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
If I create this API provider definition: 
```
delete:
    tags:
        - tasks
        - destruction
    summary: Delete task
    description: Deletes task by given identifier
    operationId: 314844b1-3dad-4005-b3b2-d1c9d9463612
    parameters:
        -
            name: id
            in: path
            description: Task identifier to delete
            required: true
            type: integer
            format: int64
    responses:
        '204':
            description: Task deleted
```
I expect to get **NO** response, since it's not defined. But I get the result of SQL invocation which is last step that returns some data in the flow. Which is quite unpleasant and unpredictable. It would be better to return either nothing or have an explicit option of returning None in the definition, which would then cause the API provider finishing step not to return anything.

**Comment by zregvart** [comment] 2019-07-25 17:59
Duplicate of #4040?

**Comment by heiko-braun** [comment] 2019-09-07 10:49
Migrated to **https://issues.jboss.org/browse/ENTESB-11402**

**Closed by heiko-braun** 2019-09-07 10:49 UTC
Labels: cat/bug, closed/migrated, group/server, prio/p2, source/qe, target/7.5
